### ISSUE TITLE
To Read content of msgs.1.idx , msgs.1.dat

### ISSUE THREAD

**Issue by Ansudeen** [nats-io/nats-streaming-server#1029]
Hi, 
I'm using nats streaming server in file store mode , which is creating msgs.1.dat , msgs.1.idx , subs.dat and so on.

please help me how i can convert this binary to Ascii readable mode

**Comment by kozlovic** [comment]
Unless you are having issues, you could simply run a subscription with "deliver all available" starting point and get those messages. For instance, using the Golang client:
```
go run examples/stan-sub/main.go -id "reader" -all <channel name>
```
This will get all the messages in the channel and dump them in the console. You could redirect the output to a file.

Otherwise, you would need to write an application that deserialize content of these files. For subscriptions, you can look at https://github.com/nats-io/nats-streaming-server/blob/9c525aa99e00c9850debf61f17d382cc4a47c31e/stores/filestore.go#L3988.
For messages, it is a bit more complex, you could look at the lookup function: https://github.com/nats-io/nats-streaming-server/blob/9c525aa99e00c9850debf61f17d382cc4a47c31e/stores/filestore.go#L3304
