### ISSUE TITLE
`--signal reload`doesn't seem to reload the (embedded) NATS configuration file

### ISSUE THREAD

**Issue by costa** [nats-io/nats-streaming-server#1030]
I'm not sure if this is a bug or a feature request, but I'm building a tiny user mgmt server for nats-streaming and meanwhile, encountered the issue in the subject.
Now I'm sure that the signalling works because, if I replace `reload` with `quit`, the server does shut down. I'm not sure if nat-streaming is designed to reload the embedded NATS server configuration, but that would be really nice, because workarounds don't look pretty.

**Comment by costa** [comment]
My current workaround (which works) is to `docker restart` the server container, but it's suboptimal.

**Comment by kozlovic** [comment]
I can certainly quickly submit a PR that will "transfer" the reload signal to the embedded NATS Server (and will print a warning if there is no embedded NATS Server), but to be clear only NATS Server-specific configuration can be reloaded, not NATS Streaming. Would that still be something you would find useful?
(As of now, the suggestion was to have NATS Streaming remotely connect to a NATS Server so that one can reload the NATS Server. Suppressing the config reload was a simple way to avoid confusion that config reload does not apply to streaming-specific configuration).

**Comment by costa** [comment]
That would exactly be what I needed (since the auth comes from the NATS server), but I've just learnt of https://github.com/nats-io/nats-streaming-server/issues/788 and it may be a deal breaker for me, making (a lot of) my recent work obsolete, so I may be looking in another direction, like Redis.

**Comment by ripienaar** [comment]
Also consider our upcoming next gen streaming server that is better integrated with NATS core AAA and have some great new features. 

It’s still tech preview though. 

https://github.com/nats-io/jetstream
