### ISSUE TITLE
Increase in NFS IO, maybe related to caching

### ISSUE THREAD

**Issue by caarlos0** [nats-io/nats-streaming-server#1033]
Hey!

We run 2 nats-streaming-servers on the latest stable (0.17.0) in fault tolerant mode, having a NFS volume for sharing state.

In the past couple of days, the IO of that volume increased a lot:

![image](https://user-images.githubusercontent.com/245435/79341013-7dc55280-7f01-11ea-9053-ebf77c8ebe35.png)

Note that it increased a lot on apr/8-9. The sudden "down spikes" later are restarts of all nats servers (just in case)... in the latest we even cleared the whole state.

The message throughput is OK too:

![image](https://user-images.githubusercontent.com/245435/79341639-7f434a80-7f02-11ea-9919-dee3191a50f5.png)

![image](https://user-images.githubusercontent.com/245435/79341817-bfa2c880-7f02-11ea-93e0-18cb858081da.png)

Then, trying to find out why, the only thing "weird" I found was the cache hit rate:

![image](https://user-images.githubusercontent.com/245435/79341955-ebbe4980-7f02-11ea-8506-8bedf3fa5b45.png)

`gnatsd_subsz_num_cache`, `gnatsd_subsz_num_inserts` and `gnatsd_subsz_num_deletes` are basically the same as before... 

That being said:

1. how can I find what is causing the poor cache hit rate?
2. anything else I can do to improve it now? The NFS volume is provisioned by google and has limited throuhgput.

Let me know if can give any more information... 
Thanks for the great project BTW :)

**Comment by kozlovic** [comment]
@caarlos0 I cannot really correlate the cache hit rate of NATS Server with the IO increase. The cache hit metric is related to the subscription list: number of hits (subject found in the sublist cache) / number of times the server tried to Match a subject. The rate will be at-most 1.

Instead, since the IO events are mainly read events in your graph, I wonder if it could have coincided with starting subscriptions that are asking for all messages from the channel. If the channel is quite big, it will require Streaming server to read back from the beginning of the file(s) for this channel. Is that a possibility?

**Comment by caarlos0** [comment]
> @caarlos0 I cannot really correlate the cache hit rate of NATS Server with the IO increase. The cache hit metric is related to the subscription list: number of hits (subject found in the sublist cache) / number of times the server tried to Match a subject. The rate will be at-most 1.

hmmm, makes sense... I just pointed it out because it seemed to be the only metric that is very different since this issue begins.

> Instead, since the IO events are mainly read events in your graph, I wonder if it could have coincided with starting subscriptions that are asking for all messages from the channel. If the channel is quite big, it will require Streaming server to read back from the beginning of the file(s) for this channel. Is that a possibility?

I'm not sure, will check and get back to you.

Thanks for the pointers and the explanation :)

**Comment by kozlovic** [comment]
@caarlos0 You are welcome and thank *you* for the goreleaser project :-)

**Comment by caarlos0** [comment]
> I wonder if it could have coincided with starting subscriptions that are asking for all messages from the channel.

investigated here, we don't have anything like that 🤔

**Comment by kozlovic** [comment]
First, I have to ask: are we sure that the IO read metrics belong to the NATS Streaming Server and it is not possible that it is from some other processes running on this machine?

If those are from the server then do you know what has changed since you started seeing these spikes in IO reads? Have you recently upgraded or get more traffic?

When subscriptions keep-up, there should not even be a need for a IO read: when a message is accepted from a publisher it is stored in the store, then if there is matching subscriptions, information about that message being sent to matching subscriptions is stored in the channel's subs.dat file, then message is sent to the subscriptions' connection. The lookup of a message does not result in an IO read because the filestore implementation has a little cache that keeps recently written messages for 1 second. The message and subscriptions stores are then flushed before the ACK is sent back to the publisher.

If the subscriptions start to fall behind, then when a PUB message is persisted, the server does not send that message in place because it detects that the subscriptions have reached their "max inflight" messages. The sent to these subscriptions will happen when processing ACKs from them, since the number of outstanding ACKs will fall bellow the sub's MaxInflight option. At that time the server will lookup the message from the filestore, and if the subscription has fallen behind, that will result in an IO read.

The other reason I can think of where the server would have to do lots of read is when expiring messages. Since in the filestore configuration the server maintains almost nothing in memory, it has to read the index of a message to be expired to get information about that message in the msgs.x.dat files. The message index is a small record, but since v0.16.0 we have added read-ahead capabilities to the filestore implementation (https://github.com/nats-io/nats-streaming-server/pull/875) that makes 2MB reads (or whatever you have configured for the `-file_buffer_size` option). Do you have message age limits in some channels that could have kicked-in?
