### ISSUE TITLE
Selectively Pick A Message at Index for a subject

### ISSUE THREAD

**Issue by avinash92c** [nats-io/nats-streaming-server#1040]
This is something i used with kafka, i would store index of every message and read message by index(offset).
is there any provision in stan to read messages by index.? is it even a valid scenario in nats-streaming

**Comment by kozlovic** [comment]
Yes you can start a subscription at any sequence in the channel. Depending on the library you are using, it would be a subscription option such as: `stan.StartAtSequence(<sequence number>)`. More information can be found [here](https://docs.nats.io/developing-with-nats-streaming/receiving).

**Comment by avinash92c** [comment]
hi @kozlovic, i've seen this option.
i have the feature in kafka, i can request a single message at a particular index for reprocessing.
like open connection, Request Message in Subject at Index N. Read Process & Close Connection
is there something like that in nats streaming. just wanted to know if there was something like that

**Comment by kozlovic** [comment]
You can always create a subscription at a specific sequence, using MaxInflight(1), and closing the subscription after receiving processing the message (in the message handler itself). But you need to be aware of this:
- If you ask for a sequence lower than the first sequence available (because older messages have been removed due to channel limits), then the server will present you with the first available message, so your app should check that the sequence is the one desired.
- If you are asking for a sequence that has not been stored yet (say channel has messages 1 to 5 and you ask for sequence 10), then the server considers this a request to start with "new only messages", so at first the subscription will not receive anything. If message 6 is stored, then this message is delivered. So again, your app would have to check. This is the same if no message was ever stored in this channel.

In the second case also, since the subscription is async and there is no timeout, you may have to set your own timer to close the subscription should you not receive the message you are looking for.

```
sc.Subscribe(<subject>, <callback>, stan.StartAtSequence(<desired sequence>), stan.MaxInflight(1))
```

**Comment by kozlovic** [comment]
Closing since there were no new update for a long time.
