### ISSUE TITLE
Streaming server with multi-tenancy

### ISSUE THREAD

**Issue by guilherme-santos** [nats-io/nats-streaming-server#1043]
It's not clear to me how to achieve multi-tenancy using nats-streaming.

In [this link](https://docs.nats.io/nats-streaming-server/configuring/tls#authenticating-users) says I have to pass the authentication params to be able to connect the nats-streaming to ?the nats-server, but if I choose one user/password from one account I'm not able to publish/consume data from a different account, that's the idea of isolation.

Based on that, if I'm getting right, what's the best approach?

- Should I run one instance of nats-streaming per tenant?
- If I create a global user or token can I connect nats-streaming using it and then my clients will use the right credentials, based on the tenant?
- Any other possible approach?

**Comment by kozlovic** [comment]
NATS Streaming project was done before accounts and multi-tenancy were introduced in NATS 2.0. Although NATS Streaming embeds NATS Server 2.0+ now, it does not not have a good integration with the NATS 2.0/accounts/security concepts unfortunately. I would encourage you to have a look at JetStream instead (in tech preview at the moment) especially if you are starting a new project.

You could use a single account but it will have to be the same account for the server and all its clients so that the whole subject space is seen by both. NATS Streaming uses some special subjects to interact with its clients.

**Comment by guilherme-santos** [comment]
Ok, I took a look on JetStream and it looks promising, thank you for your answer.
