### ISSUE TITLE
Possibility for NACK?

### ISSUE THREAD

**Issue by hvt** [nats-io/nats-streaming-server#1049]
Hey there,

First of all, great project :+1:.

I am wondering a bit on how to handle this use case we are experiencing. We have a durable queue group, let's say A. Messages for some long during tasks are published to this channel / queue A. The subscriber has `MaxInFlight=1`, `SetManualAckMode`, and an `AckWait` of 3 minutes. Usually the task takes about 2+ minutes, therefore the long ack wait, avoiding redelivery to another subscriber in the meantime.

When the task runs successfully, the subscriber ACKs the message. However, sometimes processing fails, in that case the subscriber does not ACK the message. Most of the times when it fails, it fails pretty fast. Say after 30 seconds. Now the NATS streaming server will redeliver the message after 3 minutes. Which of course keeps the worker idle for 2.5 minutes. Therefore, it would seem great if the subscriber could NACK the message in such cases. The NACK would cancel the ack wait, but not flag the message as delivered. Making the redelivery mechanism kick in earlier.

But perhaps I'm missing a use case to change this behavior with the current implementation. Would one for example ACK the message in case it is unsuccessful, and republish it in the subscriber itself?

**Comment by ripienaar** [comment]
Unfortunately Streaming Server does not have NACK and I don't think we will add it.

We are working on the successor of Streaming Server at the moment and as this was a feature request we've had numerous times it will support NACK, have a look at https://github.com/nats-io/jetstream#readme

**Comment by kozlovic** [comment]
@hvt Thanks for the compliment. As RI mentioned, we don't have a NACK in NATS Streaming, but JetStream will offer something like that.

That being said, there is a way to force a redelivery of that message, it is to close the subscription. When doing so, the server will detect that the member is leaving with an unacknowledged message and will redeliver to an existing member.
It is not the same, but at least this message will be redelivered right away. That being said, if existing members just started to deal with some message and their processing takes time, that redelivered message will be sent to a member and will have to wait for the current message to be done before being dispatched.
If there are no pending messages on the channel that need to be sent, then if your app first adds a member and then close the subscription, this message will likely be delivered to the new subscription since it won't have any pending message (compared to the other ones processing messages).

**Comment by hvt** [comment]
Thanks for the reply.

Ah nice, didn't know about JetStream, looks good! Seems this will help some of our other use-cases too :muscle:.

About the close subscription 'hack', that will do for now. Thank you very much!
