### ISSUE TITLE
Receive duplicated message in supercluster

### ISSUE THREAD

**Issue by wade19870531** [nats-io/nats-streaming-server#1054]
I setup a supercluster and nats streaming like this:
nats-streaming1 (leaf)->nats-server cluster 1 <--> nats-server cluster cluster2<-nats-streaming 2(leaf)

However, when my subscriber connected to nats-server cluster 1(streaming connection) and my sender connected to nats-server cluster 2(streaming connection) to send a message, The subscriber received two same message . One from nats-streaming 1. Another from nats-streaming 2.
If a nats-streaming cluster removed, the subscriber receive one message.

Whether a supercluster can't exist more than one nats-streaming cluster (same cluster id)?

**Comment by wallyqs** [comment]
that's right, each nats-streaming server has to be under its own account separate account in case they are using the same cluster id, then use something like the [replicator](https://github.com/nats-io/nats-replicator) in case have to bridge or map the subjects of the two remote clusters

**Comment by kozlovic** [comment]
Are the NATS Streaming servers running in standalone mode on the leafs? If so, and if they have the same cluster ID, I would even have expected the second started to fail reporting that it discovered the a cluster running with the same cluster ID.

**Comment by wade19870531** [comment]
@wallyqs thanks. It works for me.
@kozlovic Nats streaming servers run with cluster mode on the leafs. As following:
kubernetes cluster 1 (istio main cluster):
```
NAME               READY   STATUS    RESTARTS   AGE
nats-accounts-0     2/2     Running   0          84m
nats-replicator-0   2/2     Running   1          13m
nats-server-v1-0    2/2     Running   2          83m
nats-server-v1-1    2/2     Running   1          83m
nats-server-v1-2    2/2     Running   2          83m
nats-streaming-0    2/2     Running   0          83m
nats-streaming-1    2/2     Running   0          83m
nats-streaming-2    2/2     Running   0          83m
```

kubernetes cluster 2 (istio remote cluster):
```
NAME                  READY   STATUS    RESTARTS   AGE
nats-server-v2-0      2/2     Running   2          20h
nats-server-v2-1      2/2     Running   2          20h
nats-server-v2-2      2/2     Running   2          20h
nats-streaming-0    2/2     Running   0          83m
nats-streaming-1    2/2     Running   0          83m
nats-streaming-2    2/2     Running   0          83m
```

**Comment by kozlovic** [comment]
Thanks, that explains why there was no report of other instance. I just tested (with manual configs) and having 2 clusters sharing the same cluster ID and node IDs, on the same NATS network, is really bad because the current node leader, say node "a" takes over on the second cluster. If the 2nd cluster is started after say a client has connected, and that client has the connection lost handler set, it would get disconnected when the "false" leader starts because it will answer to client PINGs and say that it does not know about it.
So I am not sure how we can detect this misconfiguration, unfortunately, so you need to be very careful. I am closing this issue for now.
