### ISSUE TITLE
nats-streaming poor performance than nats-server

### ISSUE THREAD

**Issue by ariacop** [nats-io/nats-streaming-server#1069]
hi
nats streaming server seems very slow than nats server even with memory store .
i wrote a sample publish message class that publish 100000 messages with 100 bytes size.
note that both servers runs with default config.

my pc result: intel core i3:
nats server result:
Produced 100000 msg in 375 ms | 266667 msg/s

nats streaming result:
Produced 100000 msg in 24972 ms | 4004 msg/s

with file storage  it will be 56 msg/s

i ran the code in 3 environment:  my windows pc (core i3) and our windows server (xeon 2650)  and even linux server (xeon 2650) and poor performance of streaming is the same on all condition.

i dont know whats the problem, please help
thanks in advance

**Comment by kozlovic** [comment]
Because when you use NATS Streaming, each publish is equivalent to a request/reply with the NATS Streaming Server to ensure that the published was received by the server. If you repeat a benchmark with NATS Server and do request/reply, you will see that you get lower numbers than your original numbers.
With streaming, were you publishing synchronously or asynchronously? (the second is fastest since a publish does not wait for the reply in place, allowing messages to be buffered and processed in a batch in the streaming server.
Regardless, do not expect same performance between NATS Server and Streaming Server (even with memory store) because of the protocol in streaming.
As for the file store poor performance, it all depends on the disk you have. Is it an SSD? What exact test were you running? If you start consumer and request old messages while producing new ones, the server will have to read from the channel, which will slow down things. Also, you can improve perf by disabling fsync on each write (`-file_sync=false` or look at `-file_auto_sync <duration>`).

**Comment by kozlovic** [comment]
Closing this issue for now.
