### ISSUE TITLE
Can we publish to NATS server as well if NATS streaming server is running?

### ISSUE THREAD

**Issue by hsahuntnx** [nats-io/nats-streaming-server#1078]
hi @kozlovic 
I've requirement to come up with a messaging service where we can publish and consume messages with and without persistence. I've deployed NATS streaming server in clustered mode (3-node) with standalone NATS server (not embedded one). I was able to connect to NATS server by just changing the client library from `stan.go` to `nats.go` but I am wondering whether NATS server will run in clustered mode or not (I want to support usecases like publisher is on 1.1.1.1 publishing on NATS server and subscriber is on 1.1.1.2 consuming from NATS server).

here is my NATS streaming server configuration file.
```text
port: 4222
cluster: {
	"listen": "0.0.0.0:6222",
	"routes": [
		"nats-route://1.1.1.2:6222",
		"nats-route://1.1.1.3:6222"
	]
}

streaming: {
	"sd": true,
	"id": "nats-streaming-cluster-poc",
	"store": "File",
	"dir": "/data/nats_data_dir/filestore",
	"cluster": {
		"log_path": "/data/nats_data_dir/cluster_log_path",
		"node_id": "1.1.1.1",
		"peers": [
			"1.1.1.2",
			"1.1.1.3"
		]
	},
	"tls": {
		"client_ca": "/config/certs/ca.pem"
	},
	"file_options": {
		// // some configuration 
	},
	"store_limits": {
		// some configuration 
	}
}

tls: {
	"cert_file": "/config/certs/server.crt",
	"key_file": "/config/certs/server_key.pem",
	"ca_file": "/config/certs/ca.pem",
	"insecure": false
}
```

Thanks in Advance!!!

**Comment by kozlovic** [comment]
> I've deployed NATS streaming server in clustered mode (3-node) with standalone NATS server (not embedded one).

That is not what the configuration you posted shows. It shows that you are defining the NATS cluster in the streaming config (the `cluster{}` block before `streaming{}` and you do not specify a `nats_server_url` in `streaming{}` config, you are not connecting the NATS Streaming server to a remote NATS server.

That being said, NATS Streaming when running with embedded NATS Server well just does that: embeds a NATS Server. So you can use NATS connections (non streaming) to communicate with the NATS Server. Most streaming libraries expose their NATS connection so that you can conveniently use core NATS if your application needs to do both. Actually stan.go does use nats.go internally.

So you could deploy your streaming cluster and still use both streaming and core NATS from your application.

**Comment by kozlovic** [comment]
Closing this for now. Will re-open if you still have questions.
