### ISSUE TITLE
Publish ack failure suggestion

### ISSUE THREAD

**Issue by cemremengu** [nats-io/nats-streaming-server#1081]
We are using this snippet for publishing:

```golang
    ackHandler := func(ackedNuid string, err error) {
        if err != nil {
            log.Printf("Warning: error publishing msg id %s: %v\n", ackedNuid, err.Error())
        } else {
            log.Printf("Received ack for msg id %s\n", ackedNuid)
        }
    }

    nuid, err := sc.PublishAsync("foo", []byte("Hello World"), ackHandler) // returns immediately
    if err != nil {
        log.Printf("Error publishing msg %s: %v\n", nuid, err.Error())
    }
```

In this case when we get an ack error it looks like there is no automated retry.  So what is the suggested way to do? Is there a code snippet or suggested libraries?

**Comment by kozlovic** [comment]
Indeed, the library does not to any retry. Let me first preface that if this is a new project, I would recommend that you look into JetStream (that is in tech preview at the moment and part of nats-server directly: https://github.com/nats-io/nats-server and https://github.com/nats-io/jetstream for more info) since it will have publish de-dup, which NATS Streaming does not have.

When getting an error on publish, you are left with deciding if you should publish again. When getting an error (non timeout) it is likely that the message was not persisted by the server, so resending is a good/safe option. The problem is that there is always a risk that the failure to get the ack occurred after the server persisted the message and before/just after it sent the publish ack back to the client.

The issue is that NATS Streaming does not offer publish de-dup, so if your applications cannot deal with duplicate published messages, then you would have to somehow create a subscription on the flight to find out if the message has been stored or not. Depending on the context it could be as simple as creating a subscription with "last received" option that will send you the last message stored and you can check if that was the last message that you published, but that would work only if there is a single publisher. Otherwise, you may want to create that subscription with a start sequence that you know is prior to the failed send or based on time (say 1 second ago) to get past messages from the give sequence/time and again try to find out if the failed published actually made it or not.

This is obviously not ideal and therefore why I suggest that you look at JetStream if early in your project.

**Comment by cemremengu** [comment]
JetStream looks great, been looking forward to it for sometime.

However we will need clustering unfortunately so hopefully it will be available soon. 

One more thing, is it possible to use all existing nats clients with it like java client?

**Comment by kozlovic** [comment]
> One more thing, is it possible to use all existing nats clients with it like java client?

Yes, since JetStream is core NATS. However, we may provide helpers either as dedicated library or part of the NATS library to help users decode acks, etc..
