### ISSUE TITLE
Request-response

### ISSUE THREAD

**Issue by 3dmagicus** [nats-io/nats-streaming-server#1093]
Hello everyone!
Is it possible to send a request with a guaranteed response from one client to another client via nats-streaming (by request-response type).

**Comment by kozlovic** [comment]
Request-response does not make much sense in NATS Streaming. Publisher(s) and Subscriber(s) are de-coupled.
Publisher sends a message and gets an acknowledgement that the server persisted the message. At this point no subscriber may even be running. Later, when interest is created (and based on the starting point of the subscription decided by the user), the server sends a message to the subscriber and receives an ACK from the subscriber so that this message is not redelivered to THIS subscription. However the message is not removed from the channel. Only channel limits (count/size/age) causes the server to remove messages.

So I am not sure what you refer to with "guaranteed response from one client to another", but doing simple (no streaming) request/response already gives you the guarantee that if the response is received from the responder then the message has been processed. You would have to decide what to do (resend, ignore, etc) when not receiving a response.

Now, you are free to have subscriber applications send a message back based on some reply subject that you can encode in your message, but again, given the above, that does not make much sense since the same "request" message in a channel can be received multiple times (or never) by many different subscriptions.

**Comment by 3dmagicus** [comment]
Yes, 'guaranteed' it didn't need to be written. Anyway thanks for the explanation.
