### ISSUE TITLE
restarting nats streaming server client connections dont recover 

### ISSUE THREAD

**Issue by tanzeelrana** [nats-io/nats-streaming-server#1117]
On a fresh install when things are working fine we can see 7 clients and 12 channels(subscriptions) 

![Screen Shot 2020-10-29 at 4 49 27 PM](https://user-images.githubusercontent.com/2520028/97631060-cf997a00-1a06-11eb-8212-30e81fbb610e.png)

![Screen Shot 2020-10-29 at 4 49 34 PM](https://user-images.githubusercontent.com/2520028/97631076-d2946a80-1a06-11eb-9e48-7a5eb956e551.png)

After we restart the nats-streaming-server service these counts drop and some channels and client connections are unable to recover. 

![Screen Shot 2020-10-29 at 4 50 55 PM](https://user-images.githubusercontent.com/2520028/97631248-0a9bad80-1a07-11eb-84f6-542582c84b06.png)
![Screen Shot 2020-10-29 at 4 51 26 PM](https://user-images.githubusercontent.com/2520028/97631257-0e2f3480-1a07-11eb-9c8d-ddc374acb0ce.png)

I added a connectionListener on all streaming connections to debug further, looking at the debug logs it looks like we get a disconnect -> connect -> resubscribed events in order when i restart the nats streaming server. 

<img width="1302" alt="Screen Shot 2020-10-27 at 9 35 22 PM" src="https://user-images.githubusercontent.com/2520028/97631382-4171c380-1a07-11eb-90a9-8b2afbd422b2.png">

Observing the connection events being fired on a nats streaming server restart it looks like all client connections and subscriptions have recovered successfully but that is not the case as we have seen from the nats streaming server metrics and also grafana metrics. 

I am using nats java stan library 
https://github.com/nats-io/stan.java

Does anyone know why my clients and subscriptions never come back even though the connection events say that everything is connected and resubscribed ?

**Comment by kozlovic** [comment]
Are you running the Streaming server with file store/db or memory store? If the later, then there is no state and streaming client connections are lost.
Also, the reconnect/resubscribe is just for low level NATS connection/subscriptions. Streaming clients are a level above. You need to be careful when setting the streaming client-to-server pings that you are allowing enough time for the server to restart/recover state otherwise the client will report the streaming connection as permanently lost.

Check [this](https://docs.nats.io/nats-streaming-server/configuring/persistence) and [this](https://github.com/nats-io/stan.go#connection-status). The later is for Go client, but principle is same for other libraries.

**Comment by kozlovic** [comment]
Actually more information [here](https://docs.nats.io/nats-streaming-concepts/client-connections#note-important-things-to-know-about-reconnections)

**Comment by kozlovic** [comment]
Closing this issue for now. Will re-open if new information is provided.
