### ISSUE TITLE
How to delete uneeded channels?

### ISSUE THREAD

**Issue by gromas** [nats-io/nats-streaming-server#1121]
I create an application for persistent logs. But time from time I need delete old unneeded logs. This occurs one time in day / week and needed for free a disk space while log size is some gigabytes. Please tell me a way to delete old channels? Thank you advance.

**Comment by kozlovic** [comment]
This can only be done with `max_inactivity` setting at the moment, but this is not what you really want I assume. This configuration causes the server to delete a channel for which there is no new message added or no new subscription started on it for that amount of time. In that case the server deletes the channel at runtime.

If the above configuration does not fit your requirements, there is unfortunately no other way but to stop the server and manually delete the directory corresponding to the channel. Note that in cluster mode, it may not even be possible (and possibly "breaking" the state) because it could be immediately recreated if there are still messages in the raft logs.

We started to add ability to send some commands through NATS to the streaming server, so maybe we could do the same for deleting a channel (see https://github.com/nats-io/nats-streaming-server/pull/1090 for details).

**Comment by gromas** [comment]
Thank you kozlovic for your message. max_inactivity 25h is ideal for me - I can publish "ping" every 24 hours and keep channel for stay alive.

**Comment by kozlovic** [comment]
Great if this works for you. I am closing the issue then!
