### ISSUE TITLE
how can only use file store to share connection status without flush message to fs?

### ISSUE THREAD

**Issue by tonyzhu** [nats-io/nats-streaming-server#1125]
1. we open file store to avoid `STREAM: Received invalid client publish message clientID`
2. at same time, message flushed to store dir.
3. there was a unexpected read file io peak today that made nats can not sending message to subs.

so I just want to know, how can I only use file store to avoid invalid client error and avoid message dump and flush into fs.

thanks very much.

**Comment by kozlovic** [comment]
> 1. we open file store to avoid STREAM: Received invalid client publish message clientID

If you use MEMORY store, no state is stored, so if the server is restarted and clients continue to publish, the server will reject because it does not know about this clientID those messages are coming from.
What client library are you using, and what version? Most of our supported client libraries have a Connection Lost handler that would notify your application that the connection is no longer valid and should be recreated - exactly like in the case where a memory based Streaming server is restarted. You can learn more about this [here](https://docs.nats.io/nats-streaming-server/configuring/persistence)

So if you don't care that messages are lost if the server restarts, simply make sure that your apps can recover from a "connection lost" situation (that is, connection is no longer valid and they must be recreated - along with subscriptions if applicable), you may still use the Streaming server with MEMORY store.

If you want persistence of clients/subscription records, but no message, there is no solution for that. Note that it would not make sense because say that the server stores clients/subs and recovers a subscription that is at sequence 1,000 for instance. If no message is recovered, the first message after a restart would be message sequence 1. So the server would not deliver message to recovered subscription until the sequence reaches 1,001.
