### ISSUE TITLE
Memory allocation with filestore on v0.18.0 vs v0.14.3

### ISSUE THREAD

**Issue by ymkins** [nats-io/nats-streaming-server#1126]
We use embedded nats-streaming-server with filestore as intermediate collector.
Application puts metric kind data into channel and then processes it (sends to backends) in durable subscriptions.
https://github.com/gwos/tcg/blob/master/nats/nats.go
There are 2..3 subscription per channel in common with options:
```
stan.StartWithLastReceived(),
stan.SetManualAckMode(),
stan.AckWait(**30s**),
stan.MaxInflight(**math.MaxInt32**),
```
It works pretty well on nats-streaming-server@v0.14.3 and we got an issue after upgrade to nats-streaming-server@v0.18.0.
Case: for some reason the channel was not processed for some time (durable subscription was subscribed then closed) and filestore collected data taken a few GB.
Then on durable subscription restore in case of nats-streaming-server@v0.14.3 the application allocates for about 3GB VIRT 1GB RES until it processed the queue. In case of nats-streaming-server@v0.18.0 the memory allocation grows until OOM.

```
$ go tool pprof -inuse_space -top ./heap.1 
File: checker-connector
Type: inuse_space
Time: Nov 12, 2020 at 4:52pm (EET)
Showing nodes accounting for 329.03MB, 98.99% of 332.37MB total
Dropped 33 nodes (cum <= 1.66MB)
      flat  flat%   sum%        cum   cum%
  215.12MB 64.72% 64.72%   215.12MB 64.72%  github.com/nats-io/go-nats-streaming/pb.(*MsgProto).Unmarshal
   70.86MB 21.32% 86.04%    70.86MB 21.32%  github.com/nats-io/go-nats.(*Conn).processMsg
   16.51MB  4.97% 91.01%    16.51MB  4.97%  golang.org/x/net/webdav.(*memFile).Write
   10.14MB  3.05% 94.06%    10.14MB  3.05%  github.com/nats-io/nats-streaming-server/server.(*StanServer).recoverOneSub
       6MB  1.81% 95.87%   224.44MB 67.53%  github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).lookup
    5.31MB  1.60% 97.47%     5.31MB  1.60%  github.com/nats-io/nats-streaming-server/stores.(*FileSubStore).recoverSubscriptions
    3.32MB     1% 98.46%     3.32MB     1%  github.com/nats-io/nats-streaming-server/stores.(*msgsCache).add
    1.77MB  0.53% 98.99%     1.77MB  0.53%  github.com/nats-io/nats-streaming-server/server.makeSortedSequences
         0     0% 98.99%    11.45MB  3.45%  github.com/gwos/tcg/nats.StartServer
         0     0% 98.99%    11.45MB  3.45%  github.com/gwos/tcg/services.(*AgentService).listenCtrlChan
         0     0% 98.99%    11.45MB  3.45%  github.com/gwos/tcg/services.(*AgentService).startNats
         0     0% 98.99%    70.86MB 21.32%  github.com/nats-io/go-nats.(*Conn).parse
         0     0% 98.99%    70.86MB 21.32%  github.com/nats-io/go-nats.(*Conn).readLoop
         0     0% 98.99%   224.44MB 67.53%  github.com/nats-io/nats-streaming-server/server.(*StanServer).getMsgForRedelivery
         0     0% 98.99%   226.71MB 68.21%  github.com/nats-io/nats-streaming-server/server.(*StanServer).performDurableRedelivery
         0     0% 98.99%    10.14MB  3.05%  github.com/nats-io/nats-streaming-server/server.(*StanServer).processRecoveredChannels
         0     0% 98.99%   226.71MB 68.21%  github.com/nats-io/nats-streaming-server/server.(*StanServer).processSubscriptionsStart
         0     0% 98.99%    10.14MB  3.05%  github.com/nats-io/nats-streaming-server/server.(*StanServer).start
         0     0% 98.99%    11.45MB  3.45%  github.com/nats-io/nats-streaming-server/server.RunServerWithOpts
         0     0% 98.99%   224.44MB 67.53%  github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).Lookup
         0     0% 98.99%     5.31MB  1.60%  github.com/nats-io/nats-streaming-server/stores.(*FileStore).newFileSubStore
         0     0% 98.99%     5.31MB  1.60%  github.com/nats-io/nats-streaming-server/stores.(*FileStore).recoverOneChannel
         0     0% 98.99%     2.10MB  0.63%  github.com/swaggo/gin-swagger/swaggerFiles.init.12
         0     0% 98.99%    10.72MB  3.22%  github.com/swaggo/gin-swagger/swaggerFiles.init.6
         0     0% 98.99%     2.15MB  0.65%  github.com/swaggo/gin-swagger/swaggerFiles.init.8
         0     0% 98.99%    17.01MB  5.12%  runtime.doInit
         0     0% 98.99%    17.01MB  5.12%  runtime.main


$ go tool pprof -inuse_space -top ./heap.2
File: checker-connector
Type: inuse_space
Time: Nov 12, 2020 at 5:16pm (EET)
Showing nodes accounting for 1251.18MB, 97.74% of 1280.07MB total
Dropped 54 nodes (cum <= 6.40MB)
      flat  flat%   sum%        cum   cum%
  813.11MB 63.52% 63.52%   813.11MB 63.52%  github.com/nats-io/nats%2ego.(*Conn).processMsg
  372.94MB 29.13% 92.66%   372.94MB 29.13%  github.com/nats-io/stan.go/pb.(*MsgProto).Unmarshal
   17.19MB  1.34% 94.00%    17.19MB  1.34%  golang.org/x/net/webdav.(*memFile).Write
   16.30MB  1.27% 95.27%    16.30MB  1.27%  github.com/nats-io/nats-streaming-server/stores.(*bufferPool).Get
   12.07MB  0.94% 96.21%    12.07MB  0.94%  github.com/nats-io/stan.go/pb.(*MsgProto).Marshal
    9.56MB  0.75% 96.96%     9.56MB  0.75%  github.com/nats-io/nats-streaming-server/server.(*StanServer).recoverOneSub
       8MB  0.63% 97.59%   402.65MB 31.46%  github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).readAheadMsgs
    2.01MB  0.16% 97.74%   815.12MB 63.68%  github.com/nats-io/nats%2ego.(*Conn).parse
         0     0% 97.74%    10.35MB  0.81%  github.com/gwos/tcg/nats.StartServer
         0     0% 97.74%    10.35MB  0.81%  github.com/gwos/tcg/services.(*AgentService).listenCtrlChan
         0     0% 97.74%    10.35MB  0.81%  github.com/gwos/tcg/services.(*AgentService).startNats
         0     0% 97.74%   815.12MB 63.68%  github.com/nats-io/nats%2ego.(*Conn).readLoop
         0     0% 97.74%   402.65MB 31.46%  github.com/nats-io/nats-streaming-server/server.(*StanServer).getMsgForRedelivery
         0     0% 97.74%   373.65MB 29.19%  github.com/nats-io/nats-streaming-server/server.(*StanServer).performAckExpirationRedelivery
         0     0% 97.74%    51.23MB  4.00%  github.com/nats-io/nats-streaming-server/server.(*StanServer).performDurableRedelivery
         0     0% 97.74%   373.65MB 29.19%  github.com/nats-io/nats-streaming-server/server.(*StanServer).performRedeliveryOnStartup
         0     0% 97.74%     9.56MB  0.75%  github.com/nats-io/nats-streaming-server/server.(*StanServer).processRecoveredChannels
         0     0% 97.74%    51.23MB  4.00%  github.com/nats-io/nats-streaming-server/server.(*StanServer).processSubscriptionsStart
         0     0% 97.74%    15.79MB  1.23%  github.com/nats-io/nats-streaming-server/server.(*StanServer).sendMsgToSub
         0     0% 97.74%     9.56MB  0.75%  github.com/nats-io/nats-streaming-server/server.(*StanServer).start
         0     0% 97.74%   373.65MB 29.19%  github.com/nats-io/nats-streaming-server/server.(*StanServer).start.func1
         0     0% 97.74%    10.35MB  0.81%  github.com/nats-io/nats-streaming-server/server.RunServerWithOpts
         0     0% 97.74%   402.65MB 31.46%  github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).Lookup
         0     0% 97.74%   402.65MB 31.46%  github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).lookup
         0     0% 97.74%    10.72MB  0.84%  github.com/swaggo/gin-swagger/swaggerFiles.init.6
         0     0% 97.74%    18.19MB  1.42%  runtime.doInit
         0     0% 97.74%    17.69MB  1.38%  runtime.main
```
The code difference is https://github.com/gwos/tcg/pull/202/commits/5d21bfe58bcbb
So, it's not clear how to prevent OOM crash.

**Comment by ymkins** [comment]
It's reproduced with  nats-streaming-server@v0.19.0.
Setting  stan.MaxInflight(1) doesn't resolves it.

**Comment by kozlovic** [comment]
> Setting stan.MaxInflight(1) doesn't resolves it.

Really? That was the first thing I was going to say: setting the MaxInflight to math.MaxInt32 is a no-no.. The server would send possibly all messages in the channel without releasing the lock for the consumer. Also if for any reason the consumer does not ack messages, then they are all going to redelivered again, etc..

What are the 2 outputs of pprof above? Is that one for 0.14.3 and one for 0.18.0 or two from 0.18.0?

How big is the datastore? How many messages and how big on average is each message? I am going to try to reproduce that, but I can't see how having MaxInflight(1) does not solve the problem...

**Comment by ymkins** [comment]
heap.1 is for 0.14.3
heap.2 is for 0.18.0
one message is about 4KB
I see the issue on datastore about 500MB
I see the issue with application in docker container as well with native linux application

**Comment by kozlovic** [comment]
Again, with a MaxInflight of MaxInt32, what happens when the subscription starts and has a lot of backlog messages, is that the server is going to send all pending messages for this consumer "at once", that is, without releasing the consumer lock. The application may get them and ack, but the ack won't be processed because the server is still sending messages to this consumer.
Since you have AckWait of 30sec, if it takes longer to send all pending messages, the message will also get redelivered.

I see that in your callback you create a string based on durable name and message sequence number and check if this message has been processed, but in that case you return without Acking. If the server redelivers the message is that it thinks that the message has not been acknowledged, and it may in that case resend again, so you should Ack the message there.
In some cases server could send message 1, 2, 3, 4.. suppose application is slow and message is not ack'ed, so server resends 1, 2, 3, 4. In the client internal queue, there is now message 2, 3, 4, 1, 2, 3, 4 waiting to be dispatched. If application that is currently processing message 1 now ack it, then server will stop redelivering (if it receives the ack), but application will still see message 1 a second time. In that case, it would be OK not ack it, but since you can't know if server got ACK for message 1 the first time it was sent, you should always ACK it again.

I have tried with 10,000,000 messages and 0.14.3 and client 0.4.4 as you originally had. When starting the durable with all this backlog and simulating what your callback is doing (in term of ack), the server keeps redelivering messages.
It is the same with 0.18.0 and 0.7.0 client. I do notice that in the latter, messages are received much faster, which may contribute to the issue.

You could run the server with monitoring port enabled and check the channel and its subs (https://docs.nats.io/nats-streaming-concepts/monitoring/endpoints#channelsz). You may then see if messages are pending or not.

So I would recommend that you set MaxInflight to something reasonable (default is 1024) and also Ack message when you find it in your cache and let me know if that improves things.

**Comment by ymkins** [comment]
Thanks for detailed explanation! 
There are a pendings on subscription.
And for 0.14.3 with 0.4.0 client the subscription PendingLimits are 65536, 67108864.
And for 0.18.0 with 0.7.0 client the subscription PendingLimits are -1, -1.
And Pending() shows that number of queued messages grows in time.
So, it looks like we have to set the PendingLimits.
A few questions:
* Does MaxInflight affects the PendingLimits? For now I don't see it.
* How the subscription PendingLimits should be configured? Are there some options for the nats-streaming server or connection? Should we use SetPendingLimits inside subscription handler?

**Comment by ymkins** [comment]
Well, according to https://docs.nats.io/developing-with-nats/events/slow
we have to set PendingLimits on the subscription ref.

**Comment by ymkins** [comment]
I confirm that setting the PendingLimits resolves the issue.
@kozlovic, Thanks a lot for you support!

**Comment by kozlovic** [comment]
@ymkins But that is the wrong approach. I will send a more detailed response later. Also, happy to jump on a Google meet if that helps.

**Comment by kozlovic** [comment]
A NATS Streaming client uses low level NATS subscription to receive messages from the server. This low level subscription is subject to pending limits indeed, but as you can see, in more recent streaming libraries, we have set the limits to "unlimited". 

The reason is: suppose that server has 20 messages to deliver to a streaming subscription, and for illustration suppose that the low level subscription limit is 10 messages. The streaming subscription is created with a very high MaxInflight. When processing the subscription request, the server starts to send all available messages. In that case, it sends 20 messages as fast as it can. Suppose that the client library receives messages 1 to 10 from the connection then passes that to the internal NATS subscription's queue in order to be dispatched. The NATS subscription message callback is then transforming the raw bytes into a protobuf, then it invokes the user's streaming message callback. Each message is dispatched serially. For illustration purposes, suppose that this takes a bit of time. The user is currently processing message 1. 
The server continues to send and message 11, 12, 13 arrive in the client library and are processed by the connection. Message 11 is added to the subscription's internal queue (since 1 was removed, there was room). But then 12 and 13 don't fit, so they are dropped by the NATS library. Now suppose that there is no delay and all pending messages are dispatched and messages 14 to 20 have arrived and have been dispatched. The user will have seen messages 1..11, then 14..20. Messages 12 and 13 have not been seen, and therefore not acknowledged, so they are going to be redelivered after the AckWait.
This is not a desired behavior.

By setting the MaxInflight to say 5 with above example, the streaming server would never have sent more than 5 messages, so no message would be dropped and messages would arrive without gaps (assuming direct connection and no TCP reconnect anywhere in-between the streaming server and client).

This is why the streaming client library sets the PendingLimits to -1,-1 and you should NOT override that and set the pending limits to the internal subscription created by the streaming library. Instead you should set a MaxInflight that is reasonable, not math.MaxInt32.
As discussed earlier, the server will not send more than MaxInflight messages, so your application will not run out of memory. I argue that if you set it to 1 and still saw the issue, there is something else going on or the configuration was actually not being used. The monitoring endpoint would show you what the server has used for the MaxInflight.

The MaxInflight is the correct approach. It also solves the issue of "locking up" the server if there are hundred of thousands of messages available to send to a subscription. This can lead to unnecessary redeliveries because the message acknowledgement cannot be processed when the server delivers the initial batch under the consumer lock. This has uncovered a defect that I will address.

I would strongly recommend that you set a lower MaxInflight and always Ack a message that has been redelivered (even if your code detects it as a duplicate and does not process it, it should still Ack it before the callback returns).

**Comment by ymkins** [comment]
Will work it out.
Found that we also have MaxPayload=math.MaxInt32

**Comment by kozlovic** [comment]
> Will work it out.

I urge you to have a look at what I described above. I would strongly recommend ensuring that you use a reasonable MaxInflight instead of changing pending limits on low level subscriptions. 

> Found that we also have MaxPayload=math.MaxInt32

Yeah, that too is not going to help :-)

**Comment by ymkins** [comment]
well, finally with 'http://localhost:8222/streaming/channelsz?channel=metrics&subs=1'
I can see that after setting MaxInflight=1 (actually, setting some smaller value then before)
the pending_count goes down in time for existed subscription... it's why I missed as I expected changes immediately
