### ISSUE TITLE
Deleting old messages

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nats-io/nats-streaming-server#1133]
I have a single nats-streaming-server instance running with file-store option in docker.  I have set it to run with `mm(maximum messages)=10000` and `ma(max age)=24h` but it seems messages are not removed and the storage space keep increasing. Isn't it the right way to configure deletion of old messages ? Any help appreciated

**Comment by kozlovic** [comment]
Few things: the limit is per channel, so if you have multiple channels, then the file store will grow larger. But also you need to understand that the file store uses file slices to store messages/indexes. If you don't set those limits, the server picks some limits and what is likely happening is that the file grows until the file slice limit is reached before a new one is created and the old one deleted. Note that the limit is honored in term of what messages can be sent to consumers, etc.. the the (file) store implementation specifics may retain more messages than this limit. See doc https://docs.nats.io/nats-streaming-server/configuring/persistence/file_store#options for more details.

So for instance, if you were to use say `-file_slice_max_msgs 2500` then the server would fill up 4 slices, each of 2500 and then on the 5th, once that one is filled, it would delete the first slice. So there would be an additional of 2500 possibly on disk (in this explanation, I do not take into account the size of the messages and assume that the 2500 messages fit into a slice default size of 64MB).

A word of caution: don't make those file slices too small because that will affect performance since the server will have to close/create/delete files too often depending on the message rate.

**Comment by kozlovic** [comment]
Closing this issue for now. We will reopen if my previous answer did not address your question.
