### ISSUE TITLE
 Subscription Violation

### ISSUE THREAD

**Issue by CrazyPandas** [nats-io/nats-streaming-server#1144]
```
authorization {
        ADMIN = {
                publish = ">"
                subscribe = ">"
        }
        ITEM = {
                publish = ["item.change"]
                subscribe = ["_INBOX.>"]
        }
        users = [
                {user: item, password: "112233", permissions:$ITEM},
                {user: admin, password: "445566", permissions:$ADMIN}
        ]
}

streaming: {
        cluster_id: "nats_streaming"
        username: admin
        password: "445566"
        sv: true
        store: "file"
        store_limits: {
                max_age: "24h"
                max_inactivity: "24h"
        }
        dir: "data"
}
```

and code:

```ts
import {connect as natsStreamingConnect} from 'node-nats-streaming'
...
const log = getLogger('default')

function main() {
    let client = natsStreamingConnect('nats_streaming', 'clientID1', {
        url: 'nats://127.0.0.1:4222',
        user: 'item',
        pass: '112233'
    })
    client.on('connect', () => {
        let count = 0
        let handle = setInterval(()=>{
            if (count > 3) {
                clearInterval(handle)
                log.debug(`>>> clearInterval`)
                client.close()
                return
            }
            client.publish('item.change', 'worker worker worker!',(err, guid) => {
                if (err) {
                    log.error(`<<< ${err} with ${guid}`)
                } else {
                    log.info(`<<< publish success with guid: ${guid}`)
                }
            })
            count += 1
        }, 1000)
    })
    client.on('error', (err) => {
        log.error(`<<< ${err}`)
    })
}

main()
```

it will got error :

```
[9093] 2021/01/11 15:31:00.207989 [ERR] 127.0.0.1:57444 - cid:4 - Subscription Violation - User "item", Subject "_STAN.acks.489N92HEIMCCALEPTZTNAS", SID 3
[9093] 2021/01/11 15:31:00.208048 [ERR] 127.0.0.1:57444 - cid:4 - Publish Violation - User "item", Subject "_STAN.discover.nats_streaming"
```

1. why the error report Subject  is "_STAN.discover.nats_streaming" when I publish a message with subject "item.change" ?
2. how to fix it ?

- "node-nats-streaming": "^0.3.2",
- nats-streaming-server[nats_streaming] version 0.19.0
- Go version: go1.15.2
- nats-server version 2.1.9

thanks.

**Comment by kozlovic** [comment]
> I found this config is work for me, but publish limit "_STAN.pub.nats_streaming.item.change" is so long, why cant's simple set "item.change"?

This is because internally this is the subject use by the client to send messages to the streaming "server". The server is not a server per-se, it is a process using the NATS library to communicate with its clients. These links may help you understand this better:
https://docs.nats.io/nats-streaming-concepts/intro
https://docs.nats.io/nats-streaming-concepts/relation-to-nats

Note that the subscribe permission on "item.>" is of no use because the streaming client library is actually receiving messages on an inbox (prefix `_INBOX.`). There is currently no way to restrict a streaming client to subscribe on specific subscriptions. This is because the subscriptions requests are send to `_STAN.sub.<cluster id>` and the channel is part of the request payload, not the subject. So users cannot use NATS permissions to restrict those requests.

Maybe we need to add streaming level basic permissions handling for publish/subscribe at the level of NATS Streaming "server" to ease the configuration (in that case, users may not need the `_STAN.pub.` prefix, etc..

**Comment by CrazyPandas** [comment]
@kozlovic thanks.
