### ISSUE TITLE
Not pushing most update message but found no pending

### ISSUE THREAD

**Issue by dkishere** [nats-io/nats-streaming-server#1145]
"name": "updatedata-xml",
      "msgs": 677386,
      "bytes": 286736403,
      "first_seq": 46210185,
      "last_seq": 46887570,
      "subscriptions": [
        {
          "client_id": "test-client-dk-master",
          "inbox": "_INBOX.HZwexDhDdOngSrLIVCnfvQ",
          "ack_inbox": "_INBOX.b0jFZPBIQiTKlggHCtVByJ",
          "durable_name": "mapping-dk-master",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 600,
          "last_sent": 46887207,
          "pending_count": 1,
          "is_stalled": true
        },

I am petty sure the consumer side was not at its cap, and it should be pending if it was.
nats-streaming-server version 0.19.0, nats-server: v2.1.9

{
   max_payload:838860800,
   store_limits: {
      max_channels: 50,
      max_msgs: 0,
      max_bytes: 0,
      max_age: "2h"
   }
}

**Comment by kozlovic** [comment]
From the monitoring endpoint it looks like you have a durable subscription called: "mapping-dk-master" that appears to be running since we have `"is_offline": false`. This consumer is configured with a max inflight of 1: `"max_inflight": 1` which means that the server will not send more than 1 message at a time, wait for the ack from the app before sending the next message.
As we can see, it did so: `"pending_count": 1,`  and the consumer is now marked as stalled: `"is_stalled": true`. The server will wait to receive an ACK before sending more. Your consumer's ack wait is set to 10 minutes: `"ack_wait": 600,` so the server will not redeliver the message for 10 minutes.
Your application has fell behind since the server sent the message sequence 46887207 `"last_sent": 46887207,` while the last sequence in the channel is 46887570 `"last_seq": 46887570,`.

**Comment by dkishere** [comment]
> 
> 
> From the monitoring endpoint it looks like you have a durable subscription called: "mapping-dk-master" that appears to be running since we have `"is_offline": false`. This consumer is configured with a max inflight of 1: `"max_inflight": 1` which means that the server will not send more than 1 message at a time, wait for the ack from the app before sending the next message.
> As we can see, it did so: `"pending_count": 1,` and the consumer is now marked as stalled: `"is_stalled": true`. The server will wait to receive an ACK before sending more. Your consumer's ack wait is set to 10 minutes: `"ack_wait": 600,` so the server will not redeliver the message for 10 minutes.
> Your application has fell behind since the server sent the message sequence 46887207 `"last_sent": 46887207,` while the last sequence in the channel is 46887570 `"last_seq": 46887570,`.

Thank you for your quick reply, a bit confuse if pending_count means the number of messages waiting to dispatch to app? as it obviously not just 1...

**Comment by kozlovic** [comment]
> Thank you for your quick reply, a bit confuse if pending_count means the number of messages waiting to dispatch to app? as it obviously not just 1...

It is the number of messages that server send to the application, for which no ack has been received yet. In case of a non queue subscription, it can't be more than the subscription's MaxInflight. 
So there are many more messages waiting to be sent by the server to this client, but because of max inflight, there will be only 1 pending at a time.

**Comment by dkishere** [comment]
> 
> 
> > Thank you for your quick reply, a bit confuse if pending_count means the number of messages waiting to dispatch to app? as it obviously not just 1...
> 
> It is the number of messages that server send to the application, for which no ack has been received yet. In case of a non queue subscription, it can't be more than the subscription's MaxInflight.
> So there are many more messages waiting to be sent by the server to this client, but because of max inflight, there will be only 1 pending at a time.

Then I've misunderstood it for a few years... Thank you for clarify.
But how do I know how many messages are waiting in the server queue then?

**Comment by kozlovic** [comment]
> But how do I know how many messages are waiting in the server queue then?

That would be the subscription's `last_sent` minus channel's `last_seq`. Note that due to limit, it is possible that at some point the `last_sent` of a consumer be smaller than the `first_seq` in the channel. The consumer's `last_sent` value will be then the `first_seq` when it is time for the server to send the next available message, but you get the idea.

**Comment by dkishere** [comment]
So it's only by monitor api no direct methods right?
Thank you!

**Comment by kozlovic** [comment]
> So it's only by monitor api no direct methods right?

Yes.

**Comment by dkishere** [comment]
Thank you so much!
