### ISSUE TITLE
Nats proxying

### ISSUE THREAD

**Issue by saranhada** [nats-io/nats-streaming-server#1148]
Hello Nats Community,

what solution would you recommend in front of the nats cluster?

We are currently using Nginx but noticed some times it just starts failing until restarted.
Sample of Nginx conf:

```hcl
stream {

    server {
        listen some.host.ip:443 ;
        proxy_pass backendnats;
    }

    upstream backendnats {
        server  10.0.0.3:4222;
  }
}
```

**Comment by kozlovic** [comment]
@saranhada That may not be the best forum to reach the maximum people. Are you on Slack? If not, I would recommend you to join for these kind of questions when you want to ask the community. To join: https://join.slack.com/t/natsio/shared_invite/zt-41e6tnmb-qCt63606MKR1YxIHZf4ICA

The common answer is that NATS in general does not like to have something in between client and server(s). NATS already does load balancing and clients can provide a list of URLs to randomly pick a server to connect to. Servers will also gossip the cluster addresses to the clients so that the list can be augmented for when they need to reconnect.

**Comment by kozlovic** [comment]
I see that you have posted this on our Slack channel. Closing this now. Thanks!
