### ISSUE TITLE
How to connect to the browser?

### ISSUE THREAD

**Issue by sensone** [nats-io/nats-streaming-server#1149]
Hi, Could you help me?

I try to connect Browser with nats-streaming-server and don't understand How I can do it. 

I use [nats.ws](https://github.com/nats-io/nats.ws). In examples from this library, this library connected to the [nats-server](https://github.com/nats-io/nats-server), and this server has an option for WebSocket support. I didn't find WebSockets options for the nats-streaming-server.

Should I develop my own proxy-server using [stan.js](https://github.com/nats-io/stan.js) or develop proxy-server use resgate.io?

Could you explain to me the best way for it?
Thanks.

**Comment by kozlovic** [comment]
Websocket support is in NATS Server but only in the main branch (as not been published yet). That being said, NATS Streaming server is actually a client (that may embed NATS Server). In the embedded mode, you won't be able to use Websocket because the NATS Server version embedded in NATS Streaming does not have the feature.
If you use the NATS Server from the main branch, and have websocket port enabled, then you can connect your clients to the websocket port. However, the NATS Streaming server does not have websocket support, so it would still need to connect to the regular NATS Server's client ports. As long as the NATS Streaming server and your clients share the same account, they will still be able to talk to each other even if the Streaming server is connected to client port and your browser to the websocket port.

**Comment by sensone** [comment]
Hi, @kozlovic 
Thanks a lot for your explanation. Maybe you know, When WebSockets will publish?

**Comment by aricart** [comment]
@sensone some time in February. - this will coincide with the release for JetStream which will have nats.ws support.
