### ISSUE TITLE
Can you access guid in received message ?

### ISSUE THREAD

**Issue by Sikarnas** [nats-io/nats-streaming-server#1151]
I'm trying to properly map two of my ES indexes, but I don't see a way to access a unique identifier for a received message. I see that the published message returns a guid, but can it be accessed by the listener?

**Comment by kozlovic** [comment]
No you can't, and also note that the synchronous call does not even return the guid, just a possible error. The guid was added just for client-to-server protocol. So it is part of the message protobuf that is sent to the server but then another type of message (MsgProto) is persisted and sent to the consumers. So the Guid is used just by the server to send a PubAck back to the publisher and is otherwise dropped/not persisted.

If you want to identify a published message, I would recommend that you add your own ID in the message. We have a library that produces uid if you would like: https://github.com/nats-io/nuid
