### ISSUE TITLE
Reducing number of nodes in nats cluster

### ISSUE THREAD

**Issue by sergeiepam** [nats-io/nats-streaming-server#1166]
Dear Nats Community,

We have 7 nodes in Nats cluster. Everything is allright, no issues at all. But we do see that the nodes are not loaded at all and we can serve the current number of customers with 3 nodes.
Is it possible anyhow to decrease the number of Nats nodes by 4? If we simply shutdown the four nodes, then the cluster will end up with the lack of quorum.

**Comment by kozlovic** [comment]
Starting v0.19.0, there is an option that can be enabled in the server to allow the removal of nodes in the cluster: https://docs.nats.io/nats-streaming-server/configuring/cfgfile#cluster-configuration

With that option enabled, you would then be able to send a NATS message to `_STAN.raft.<cluster ID>.node.remove` with the payload being the node ID you want to remove.
Obviously, you would want also to change the configuration of remaining servers so that after a restart they don't try to add those again to the group.

(note, the latest is v0.21.0, but I just found a bug, so if you are pre v0.19.0 and want to upgrade to benefit from the add/remove feature, do not upgrade to v0.21.0 or wait a day or two before I issue a fix).

**Comment by sergeiepam** [comment]
@kozlovic thank you so much! We will try to do it.

**Comment by sskserk** [comment]
In 5 nodes cluster we successfully removed 2 nodes according to the sequence:
1) Shutdown node
2) Publish message into topic with the "Server id" of the removed node. 

In the logs of the leader node we see the message: **STREAM: Removed node "j8D8n1MDwiqFniNHZ8jzcj"**

But then the problem appears:
- if we shutdown node 3 then the cluster loses quorum. All nodes turn into candidates. If we try to send the removal message, then there is no **STREAM: Removed node ...** confirmation message in the logs. And the clients cannot establish connections.
-  If we send the Removal message prior the node shutdown actions, then because the node is still active, it rejoines the cluster, and the removal action seems doesn't make any sense.

How the node removal action should be performed correctly?

**Comment by kozlovic** [comment]
Could you send me your original configuration for the 5 node clusters? Were you using bootstrap and non named peers? (based on the node ID, I guess that you did not name them). Thanks!

**Comment by kozlovic** [comment]
I just tried and it works fine for me with a cluster of 5 either with bootstrap or naming the peers. Please describe the configuration and the exact steps you followed.
Here is an example with named peers. This is the config of node "a" out of "a", "b", "c", "d" and "e"
```
port: 4222
cluster {
  port: 6222
  routes [
    "nats://localhost:6222"
    "nats://localhost:6223"
    "nats://localhost:6224"
    "nats://localhost:6225"
    "nats://localhost:6226"
  ]
}

streaming {
  store: file
  dir: "ds1"
  cluster {
    node_id: "a"
    peers: ["a", "b", "c", "d", "e"]
    log_path: "test-cluster/a"
    raft_logging: true
    allow_add_remove_node: true
  }
}
```
For second node, it would be:
```
port: 4223
cluster {
  port: 6223
  routes [
    "nats://localhost:6222"
    "nats://localhost:6223"
    "nats://localhost:6224"
   "nats://localhost:6225"
   "nats://localhost:6226"
  ]
}

streaming {
  store: file
  dir: "ds2"
  cluster {
    node_id: "b"
    peers: ["a", "b", "c", "d", "e"]
    log_path: "test-cluster/b"
    raft_logging: true
    allow_add_remove_node: true
  }
}
```
etc.. Note that ports are +1 (since I run on same machine) and `dir` is "ds2", `node_id` is "b", and `log_path` is "test-cluster/b". Same idea for the other config files.

For a cluster of 5 nodes, you have quorum at 3 nodes, so after starting a, b and c already there could be a leader. You will notice the RAFT logging if you did not start yet "d" and "e" that the leader is trying to replicate to them. When all 5 are running, the tracing from RAFT should stop.

Then I publish 3 messages on channel "foo" and can then start a consumer to consume them, all works ok.

I then send a message like this:
```
$ go run examples/nats-pub/main.go "_STAN.raft.test-cluster.node.remove" e
Published [_STAN.raft.test-cluster.node.remove] : 'e'
```
The leader then will report this:
```
[5194] 2021/03/02 16:33:31.461583 [INF] STREAM: raft: updating configuration: command=RemoveServer server-id=e server-addr= servers="[{Suffrage:Voter ID:a Address:test-cluster.a.test-cluster} {Suffrage:Voter ID:b Address:test-cluster.b.test-cluster} {Suffrage:Voter ID:c Address:test-cluster.c.test-cluster} {Suffrage:Voter ID:d Address:test-cluster.d.test-cluster}]"
[5194] 2021/03/02 16:33:31.461713 [INF] STREAM: raft: removed peer, stopping replication: peer=e last-index=16
[5194] 2021/03/02 16:33:31.461805 [INF] STREAM: raft: aborting pipeline replication: peer="{Voter e test-cluster.e.test-cluster}"
[5194] 2021/03/02 16:33:31.462438 [INF] STREAM: Removed node "e"
```
after a few seconds, we see node "e" that tries to vote but it is now rejected:
```
[5194] 2021/03/02 16:33:33.818106 [WRN] STREAM: raft: rejecting vote request since we have a leader: from=test-cluster.e.test-cluster leader=test-cluster.a.test-cluster
```
So I can stop "e" after sending the remove command, but I could have stopped it before. Then I do the same for "d".
I now have "a", "b" and "c" running. If I stop "c", there is still quorum, so I can send messages or start a consumer.

Note that since I have explicitly defined the routes to a, b, c, d and e, as soon as "e" and "d" are stopped, the other servers complain about not being able to create the route. I can modify "a", "b" and "c" config files to remove the routes to "d" and "e" and then issue a configuration reload: `nats-streaming-server -sl reload=<pid>` to make them stop trying to create a NATS route to these servers.

**Comment by kozlovic** [comment]
Also, you should modify the list of "peers" in the servers config so that if servers get restarted, the config on file matches the config in the RAFT logs.

**Comment by sskserk** [comment]
Our case is a little bit different. We have configured dynamic cluster without node_id-s and peers[].
Dynamically it was expanded to 7 nodes. I have compiled a synthetic set of configuration files which reproduces the problem, we use this set trying to understand how it is possible to reduce the cluster size to 3 node. 

The attached artifact contains 5 nodes cluster. We can safely shutdown 2 nodes and remove them. But not 3.

[nats.tar.gz](https://github.com/nats-io/nats-streaming-server/files/6077490/nats.tar.gz)

**Comment by kozlovic** [comment]
I have used your config files and I am able to remove all the nodes I want. So could we do a Google Meet or something so that you can show me? Or then provide the steps and server outputs so I can see what is going on?

Note that because of your use of bootstrap, you could potentially go down to single server and it will still elect itself (this is why I don't like this option and usually recommend against using it).

**Comment by sskserk** [comment]
This time it worked. We could exclude 3 nodes from the 5 nodes cluster. And there is still a leader. Cluster works.

The problem was in incorrect Node ID which published into the subject. This time we used identifier taken from the node startup logs (please see the attachment).

![nats_log](https://user-images.githubusercontent.com/78915702/109868220-acf2c880-7c67-11eb-9e35-aa0429af6b9b.png)

Is it possible to obtain the node ids anyhow?

**Comment by kozlovic** [comment]
You have it printed in the startup banner. Look for "STREAM: Cluster Node ID:". In the pic you have attached, you will see that the ID is same than the one you circled in the RAFT logging.

(again, with bootstrap, you can have a single server being leader, but for RAFT to behave properly, you should have a cluster with an odd number, so bringing the size from 5 to 2 is not good, you should have at least 3 servers. With 3 servers, there will be tolerance for losing one).

**Comment by sskserk** [comment]
Yes, agree that the cluster with 2 nodes should not be used in production. I just wanted to mention that we could exclude nodes from the cluster without loosing the quorum between the remained. The number of servers for sure should be odd.

I see the node ids in the startup banner. It is OK. But if the cluster was launched long time ago, and there are no logs that have it. Is it possible to identity the node ids still?

**Comment by kozlovic** [comment]
> But what if the cluster was launched long time ago, and there are no logs that have it. Is it possible to identity the node ids still?

I see. I don't think it is currently available. Are you guys using monitoring endpoints in prod? I could maybe add that as part of the `streaming/serverz` endpoint.

**Comment by sskserk** [comment]
Yes this is the 1st endpoint which comes into mind. Even without monitoring we could manually query this endpoint and thus obtain the required node id. 
And yes, of course we monitor the endpoints and display this information on the dashboards.

If it possible to provide mentioned by you improvement, then we would wait for this upgrade.

Thank you!
