### ISSUE TITLE
nats-streaming-server does not work against github.com/nats-io/nats-server/v2 v2.2.1

### ISSUE THREAD

**Issue by dirkm** [nats-io/nats-streaming-server#1180]
the streaming server does not start up when run against [github.com/nats-io/nats-server/v2](github.com/nats-io/nats-server/v2) `v2.2.1`.
Against `2.1.9`, everything is fine.

The error-message is `error detecting another server instance: nats: no responders available for request`.

I am unable to debug any further, but I have created a demo program to illustrate the problem here: [https://github.com/dirkm/embeddednats](https://github.com/dirkm/embeddednats)

Not sure if this is worth a bug report or an enhancement request in the go world.

**Comment by vennekilde** [comment]
Running into the exact same issue here

**Comment by kozlovic** [comment]
@dirkm @vennekilde This is likely because your project does not respect the NATS Streaming server dependency, which states that it needs nats.go v1.10.0: https://github.com/nats-io/nats-streaming-server/blob/379bb2deeb173280458e0faac792a586351a98c6/go.mod#L13

Since you use a newer server (2.2.1) and likely main of nats.go, the error that is returned when there is no responder is different than when it is a timeout. The code in streaming server was done prior to introduction of the "no responder" error code, which is why it fails.
Once nats.go v1.11.0 is released (which should be any day now), I will update stan.go (which suffers from the same issue of checking for ErrTimeout and not "no responder") and the streaming server.

But again, if you were to use nats.go v1.10.0, it would work fine. To convince yourself, you could run the nats-streaming-server executable and point to an outside nats-server v2.2.1 (with `-ns nats://<host>:<port>`) and it would work fine, and this is because the streaming executable has been compiled with nats.go v1.10.0.

**Comment by dirkm** [comment]
I am afraid the nats version in my program is out of my control, so I will just wait for your update. thank you for the feedback.

**Comment by ehrktia** [comment]
@kozlovic thanks fixing version for nats-server and others resolved the problem.

**Comment by dirkm** [comment]
I have written a temporary patch for this: https://github.com/dirkm/nats-streaming-server (but it is probably not production quality, so I will not add a merge request).

**Comment by kozlovic** [comment]
I have updated dependencies and server code to work with nats.go v1.11.0. The server has been released: https://github.com/nats-io/nats-streaming-server/releases/tag/v0.22.0. Closing this issue now.
