### ISSUE TITLE
the nats cluster to crash,one of the client.dat in the cluster is corrupted.

### ISSUE THREAD

**Issue by guojianyu** [nats-io/nats-streaming-server#1199]
Because /data/stan of disk is full,   nats leaf nodes  or cloud nats  clinet.dat file  is corrupted, all clients did not send messages. 
we stop all nats servers and  delete all nats server client.dat files for solved this problem.
Is there a more elegant solution?

**Comment by kozlovic** [comment]
Which version are you running? And are you running NATS Streaming Server in cluster mode or standalone? In cluster mode, nothing gets written to this file. The normal stored is wrapped with a RaftStore implementation and AddClient/DeleteClient is a no-op since the information is stored in the RAFT log: https://github.com/nats-io/nats-streaming-server/blob/528588f6b57c68eb4a5e84d92fdd9b1e626ad813/stores/raftstore.go#L104

If you are not using clustering mode, then if a file is corrupted, there is not much the server can do. If the end of the file is "missing", that would cause an "unexpected EOF", which server would try to fix when restarted with a special flag. I recommend that you read https://docs.nats.io/nats-streaming-server/configuring/persistence/file_store#recovery-errors. But again, if you are running in clustered mode, then clients.dat should not be used (may be created on startup, but that's it), so it may indicate that you are not configured the way you think the system is.

**Comment by guojianyu** [comment]
Thanks for your response。
My nats servers are  running in  cluster  mode. but the client.dat file has data to write. 

![image](https://user-images.githubusercontent.com/21234963/123195141-3b6eac80-d4da-11eb-91a4-acd0624088f0.png)

this is my nats configurations in k8s.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: nats
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    cluster {
      port: 6222
      routes [
        nats://nats-0.nats-mgmt.nats.svc.cluster.local:6222
        nats://nats-1.nats-mgmt.nats.svc.cluster.local:6222
        nats://nats-2.nats-mgmt.nats.svc.cluster.local:6222
      ]
      tls: {
        ca_file: /etc/nats-routes-tls-certs/ca.crt
        cert_file: /etc/nats-routes-tls-certs/tls.crt
        key_file: /etc/nats-routes-tls-certs/tls.key
      }
      connect_retries: 10
    }
    tls: {
    verify:   true
    ca_file: /etc/nats-server-tls-certs/ca.crt
    cert_file: /etc/nats-server-tls-certs/tls.crt
    key_file: /etc/nats-server-tls-certs/tls.key
    }
    leafnodes {
      port: 7422
      tls: {
        verify:   true
        ca_file: /etc/nats-server-tls-certs/ca.crt
        cert_file: /etc/nats-server-tls-certs/tls.crt
        key_file: /etc/nats-server-tls-certs/tls.key
      },
    }
--- 
this is my nats-streaming configuration files  in k8s:
data:
  stan.conf: |
    http: 8222

    streaming {
      id: test-cluster
      store: file
      dir: /data/stan/store
      ft_group_name: "cloud-cluster"
      file_options {
          buffer_size: 32mb
          sync_on_flush: false
          slice_max_bytes: 512mb
          parallel_recovery: 64
      }
      nats_server_url: "nats://nats.nats.svc:4222"
      partitioning: true
      store_limits {
          channels: {
           cloud.>: {}
          }
          max_channels: 0
          max_msgs: 0
          max_bytes: 256gb
          max_age: 168h
          max_subs: 0
      }
      tls: {
      verify:   true
      client_cert: "/etc/nats-client-tls-certs/tls.crt"
      client_key: "/etc/nats-client-tls-certs/tls.key"
      client_ca: "/etc/nats-client-tls-certs/ca.crt"
     
     }  
    }
---

**Comment by kozlovic** [comment]
You are not running the Streaming server in cluster mode, you are running it in Fault Tolerant mode (https://docs.nats.io/nats-streaming-concepts/ft). In this mode, the data store is supposed to be shared (read/write accessible) for all nodes in the same FT group (`ft_group_name`). Make sure that when you mount the storage, you have ReadWriteMany persistence option.

So my comment about recovery errors applies since you are not running in cluster (RAFT) mode. Please check https://docs.nats.io/nats-streaming-server/configuring/persistence/file_store#recovery-errors

**Comment by guojianyu** [comment]
Thanks for your answer.
best regards.
