### ISSUE TITLE
Error looking up message  (end of file padded with zeros)

### ISSUE THREAD

**Issue by hanxinimm** [nats-io/nats-streaming-server#1200]
subject:  Labor-Work
error: Error looking up message   Labor-Work:1927   (end of file padded with zeros)
how can  fix it? what's happen

**Comment by kozlovic** [comment]
This happens if the end of a record is not what it should be and the record is filled with zeros (instead of file being simply too short). Please refer to https://docs.nats.io/nats-streaming-server/configuring/persistence/file_store#recovery-errors for instructions on how to recover from those errors.
