### ISSUE TITLE
When added cluster nodes to existing cluster: not syncing store and new node flapping role Follower/Candidate 

### ISSUE THREAD

**Issue by honzakadlec** [nats-io/nats-streaming-server#1209]
Hi, NATS cluster is running quite some time, we need to migrate it to new nodes. The idea was to join these nodes to existing cluster and than power off the old nodes.

nats-streaming-server version 0.18.0, nats-server: v2.1.7
clustered, file storage

What has been done: 
1. I've added the new node IDs to cluster {  peers:[] }
2. Reloaded config of the leader node (by nats-streaming-server --signal reload=$NATSPID)
3. on new nodes I can see raft log (<clustername>/nodename/<clustername>/raft.log) is created, clients.dat, server.dat created, 
but no data are transfered to new nodes: STREAM: Recovering the state...
STREAM: No recovered state
4. in streaming/serverz I can see "role": "Candidate", than "role": "Follower", and back and forth, every 5 - 10 seconds

Is my migration plan feasible please? Is so, what I'm missing please?

Thank you in advance

**Comment by kozlovic** [comment]
@honzakadlec Unfortunately, configuration reload does not apply to NATS Streaming configuration, only embedded NATS configuration. As you can see from v0.18.0 release notes, the handling of config reload signal was added but just for embedded NATS: https://github.com/nats-io/nats-streaming-server/releases/tag/v0.18.0
```
Reload signal now accepted for embedded NATS Server. 
```

So this explains why that did not work at all. However, since v0.19.0, we added a way to configure the server to be able to add/remove RAFT nodes. This is not well documented, so you would need to look at the description of this PR: https://github.com/nats-io/nats-streaming-server/pull/1090.

However, I would recommend that you update to the latest, not to only v0.19.0.

I will leave this ticket opened so you have a chance to look at all this and maybe run some experiment in dev setup and let me know if you have further questions/issues.

**Comment by honzakadlec** [comment]
Hi @kozlovic thank you for prompt and accurate response. 

Is the latest version v0.22.1 (is it JetStream?) backward compatible with v0.18.0 please?

**Comment by kozlovic** [comment]
> Is the latest version v0.22.1 (is it JetStream?) backward compatible with v0.18.0 please?

The version v0.22.1 does embed NATS Server v2.3.3, that technically has JetStream feature, but NATS Streaming is different from JetStream. And yes, NATS Streaming v0.22.1 is backward compatible with v0.18.0.
