### ISSUE TITLE
Configuration for cluster-members to be follower-only

### ISSUE THREAD

**Issue by PBug90** [nats-io/nats-streaming-server#1210]
In an attempt to transition to different AWS-Accounts, we would like to have 2 more nodes to join our existing cluster. We do want to prevent that the new nodes are eligible to become leader if the leader steps down though.
I took a look at the configuration but I could not find an option to set a node to "follower only"-mode in nats streaming configuration. 
Does that feature exist or is there a workaround?

**Comment by kozlovic** [comment]
No, there is no option to make a node a "follower-only". Being able to add nodes to an existing cluster is available only since v0.19.0 and a configuration option has to be enabled (https://github.com/nats-io/nats-streaming-server/pull/1090). But there is no guarantee that the newly added node would not become leader (after it has catch up with the current leader, of course). Note that adding a node (or removing one) can cause a leader re-election.
