### ISSUE TITLE
Define a Migration path from STAN to JetStream

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-streaming-server#1230]
We'll need a migration path from STAN to JetStream. We may have different paths or tooling based on whether downtime is allowed in a migration.  This could be a reference document, tooling, a bridge, or combination of the three.

**Comment by na-le** [comment]
@ColinSullivan1 how did you manage it? d you have  tool to migrate from STAN to JetStream?

**Comment by DrManojD** [comment]
> We'll need a migration path from STAN to JetStream. We may have different paths or tooling based on whether downtime is allowed in a migration. This could be a reference document, tooling, a bridge, or combination of the three.

I am also looking for a smooth migration tool to JetStream.

**Comment by bruth** [comment]
@ColinSullivan1 I am happy to drive this forward. I think the two most immediate outputs we can produce include:

- Document the relationship between the concepts in STAN and JetStream
  - Including examples of "given this example in STAN, this is how it looks in JetStream"
- A program that can migrate/copy/translate stream messages from STAN to JetStream

A few open questions include:

- Migration of subscriptions. Its unclear if this would work in practice since sequence numbers may change when a stream is converted
- Downtime concerns. A bridge option such as a program that subscribes to STAN streams and republishes to a JetStream may help with reducing downtime. Of course this requires application code (publishers and subscribers) to be updated themselves as well.

But if folks using STAN in production have specific concerns or questions please leave a comment! Or if you want to vote for the most pressing need to help facilitate this migration.

**Comment by erwanriou** [comment]
Hey i have a question regarding the deprecation of `nats streaming`. I have indeed an `nats streaming` server within a `kubernetes` cluster with other services together (mainly `nodejs` express servers), but when i look to the documentation regarding the `NATS JetStream Enabled Clients` that i should use with `nodejs` then it redirect me to this one:

https://github.com/nats-io/stan.js

![Screenshot from 2022-09-27 22-05-50](https://user-images.githubusercontent.com/30130006/192625402-48c585a3-b0b3-4ac5-b504-ee9653973777.png)

So i wonder if it's in purpose and you intend to reuse this library for `jetstream` in the future and so if we can assume that it would have backward compatibility with`nats streaming` somehow.

**Comment by kozlovic** [comment]
@erwanriou The client https://github.com/nats-io/stan.js is the one to use for NATS Streaming. For JetStream, you can use: https://github.com/nats-io/nats.deno (https://github.com/nats-io/nats.deno/blob/main/jetstream.md)

**Comment by erwanriou** [comment]
@kozlovic thanks, i though it was for `deno` only. I will take the time to read it through at try it.

**Comment by ehovaere** [comment]
Hi @erwanriou ,

I'm in the same  situation than yours. For a POC, I successed at replacing nats with jetstream but if I remembered well, you have to  create and to handle each stream separatly. A stream must have its own configuration and a 'max size' or 'max  messages count' setting.. which is annoying  as it means old messages will  be suppressed once the limit reached...It can be resolved using streams replicas.. backup and  restore etc..  but I think it's a bit tricky for a developer  approach. STAN were easier to setup and use.
See the discussion here https://natsio.slack.com/archives/CM3T6T7JQ/p1649235082171679

Moreover, if you want to migrate your old messages, I  suppose  you'll have to write a tool which will   subscribe to all  STAN events and publish  them to new  jetstream streams.. but not sure about the "nice"  way to do so.
The community on natsio.slack.com seems to have the required skills  but I'm currently looking forward other solutions such  as  kafka... I'll be annoyed if jetstream becomes  deprecated in 2 years.
Somebody gave me link to that tool but I did not investigate furthermore
https://github.com/snapp-incubator/stan-js-replicator

**Comment by bruth** [comment]
@erwanriou Thanks for calling out the error. Fix open here: https://github.com/nats-io/nats-site/pull/776

@ehovaere I can understand the frustration of dealing with the deprecation. NATS Streaming was the first generation persistence layer for NATS and there are fundamental design decisions that has limited it's ability to scale and adapt as the core NATS server has evolved. All of these learnings led to taking on JetStream which is now built-in to the server, not a separate project/dependency like STAN.

> I'm currently looking forward other solutions such as kafka... I'll be annoyed if jetstream becomes deprecated in 2 years.

Of course I do not know your use case, so I can't recommend/argue against using Kafka (NATS/Jetstream and Kafka are fundamentally different.. they just have similar concepts), but if you are considering it simply because of concern of future JetStream deprecation, then FWIW, I wouldn't be concerned about that at all. It has been instrumental for adoption and its built-in to the server. Completely different situation than STAN.

> A stream must have its own configuration and a 'max size' or 'max messages count' setting.. which is annoying as it means old messages will be suppressed once the limit reached

You can choose how many streams you want, but note that any number of subjects (including wildcards) can be mapped to a stream. So you if you prefer a single stream for all subjects, then you can do if it makes sense for your workload.

By default there are no limits imposed on a stream. If you are using [NGS](https://app.ngs.global/) then there are plan limits, but not if you run the servers yourself.

> I suppose you'll have to write a tool which will subscribe to all STAN events and publish them to new jetstream streams.. but not sure about the "nice" way to do so.

As noted above in my previous comment, I was offering to support/strategies for a successful migration. However, everyone's use case and setup is different, so the suggestions may be vary. If you can give me a run-down of your streams, configuration needs, etc. I should be able to provide a good path forward to JetStream.

**Comment by rhzs** [comment]
> As noted above in my previous comment, I was offering to support/strategies for a successful migration. However, everyone's use case and setup is different, so the suggestions may be vary. If you can give me a run-down of your streams, configuration needs, etc. I should be able to provide a good path forward to JetStream.

Apologize to jump in, because we need to care **more** on the developer experience. Not focus on bloated use cases. If the answer is all depends on the use cases, there is no ending on it. Just focus on basic and simple use case first, then we talked advanced or beyond.

**Comment by bruth** [comment]
@rhzs Thanks for the feedback (seriously.. text is bad to express emotion) and I get that "use case" is often a way to defer practical, "give me code now" options.

My **blunt** suggestion would be "STAN and JetStream both provide stream abstractions.. so read about how JetStream does it and write a function that connects to both old and new and convert the messages." However, there are various questions that come up with that statement.

- Are STAN and JetStream streams the same? What are the differences and/or trade-offs?
- Does this require my STAN instance to be offline (and thus my application)? Or can I do a live migration?
- Will my translation function keep up with the load for my workload? I can only tolerate so much downtime.

The mechanics are straightforward, but these other considerations may impact how it actually gets implemented in practice.

If the feedback was more focused on "write a document on the practical considerations on converting streams and consumers from STAN to JetStream," then that is actionable and likely more useful than code that may not work for everyone.

**Comment by erwanriou** [comment]
@ehovaere thanks for your help. I could see that jet stream implementation is slightly less digested than it is currently with stan. Setup the Jetstream statefulset was not so hard tho. What is more of a problem for me is to rewrite all the helpers functionalities regarding my emitters and listenners on my backends. Kafka or rabbitMQ will require at least the same or more work anyways so i rather stay with nats where i somehow understund i bit more (so far).

I pretend to build a POC and build some kind of OOP helper that would handle connection, configuration, messaging with more ease that it have to be currently for nodejs for simple usecase like mine.

Migration of old messages might be an issue also but i will take it as a separate case and since it's a one time script i am less worried ( i can go dirty there)

@bruth ` but if you are considering it simply because of concern of future JetStream deprecation, then FWIW, I wouldn't be concerned about that at all.` 
This is good to hear really!

**Comment by bruth** [comment]
For those interested, I will be hosting a virtual event for folks who want or need to migrate to JetStream. It will be focused on connecting the concepts between STAN and JetStream, discussing migration considerations, and then Q&A. You can register here: https://hopin.com/events/nats-streaming-to-jetstream

**Comment by bruth** [comment]
A quick update to folks on this thread:

- Here is the [recording](https://www.youtube.com/watch?v=yKI9YmLx_8A) of the webinar mentioned above (on YouTube) and the [slides](https://docs.google.com/presentation/d/e/2PACX-1vRJ5-gyW7Wignxt_l6sNrCWDXUevm7fChuJBrWIFWygxMMmEh7a_IjnYpkMuPMah-CZPN0Tk50Vhxti/pub?slide=id.g1fa73f6fc1d_0_206)
- Here is a new data migration tool, called [stan2js](https://github.com/nats-io/stan2js) and an [example](https://natsbyexample.com/examples/operations/stan2js/cli) showing how to use it and the output

I am going to close this issue, but if you have very specific migration needs beyond what these resources provide, feel free to post here or connect with the NATS team on Slack.
