### ISSUE TITLE
High memory consumption while recovering damaged data file (in scenario in-file storage)

### ISSUE THREAD

**Issue by Jerito-kun** [nats-io/nats-streaming-server#1255]
High memory consumption while recovering damaged data file (in scenario in-file storage)
In case, when (for unknown reason) one of data file was damaged (for example: bad EOF mark), server make a note in log file:

{"level":"info","time":"2022-06-23T13:14:37+03:00","message":"Server is ready"}
{"level":"info","time":"2022-06-23T13:14:38+03:00","message":"STREAM: Recovering the state..."}
{"level":"error","time":"2022-06-23T13:14:43+03:00","message":"STREAM: Verification of last message for file \"C:\\\\ProgramData\\\\Some_folder\\\\NSS\\\\data\\\\Some_file.Log\\\\msgs.1.dat\" failed: unable to read last record: unexpected EOF"}
{"level":"error","time":"2022-06-23T13:14:43+03:00","message":"STREAM: Error with index file \"C:\\\\ProgramData\\\\Some_folder\\\\NSS\\\\data\\\\Some_file.Log\\\\msgs.1.idx\": Verification of last message for file \"C:\\\\ProgramData\\\\Some_folder\\\\NSS\\\\data\\\\Some_file.Log\\\\msgs.1.dat\" failed: unable to read last record: unexpected EOF. Truncating and recovering from data file"}

Memory usage exceeds more than 1,6 Gb instead of ~30 Mb in normal operating mode.

![image](https://user-images.githubusercontent.com/39138364/175277186-eefd12d9-9968-468e-b381-9cd502043f29.png)

Problem gone by deleting the damaged file or restarting server, but in such case damaged file continues to exist and other software, whose using this file to operate, cannot start and work.
This sutuation occurs both on Windows and Linux hosts, including 0.24.6 software version.

**Comment by kozlovic** [comment]
Do you have the store file that we could use to reproduce? It is possible that a corruption causes the server to think that a payload/etc.. is of a size bigger than it is, but this is just speculation at this point.

I am not clear on this:
```
Problem gone by deleting the damaged file or restarting server, but in such case damaged file continues to exist and other software, whose using this file to operate, cannot start and work.
```
If you delete the file, which then resolves the issue, how can the file "continue to exist"?

**Comment by kozlovic** [comment]
> Yes, sure. Could you please tell me, which way can I send you these files?

If you have the corruption, you could send the whole datastore directory to ivan@nats.io.

**Comment by kozlovic** [comment]
@Jerito-kun As suspected, the high memory usage is due to a corrupted record that indicates that the message payload is ~1.6GB which then cause a memory allocation of that size. Note that the buffer is then released, so the actual memory in use is not that much and when garbage collection will kick in, the memory should be reclaimed (I have verified with `-profile <port>` that this memory was allocated but not currently in-use).

Given that, I am not sure what is the best course of action here. I could make reading a record fail if it means that the server would have to create a buffer of a certain size, but which? hard-code? a new option? Or leave as-is, again knowing that the memory was allocated, but not currently in-use.

**Comment by Jerito-kun** [comment]
I think, a new option will be the best.

**Comment by kozlovic** [comment]
@Jerito-kun I added that in PR 1259 and 1260. This will be part of the next release.
