### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by njern** [nats-io/nats-streaming-server#167]
Hey guys,

Thoughts on adding [contributing guidelines ](https://github.com/blog/1184-contributing-guidelines) to the project? 

As a NATS "outsider" it would be nice to know what types of PR:s you are happy to take in / if there is a specific process you prefer, like open issue -> issue accepted -> PR ?

**Comment by kozlovic** [comment]
We don't have formal guidelines as of now. We welcome PRs, but I think what you propose seem to make sense in that we don't want users to spend time working on a PR to be rejected because it does not fit with the project or we had planned to address that a different way, etc... So unless a very trivial one, I would recommend vetting the idea first by opening an issue (which can be marked as bug, enhancement, etc..). Also, if you are not already on our Slack channel, I would recommend you joining. Let me know if you need more info on that.

**Comment by njern** [comment]
Sounds good. My Slack account is my first name at walkbase.com if you don't mind sending over an invite.
