### ISSUE TITLE
STAN appears to have a memory leak

### ISSUE THREAD

**Issue by sfrooster** [nats-io/nats-streaming-server#183]
I've run three different tests over the weekend, all with nearly identical results.

Using four vm's in our datacenter, one running STAN+NATS, one publishing only (java), one subscribing and publishing (node) and one subscribing only (java), I see the memory usage (as reported my nats-top) climb slowly towards ~7.5G.  Along the way, NATS will prune STAN a few times as a slow consumer.  In the 7.5G neighborhood STAN will disappear permanently* (* = at least for many hours - I haven't yet seen it come back).

The STAN process is not aborted, the file system is not full, but it no longer appears in nats-top and messages are no longer delivered (and the file store is no longer growing), even though the publisher does seem to think it's still publishing (albeit very slowly) and is still receiving acks.

I can provide additional detail upon request.

**Comment by kozlovic** [comment]
I saw from an email thread that you have set the number of messages/size to unlimited. Could it simply be that you are storing tons of messages? Also, default file store implementation keeps messages in memory, which would make the memory growth go faster (file_cache=false) would reduce this.

**Comment by sfrooster** [comment]
I do have it set to unlimited.  In terms of file store, this should be ok as long as you have disk space - and we do.  We also have cache set to true.  I was under the impression that this would intelligently cache some of the messages, not blanket cache all of them.  If it caches all messages in memory, how do you ever clear them out without restarting the server?

I will rerun the test with cache = false, but can you clarify how the cache works?

**Comment by kozlovic** [comment]
In early implementation, all messages were cached. In v0.3.0, same by default and but you can configure for no message cached at all (expect for short amount of time due to use of buffered write on disk). 
Regardless of caching or not, if you set to unlimited, there is still memory used on a per-message basis, so the more messages you store, the more memory the server will use (it's just that it may be much less if you don't use caching vs using caching with messages having a payload).

**Comment by sfrooster** [comment]
I'm re-running now with unlimited=true, cache=false.  We'll see what happens with that.

In terms of setting limits/ages on messages - if you want to keep 7 days (168 hours) of messages around, can you specify just that, or do you have to also estimate how many messages/bytes that will be and set those as well?  That is, can you set those values to 0, only set the age, and have it work as expected?

I'll report back when this test has run for awhile and maybe we can close this issue.

**Comment by kozlovic** [comment]
As a side note, I have created https://github.com/nats-io/nats-streaming-server/issues/184 to improve default caching for file stores.

**Comment by kozlovic** [comment]
Regarding age limit: as of now, I would recommend setting a limit in count and/or bytes, otherwise a single file would be used, which would prevent store from removing file "slices".

**Comment by sfrooster** [comment]
We've been running for a bit (1.1M messages) and something interesting happened. Here are memory sizes for various numbers of messages sent:
36000     38.1M
400000   209.1M
880000   617.6M
1.1M         585.4M
1.2M         623M

Not sure what's going on there, but it did reclaim some memory at one point.

**Comment by kozlovic** [comment]
Garbage collection. Go will increase memory and set targets for garbage collection, so you may see jumps not proportional to the number of messages being sent. 
Is this test using a single channels or multiple? Each store has buffered writers with a default of 2MB buffer size. They will shrink when not in use, but if you have multiple channels, the memory footprint will increase.

**Comment by sfrooster** [comment]
Two channels currently.

**Comment by kozlovic** [comment]
Did you use `file_cache=false`? In my tests, 1.2M messages with file store and cache disabled makes streaming server plateau at ~200MB (mac os x, go 1.6.3), regardless the size of the messages (since caching is disabled). As a test I have set the max count to 1.2M, max bytes to unlimited and keep sending 1M messages. Memory footprint constant.
```
Ivans-MacBook-Pro:nats-streaming-server ivan$ nats-streaming-server -store file -dir datastore -file_cache=false -mm 1200000 -mb 0 -m 8222
[17576] 2016/10/24 17:26:24.927487 [INF] Starting nats-streaming-server[test-cluster] version 0.3.1
[17576] 2016/10/24 17:26:24.928587 [INF] Starting nats-server version 0.9.4
[17576] 2016/10/24 17:26:24.928592 [INF] Starting http monitor on 0.0.0.0:8222
[17576] 2016/10/24 17:26:24.928597 [INF] Listening for client connections on 0.0.0.0:4222
[17576] 2016/10/24 17:26:24.928651 [INF] Server is ready
[17576] 2016/10/24 17:26:25.267298 [INF] STAN: Message store is FILE
[17576] 2016/10/24 17:26:25.267310 [INF] STAN: --------- Store Limits ---------
[17576] 2016/10/24 17:26:25.267315 [INF] STAN: Channels:                  100 *
[17576] 2016/10/24 17:26:25.267317 [INF] STAN: -------- channels limits -------
[17576] 2016/10/24 17:26:25.267321 [INF] STAN:   Subscriptions:          1000 *
[17576] 2016/10/24 17:26:25.267324 [INF] STAN:   Messages     :       1200000
[17576] 2016/10/24 17:26:25.267327 [INF] STAN:   Bytes        :     unlimited
[17576] 2016/10/24 17:26:25.267329 [INF] STAN:   Age          :     unlimited *
[17576] 2016/10/24 17:26:25.267331 [INF] STAN: --------------------------------
[17576] 2016/10/24 17:26:53.520562 [INF] WARNING: Reached limits for store "foo" (msgs=1200000/1200000 bytes=640783492/0), dropping old messages to make room for new ones.

varz:
"mem": 208510976,
```

**Comment by kozlovic** [comment]
Note the above is for a single channel, 1.2M. If I have 2 channels, we then store 2.4M messages, and memory goes to ~380M.

**Comment by kozlovic** [comment]
If your messages are quite big and producer rate is high, there will be pressure in memory when those messages are processed by the server. With async producers, it is possible that thousands accumulate in the server before being processed, so that will make the memory usage jump, but then it should be bounded if the total number of messages does not increase.

**Comment by sfrooster** [comment]
Ah - well our situation is a little different. We have clients A, B, C.  A pubs messages of type M1. B subs messages of type M1. Our framework is also sending "tracers" so that pub'ing a message, or receiving a message as a sub, will pub a message of type M2 (pub'ing or sub'ing M2 does not fire another tracer).  C is sub'ing to M2.

So, in reality, when I say 1.2M, it's really 3.6M.

**Comment by kozlovic** [comment]
Ok, so this plus the incoming rate that may cause the server to temporarily need to have many thousands of messages in memory (if you use async producers), so that could very well explain this. Again, the test would be to set a limit on the number of messages per channel and verify that the process does not grow overtime.

**Comment by kozlovic** [comment]
and that's the test I just did to say that the mem usage reach a plateau when the limit of messages is reached.

**Comment by sfrooster** [comment]
I'm going to leave this test running for awhile and, if things keep chugging along, I'll close this issue.

I'll probably end-up opening a different feature req / issue around being able to specify max message age AND have that timeframe split into multiple files, or specifying unlimited with a max file size (and so multiple files). All of which has to do with being able to take a file and archive it off before it is overwritten (and then later, some way to load a file like that back up), etc.

That's mostly covered under another request, though, so maybe I'll just append to that.

**Comment by sfrooster** [comment]
The test is at ~21 hrs now, doing much better than when cache was set to true.  We're around 7.8M messages (so x3 - 23.4M) and memory is at 3.3G.  I am curious what is being kept in memory that is causing it to continuously grow.  I realize you're saying it's not a leak and I'm inclined to agree. But if everything has been delivered and ack'd etc, what is the server holding in memory?

**Comment by kozlovic** [comment]
The file store still maintains a map with message sequence as the key (an uint64) and the value is a record of about 32 bytes (contains vital information for a message that server needs in memory).

But I think that the bulk of memory you see is because of the influx of messages before they are even persisted. This causes memory to grow and memory is not released back to OS. 
Using sync producers will probably show less memory usage because per producer, a single message at a time will be processed by the server. (performance would be bad, but done as a proof).

**Comment by sfrooster** [comment]
So what is the suggested way to avoid this? Is this a by-product of "unlimited messages"?  Would the memory be freed once messages were expired or...?  How do we operate a server with this sort of throughput (about 1.1M / hour) without having to schedule reboots to reclaim memory?

**Comment by kozlovic** [comment]
It is very well possible that we have a memory leak, but:
- The file implementation still needs memory per-message. So the more you store, the more the process size will grow.
- The number of connections/subscribers, processing of acks, etc will also require memory in the server.
If with a similar influx of messages the process size grows, but slowly, it may just be the memory needed to store the messages. If that's the case, there is nothing you can do for releasing memory back to OS.

When I test with a limit in the number of messages, the process usage is more than you would expect for storing that given limit (and again I think this is due to the rate of incoming messages) but then even sending many times over the limit, the memory barely grows.

**Comment by sfrooster** [comment]
I think there needs to be some refinement around managing the file store, and memory. But I don't currently have a reason to believe there's a memory leak so I'm closing.
