### ISSUE TITLE
use monotonic time source instead of time.Now()

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats-streaming-server#231]
Given this:
https://blog.cloudflare.com/how-and-why-the-leap-second-affected-cloudflare-dns/

and the current state of the time.Now() call not being monotonic:
https://github.com/golang/go/blob/29cb72154d3bb3530d8092cc89d35b3ed4f7e9c5/src/runtime/sy\
s_linux_amd64.s#L147

you may wish to prefer this:
https://github.com/glycerine/monotime

and replace calls to `time.Now()` with `time.Unix(0, int64(monotime.Now()))`

**Comment by kozlovic** [comment]
At a quick glance, I don't think we need that. There may be places where we could/should check for negative values, but most of the time it will be harmless. I will still have a go at places where we do sub time to check.
Note that it seems that nanotime() is not always monotonic on all platforms. I have started to code a quick benchmark and it always fail for me on Mac OS/X Yosemite (with Go 1.6.4 and 1.7.4), but passes on a Ubuntu 14.04 VM:
```
func BenchmarkTimeMono(b *testing.B) {
	prevTime := uint64(0)
	for i := 0; i < b.N; i++ {
		t := monotime.Now()
		if t < prevTime {
			b.Fatalf("Time went backward: i=%v t=%v prev=%v diff=%v", i+1, t, prevTime, int64(t-prevTime))
		}
		prevTime = t
	}
}
```
Here is the output:
```
BenchmarkTimeMono-8   	--- FAIL: BenchmarkTimeMono-8
	bench_test.go:15: Time went backward: i=18871104 t=1483467178103227000 prev=1483467178103227209 diff=-209
```
To be fair, the same with `time.Now().UnixNano()` fails too:
```
BenchmarkTimeNow-8    	--- FAIL: BenchmarkTimeNow-8
	bench_test.go:26: Time went backward: i=49161931 t=1483467178613243000 prev=1483467178613243922 diff=-922
```

**Comment by glycerine** [comment]
sure, it may not work on all platforms, but best effort seems worth it.  It will prevents bugs on a linux server, for example.

> most of the time it will be harmless

Yep, but that's not a high standard, and represents a fairly cavalier attitude to correctness. 

Why require that high-performance systems using nss be subject to unnecessary bugs every so often?

**Comment by kozlovic** [comment]
Like I said, I will fix places where time.Sub() leading to negative values will cause problems. Since nanotime() is not guaranteed to be correct in all platforms, those fixes would still be required anyway for correctness on all platforms.

As a side note, I don't know how nanotime is implemented in Go, but other languages's version of nano time is supposed to be used just for timing things (elapsed time between some operations) but not to represent time. So creating a time from that value (as you suggest for Go using `time.Unix(0, int64(monotime.Now()))` would be wrong in those languages. Also not safe to use in different threads since comparison could also lead to negative values there.

**Comment by glycerine** [comment]
> I don't know how nanotime is implemented in Go

On linux, it uses the same vdso as clock_gettime(CLOCK_MONOTONIC, &struct timespec)

> Also not safe to use in different threads since comparison could also lead to negative values there.

In Go, on linux, since the CLOCK_MONOTONIC vdso is used, it should be okay across threads. Discussion:
http://stackoverflow.com/questions/4943733/is-clock-monotonic-process-or-thread-specific

**Comment by glycerine** [comment]
although, depending on release, this may be relevant:
http://stackoverflow.com/questions/3657289/linux-clock-gettimeclock-monotonic-strange-non-monotonic-behavior

**Comment by kozlovic** [comment]
Well, that proves my point, I think. It is better to fix applications that perform time subtractions and account for possible negative values than rely on `monotime.Now()` since it is not for supported on all platforms and even then, subject to some issues depending the releases. That is, until some cross platform API is provided that gives a monotonic elapsed time.

And I am correct saying that your approach of re-creating time from `monotime.Now()` is wrong. Actually, the API name itself is misleading. It implies that it is giving back a time, where it gives a number of nano-seconds since an arbitrary time. 

You can test for yourself: print the time from `time.Now()` and as you suggest from `time.Unix(0, int64(monotime.Now()))` and see the result (on Linux box for which CLOCK_MONOTONIC is actually defined):
```
Time now=2017-01-03 23:19:43.438443798 +0000 UTC monotime=1970-01-01 00:05:48.684810285 +0000 UTC
```
