### ISSUE TITLE
Q: message size limits or packetize and reassemble?

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats-streaming-server#250]
Q: To transmit a big file, does nats-streaming chop up and re-assemble messages--like TCP--so that it can avoid over-running internal fixed sized buffers but still handle transmitting an infinite stream?

**Comment by kozlovic** [comment]
NATS Streaming is subject to the payload limit imposed by NATS, since NATS is used to communicate between the Streaming server and its clients. The `max_payload` config parameter is the one that set this limit. See for instance at the end of the NATS Server configuration file [here](https://github.com/nats-io/gnatsd#configuration-file).

Note that in Streaming, all messages exchanged between the server and clients use protobuf and contain meta data, so when a Streaming client sends a message, the payload of the NATS message being sent contains some meta data and the user payload. Therefore, with NATS Streaming, the maximum user's payload will have to be less than the `max_payload` limit. Unfortunately, how much less is not a constant since again the meta data and payload is a protobuf object and serialization does some variable encoding.

**Comment by glycerine** [comment]
Ironic. Are there any plans for such?  I mean, plans to actually support streaming (by which I mean, TCP-like capability to fragment and reassemble streams of arbitrary length) in the nats-streaming-server.

**Comment by kozlovic** [comment]
No. The streaming terms comes from the fact that messages are stored in a log (think Kafka, etc.), that can be interpreted as a stream of events, etc..

**Comment by glycerine** [comment]
Okay. Thanks for filling in the details.

**Comment by kozlovic** [comment]
No problem. And what I tried to say, is that "Streaming" here should not be interpreted as an uninterrupted stream of bytes. In NATS Streaming, each channel stores messages, not a stream of bytes.
