### ISSUE TITLE
Q: FIFO rotation of stored files messages?

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats-streaming-server#251]
Q: In order to avoid needing infinite storage on disk, does nats-streaming have facility for persisting to disk a fixed size (say 1GB) worth of messages, and then rotating messages FIFO when more come in? (i.e. delete the oldest, save only the newest 1GB worth)

**Comment by kozlovic** [comment]
Yes, NATS Streaming define [store limits](https://github.com/nats-io/nats-streaming-server#store-limits) that ensures that a given channel is bound. When the limit is reached, older messages are indeed discarded to make room for new ones. For the memory store, you can see that as a ring-buffer.

For file stores, we use what we call file slices. For a given channel, the messages are stored in files (data and index). When this file reaches a certain size, a new file is created, etc.. When older messages are "discarded", we can't delete the oldest slice until all messages in this slice have been discarded.

On top of the store limits, you can define how big a file slice is. You also have the option to specify an "archive" script that is going to be invoked with the name of the files that would be otherwise discarded, allowing the user to maybe move these files for archiving, etc...

Check [this](https://github.com/nats-io/nats-streaming-server#file-store) for general description of File Store and [this](https://github.com/nats-io/nats-streaming-server#file-store-options) for File Store options.

**Comment by glycerine** [comment]
> When older messages are "discarded", we can't delete the oldest slice until all messages in this slice have been discarded.

Excellent.  I like this design; it sounds super useful.
