### ISSUE TITLE
Q: fsync schedule

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats-streaming-server#252]
Q: When doing disk based persistence, what kind of fsync schedule is used in nats-streaming? 

For example, does n.s.s. fsync after each message or after a fixed time period? 

Since an fsync schedule controls durability versus throughput, is there some way to fsync only every so often and still recover from disk in the case of disk corruption (say by writing a checksum/checkpoint to disk and using it to recover to the last know good point even upon corruption detection)?

**Comment by kozlovic** [comment]
When the server receives messages from publishers, it may accumulate some, possibly from different channels, then starts processing of those messages. They are persisted and possibly sent to matching subscribers. When the processing of the batch of messages is done, the server calls `MsgStore.Flush()` and `SubStore.Flush()`. This is where `File.Sync` is called on corresponding files. So by default, if a publisher gets an OK for a given message, you have the guarantee that message was persisted and fsync was performed. 

Some users may not need/want fsync (for instance, use of storage backed by battery, etc..) and so the option can be disabled.

The command line parameter to enable/disable fsync is this:
```
--file_sync                      Enable File.Sync on Flush
```
The configuration parameter description is this:
```
# Define if server should perform "file sync" operations during a flush.
# Can be sync, do_sync, sync_on_flush
sync: true
```

**Comment by kozlovic** [comment]
Also, we actually had a discussion on that in Slack some time back. The idea of doing a fsync in background was discarded, because then it is a bit pointless since there would not be a way to directly report to the producer that its message did not make it.

And yes, we also use crc32 checksum on each record. They are always computed and stored, and you have the option to disable the checksum on reads (`--file_crc=false`).

**Comment by glycerine** [comment]
> And yes, we also use crc32 checksum on each record. They are always computed and stored, and you have the option to disable the checksum on reads (--file_crc=false).

If you don't need to ack to the producer, one way to avoid having to fsync too frequently is to append to the file, every so often, a very unique locator (think 100 bytes, generated once randomly,  but then fixed -- so extremely unlikely to occur by chance, but uniquely locating a good record in the middle of a corrupted file) -- along with a checksum of the previous record.

Then upon failure and recovery you read back through the file to find the last uncorrupted locator.  32-bit crc don't really let you re-sync your read in the face of a corrupted file, but combining a 100-byte unique locator with a crytographic checksum does; then you can get excellent throughput without sacrificing durability. You don't get transactions, but you can recover to a consistent state from 30 seconds ago (last fsync point). This suffices for many, many case.

**Comment by kozlovic** [comment]
> If you don't need to ack to the producer, 

Yes but we do ;-) Even when producer is sending asynchronously (that is, the API does not block waiting for the ack or error), the server sends back an ACK for every single message produced.

>one way to avoid having to fsync too frequently is to append to the file, every so often, a very unique locator (think 100 bytes, generated once randomly, but then fixed -- so extremely unlikely to occur by chance, but uniquely locating a good record in the middle of a corrupted file) -- along with a checksum of the previous record.

I see. I guess the marker would have to be written first and fsync'ed so that when recovering the file, the store knows what is a "valid" marker, right? Or is it that this marker is randomly generated but then hardcoded in the Streaming code?

>Then upon failure and recovery you read back through the file to find the last uncorrupted locator. 

The thing is that our FileStore implementation does not recover the data file, only the index file to reconstruct state of each file slices (first/last seq in this file, total size, etc..). The index file also contain the offset of a given message's seq in the data file. I used to maintain the index map in memory (as part of the recovery), but no longer do. So now FileStore memory footprint is flat (almost) regardless of the number of messages you store (at a cost of disk reads to get the message's index then offset then data).

You can imagine situations where there would be Gigs and Gigs of data. It could take a while to restart the server if it was to recover data. It is much faster when it simply recovers the index files.

**Comment by glycerine** [comment]
>  I guess the marker would have to be written first and fsync'ed so that when recovering the file, the store knows what is a "valid" marker, right?

well, the idea is that there's no need to fsync the marker, that's the whole point. the marker just lets you synchronize your read. just in front of the marker is your cryptographic hash of the previous record. once you've located that hash (by means sychronizing your read with the marker/locator), then you can detect corruption. In practice I actually use two hashes, one over the previous record and one over the checksum+locator itself. You get a merkle chain like git.

> this marker is randomly generated but then hardcoded in the Streaming code?

yes, that is right.
