### ISSUE TITLE
Historical data related questions

### ISSUE THREAD

**Issue by foobargeez** [nats-io/nats-streaming-server#266]
I am currently developing an application (with a mobile app as frontend) that will have a "feed" like functionality (feed is simply a bunch of JSON documents starting with most recent and delivered in batches, when the mobile requests for more data).  Note that I do not need to track the client state (read/unread/something else).  I do not know if NATS streaming is a good fit for my requirement and wasn't sure about a few things.  I would appreciate if someone can confirm/clarify either way:

- As I understand, the data is either stored in RAM or files but not both (i.e., after hitting a RAM threshold, leverage file store etc.,).  I would always want to deliver the recent, say 100, msgs as quickly as possible, so storing in RAM is preferred.
- Is there a way to request data in batches? i.e., start with recent but limit the message count to `<N>` msgs
- Is there a way/interface to edit already published data (either in RAM/file)?
- Is supporting an external datastore a priority (MongoDB, Elastic or something)?  This lets me take care of the HA for the data store and allows me to edit the content outside of NATS.

Thanks and do let me know if something is unclear.

**Comment by kozlovic** [comment]
@foobargeez 
* At this point, you are right that the server is either using a memory or file based store, not a mix. Actually, the file store has a small cache that is not really configurable and allow to keep recently stored messages in memory: this is so that when the server stores a messages and right away send it to matching consumers, messages do not need to be read from disk.
* When a consumer is created, it can set the `MaxInflight` option (defaults to `1024`). This tells the server to not send more than this number of messages without receiving ACKs from the application. This serves as flow control.
* No, messages cannot be edited, regardless of the type of store used.
* Support for databases is something that we have always considered by lack the time. We have made the store an interface to make it easier for the community to contribute different implementations. We are working on an FT solution as an interim to a full cluster solution. This would still be based to the provided file store implementation, but again would work for a different shared storage method. (see issue https://github.com/nats-io/nats-streaming-server/issues/263)
