### ISSUE TITLE
Embedded NATS monitoring port

### ISSUE THREAD

**Issue by m4ce** [nats-io/nats-streaming-server#310]
Hi,

I've noticed that when running the streaming server with the embedded NATS instance, the monitoring http port doesn't seem to work when specified.

```
# NATS server configuration
host: 0.0.0.0
port: 4222
http_port: 8222
```

I've also tried monitor_port, http etc. but none of these seem to work. The NATS server runs okay but it doesn't seem to create a listening socket on that port.

**Comment by kozlovic** [comment]
First, keep in mind that so far, there is no monitoring specific to NATS Streaming. What you would get with the embedded NATS monitoring http server are stats related to NATS itself. Issue #116 that is in the works will bring Streaming specific metrics monitoring.

Regardless, since monitoring is actually triggered by NATS code, you need to pass this config through the NATS settings (`-c`). The config specific to NATS Streaming is given through `-sc`. You can have the NATS and Streaming configuration in the same file, but you would need to pass it twice with `-sc` and `-c`.

I have created an enhancement request (issue #311) to have the server tries to parse the config file for both NATS and Streaming with the use of any of the `-c` or `-sc` parameter.

**Comment by m4ce** [comment]
@kozlovic, thanks for the feedback. I will try your suggestions and wait for the new release with regards to monitoring NATS streaming.
