### ISSUE TITLE
Intermittent results - Increasing or Large number of subscribers with stan-bench not working

### ISSUE THREAD

**Issue by rogeriofza** [nats-io/nats-streaming-server#327]
I am presently utilizing the **stan-bench.go** benchmarking example utility with **nats-streaming-server-v0.4.0-darwin-amd64** on my MacBook Pro locally.

Start up of NATS streaming server is as follows:  
`./nats-streaming-server-v0.4.0 -m 8222 -msu 0 --file_fds_limit 500 -D`

This server starts up fine.

I then hop over to the stan-bench utility and try to simply run 1 msg (68 bytes) using 1 publisher to N number of subscribers.  Example command I am giving is:

`go run $GOPATH/src/github.com/nats-io/go-nats-streaming/examples/stan-bench.go -s nats://localhost:4222 -np 1 -ns 100 -n 1 -ms 68 -a foo`

As I increment the number of subscribers past 100 or so I get intermittent results
For instance:

-90 Subscribers, works fine
-100 Subscribers, works fine
-110 Subscribers fails with following message 
`Subscriber benchmark-sub-xx can't connect: read tcp [::1]:portnumber->[::1]:port number: read: connection reset by peer`

- I then proceed to go back down to 105 subscribers, works fine
- Increment by 5 to 110 it works.
- 115 Subscribers it works
- 120 Subscribers - fails again
- I try the same 120 Subscribers again and then it works

I have tried at thresholds of 140 and get the same error. I find if I try go to say 140 after from 120 subscribers it doesn't work, but if I increment it gradually i get 135 working and then ultimately 140 working without a retry.

I have a use case to publish to well over 100 000 subscribers. The server is saying unlimited subscribers on startup. So I am questioning whether or not am I doing something wrong or not, or is there indeed a bug with a large number of subscribers > 100.

Assistance on this matter would be greatly appreciated. PS. I have also attempted with async enabled. I get the similar results.

I made a recording to show you the intermittent results as an example.
Find it here - https://www.dropbox.com/s/9u6jtkebhnjlykh/nats-sbench-intermittent-results.mov?dl=0

**Comment by kozlovic** [comment]
Sorry for the delay in getting back to you. I don't see such problem with such a small number of subscribers. But keep in mind that `stan-bench.go` creates an individual connection per subscription. It means that there will be 100+ connections to the NATS Server. The NATS Streaming Server also has 2 connections to the server. Each connection will consume 2 FDs (one on each end since you are running server and clients on the same machine). Make sure that you are not hitting the default number of allowed FDs on your shell.

Note that `--file_fds_limit` is only for the file descriptors used by the FileStore implementation. It does not limit the number of FDs required for TCP connections.

You may want to try increase the system FDs limit, or move your clients to another box, to leave more FDs for the server itself.

**Comment by kozlovic** [comment]
Closing for now, will re-open if needed. Thanks!
