### ISSUE TITLE
Idea:  notify client when a store limit is reached and message cannot be processed without deleting others

### ISSUE THREAD

**Issue by vl409** [nats-io/nats-streaming-server#418]
Quoting doc:
> Finally, the number of stored messages for a given channel can also be limited with the parameter 
> `-max_msgs` and/or `-max_bytes`. However, for messages, the client does not get an error when the 
> limit is reached. The oldest messages are discarded to make room for the new messages.

Such behaviour makes it impossible to implement normal client-side rate limiting.
If at some moment clients produce more messages than server can process, it means
messages are silently dropped. And there is not even a counter in statistics for such cases.

The proposal is to reply to client with ack, and set something like HTTP 503, meaning: now
server can't process the message, come later. Even without changing protocol, setting
PubAck.Error to something special may help.

There is no sense in dropping some not-yet-processed messages to accept others.

Increasing queue size is not an option, because it is not endless anyway, and with big queue
you get more expenses for managing it (including garbage collector).

**Comment by kozlovic** [comment]
@vl409 With the current design, it would not make sense to fail the publisher since the message is accepted, only older messages are dropped to make room.

Keep in mind that in streaming, a message is never removed because it has been "processed" by a consumer. Messages are appended, regardless of subscription interest.

If we were to reject the incoming messages because the channel is full, then effectively, the channel would never be able to accept any new message since messages are not removed from the channel due to subscriptions, but only when limits are reached.

The only case where we could possibly (through an option I guess) do that is that if the channel has a max_age limit, so messages are discarded based on the time they stayed in the channel. 
Still, this may not be a good fit for you if you believe that a message should not be removed until it has been processed (consumed by at least one consumer).

**Comment by kozlovic** [comment]
Closing for now, don't hesitate to reply with comment, etc.. and we will re-open.
