### ISSUE TITLE
Feature: Notification when subscriber is done receiving from cache and start receiving in "real time" 

### ISSUE THREAD

**Issue by runech** [nats-io/nats-streaming-server#430]
I have three different scenarios where this feature could be of use:

Publishing client crashes and wants to continue from where it left off when re-started.
The problem is at first start-up and there are no "last published message". Currently I need to use (unreliable) time-out to decide whether to start with message 1. If I received "real-time notification" immediately I could use that as trigger.

A subscribing client is expected to process cached messages, starting from where it ended previous time, then stop. Currently I need to use (unreliable) time-out to decide when to stop.

Client and per-day caches (similar to 2). I know message log for yesterday is complete, but, unless I on app-level enforces some "end of day" message, I have to wait for time-out to decide processing is complete.

I have tried to find this functionality, or similar, in documentation, Java client source code and Stack Overflow (https://stackoverflow.com/questions/47394907/is-it-possible-to-see-if-subscriber-have-received-last-message-when-using-nats), but failed.

**Comment by kozlovic** [comment]
> Publishing client crashes and wants to continue from where it left off when re-started.
The problem is at first start-up and there are no "last published message". Currently I need to use (unreliable) time-out to decide whether to start with message 1. If I received "real-time notification" immediately I could use that as trigger.

How? That is, how would you expect to receive such notification and what would that be? What would your publishing application with that notification?

> A subscribing client is expected to process cached messages, starting from where it ended previous time, then stop. Currently I need to use (unreliable) time-out to decide when to stop.

Again, not sure how you expect to receive a notification and what that notification should include?
A durable subscription allows you to restart your subscription from the last message consumed. What do you consider cached data versus real time data?

> Client and per-day caches (similar to 2). I know message log for yesterday is complete, but, unless I on app-level enforces some "end of day" message, I have to wait for time-out to decide processing is complete.

Not clear on what you expect from server in this use case?

**Comment by tylertreat** [comment]
I agree with Ivan's points. What is the distinction between "real-time" and "cached" data? Further, I think "cached data" is the wrong way of thinking about NATS Streaming. The better idiom I think is a durable log and, as Ivan mentioned, NATS Streaming provides durable streams which allow you to pick up where you left off in that log.

It's also not clear what you mean by the publisher semantics you're describing. Specifically:

> Publishing client crashes and wants to continue from where it left off when re-started.

What do you mean by where the publisher left off?

**Comment by runech** [comment]
Thanks for replying :)

Regarding scenario 1.  I have a pipeline A -> B > C
Box A is a 3rd party message store which could have been a NATS streaming server - I can tell it to start from, e.g., message 1000.
Box B is my application, publishing messages to box C - a NATS streaming server. On failure, of either A or B, I would like to be able to: Restart A an B, then query C for last published message, then using content of that message to query A for messages starting with appropriate start number.

When querying C for this last message, the subscription command, "start from last published" is almost perfect. However; it fails when there are no previously published messages. I have to decide on a timeout to discover this, instead of getting notified. There are several ways to fix this, I just think that this "real time" notification would be appropriate.

"real time notification"  is a (meta-)message the NATS streaming server could send to a subscriber when it discovers it has no more messages to send(yet) because it has sent all available from the log. - someone has to publish more. From then on messages will appear almost in real-time when sent from any publisher; therefore the name "real-time notification".


Regarding scenario 2 - this is for batch processing. I want my application to start, process messages, then exit. I don't want it to wait for messages. E.g. a publisher produces a message 1-20 times per minute. My process starts once an hour, processes all messages, then quits. If it could receive this "real-time notification", it would know it was up to date, and can quit.

Similar for scenario 3: On receipt of "real-time notification"  it would know it has finished processing.

Another example is for latency computation. We have a system which we want to process messages in close to real-time. However, on failure or for maintenance we would like to take down and restart our application without loosing messages - hence the need for NATS Streaming server. However we would like to receive notification for when we are up to speed and can again start monitoring latency - "reaal-time notification" would be an appropriate trigger.

Hope this clarifies my needs.
I can, and will if necessary, work around them (time-outs/querying using monitor interface for number of messages in log) . But I really would love to have this feature.

**Comment by kozlovic** [comment]
But you understand that the "real time notification", that is, a meta message that says that there is no more message is not possible because messages can come at any time. That is, say that there is a constant publishing and the consumer is keeping up, then server will almost send that notification for each message! 

Server *could* send the current last message index in the log when creating the subscription, but again, by the time consumer reaches the end of the log (or at least that position), other messages may have been persisted. This is more what https://github.com/nats-io/nats-streaming-server/issues/175 is about.

**Comment by ColinSullivan1** [comment]
@runech , it sounds like your `end-of-day` message is the correct solution to your problem.  

This seems to be loosely coupling producers with subscribers, something that by design NATS does not do.  Any coordination between the two (beyond subject name) needs to occur at the application level.  In your case, this is batch size, and perhaps some latency data.  

NATS does provide the tools you need to implement a system that should work for you.  Your client could request the last message, and if it is an `end-of-day` message you've already processed, you'll know you have no data.  Otherwise, you have new data to process, and can then pick up where you left off.  If you seed your channel with with an `end-of-day` stub message, then the only time you'd ever hit a timeout would be an error condition, where upon you can toggle your latency checking.  This does assume the channel is setup before you subscribe - otherwise, you'll only hit the timeout once with a new channel.

#175 could help you a bit, where you'd subscribe again to get the ceiling and compare with what's been processed, although you could still run into the issues @kozlovic and @tylertreat mentioned.

You could administratively look at [`/channelsz`](https://github.com/nats-io/nats-streaming-server#channelsz), although IMO that would be unnecessarily complicated when compared to the end of day message.

The `end-of-day` message idea you mentioned sounds like a pretty good approach to solve this problem.
