### ISSUE TITLE
Recovering from corrupted subscriptions  state

### ISSUE THREAD

**Issue by notbdu** [nats-io/nats-streaming-server#440]
Colleague came across this bug today causing STAN to exit on startup.
```
2017/12/01 21:48:36.470383 [FTL] STREAM: Failed to start: unable to create subscription store for [event.9ab3e7223762297ebc37d980701cd4afa4ef72b8c3616281142db29ff613fefc]: unexpected record type: 0
```
Running the `nats-streaming:0.5.0` image.

**Comment by kozlovic** [comment]
This is the second report, however, I could not find an explanation on why there would be a record with type 0. Could it be that the file is extended and pre-filled with 0, but streaming code is not doing that.
Any detail that you could share about OS, file storage use (NFS, local disk, etc...)?
Any chance that you could share the file? (or are you using sensitive information in the subscription such as in clientID, queue group, durable name).
Unfortunately, at this point we don't have a tool to cleanup a corrupted file, so you would need to delete (backup first) the `subs.dat` file in the `event.9ab3e7223762297ebc37d980701cd4afa4ef72b8c3616281142db29ff613fefc` directory. The server will no longer have knowledge of the subscriptions on that channel (and you may have to restart some of your applications that created such subscriptions).

**Comment by notbdu** [comment]
I can't share the file but I can share system info.
Running inside a ubuntu vm on OSX:
`Linux ubuntu-xenial 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Volume mounting from an `ext4` fs on the ubuntu vm host into the STAN docker container.

**Comment by notbdu** [comment]
Does running a script before startup to...
- read through all the records
- check the crc hash
- check for and remove unknown record types
... sound crazy to you?

**Comment by kozlovic** [comment]
@notbdu The problem is how to remove. A record layout is this: 4 bytes for size (1 byte for type, 3 byte for size) then 4 bytes for CRC, then payload. What seem to be happening here, is that the code reading records return no error, but record type is 0 - which should not be the case for subscription records. So after reading at least 8 bytes (all 0), readRecord() will return that the record type is 0, which produce the fatal error. 
It would be great if you could verify this theory and inspect the end of the `subs.dat` file in that directory and check if there are null bytes at the end of the file.
The file is opened in append mode, and we are not doing any seek on that file. If there are extra zeros that the server did not add, even if we were to ignore a record header with all 0, the server would stop the recovery there and any new subscriptions info added after that would be ignored after another recovery.
If there are indeed zeros at the end of the file, we need to find out how they got there and prevent that from happening.

**Comment by notbdu** [comment]
Ah, I see... unfortunately, he doesn't have the file anymore. We'll have to test this theory when it comes up again.

Will let you know. Thanks for the assistance @kozlovic!!

**Comment by kozlovic** [comment]
No problem. If you could get more information on what options are used when creating/mounting the file system and also NATS Streaming configuration in general may help.

**Comment by kozlovic** [comment]
@notbdu Although I don't think that the issue originated from the server, I tried to add code to handle the situation where there are null bytes at the end of the files. If there are null bytes, but less than the expected size of a record header, then I also added code to report the expected number and how many were read. In this case, the server will still fail to start since I cannot say for sure if it is corruption or if it would all have been zero. But you can still use `truncate` or other tools to truncate the file.
See PR #441 for details.

**Comment by notbdu** [comment]
Oh wow, thanks for the quick turnaround with this @kozlovic!

Appreciate the good work on NATS/STAN so far by you and your team.
