### ISSUE TITLE
Playback of messages from date set within message

### ISSUE THREAD

**Issue by vjpr** [nats-io/nats-streaming-server#442]
https://nats.io/documentation/streaming/nats-streaming-intro/:

> Historical message replay by subject...By using this option, message delivery may begin at...A specific date/time in nanoseconds

For **testing**, I would like to load a week of data into NATS. Then I would like to playback data from the last day. NATS message received date would be all about the same time. Is there a way to allow NATS to store the date from inside the message payload?

Also, in **production** the recorded date of my data (say IoT data that is broadcast in batches every hour or so) will be different from the "nats message received" date. So when I want to replay data, I am not able to use NATS to find the correct date of the data to replay.

I am wondering if this use case is something that NATS can support? The alternative is to just write it to a database and implement some code to read data from the date of the message (but then I miss out on the durable subs and rate limiting etc).

I feel like I am looking for a hybrid of NATS (durable subscriptions, rate limiting) + SQL db. But maybe I am looking for a different tool?

**Comment by kozlovic** [comment]
In short, no this is not possible. The NATS Streaming storage was not implemented as a time series DB.
See inline for more details:

> For testing, I would like to load a week of data into NATS. Then I would like to playback data from the last day. NATS message received date would be all about the same time. Is there a way to allow NATS to store the date from inside the message payload?

No, this is not possible. As you said, the message timestamp is set by the server at the time it receives it, and in a bulk send, they may all get same or very close timestamp.

> Also, in production the recorded date of my data (say IoT data that is broadcast in batches every hour or so) will be different from the "nats message received" date. So when I want to replay data, I am not able to use NATS to find the correct date of the data to replay.

That raises the issue of out-of-order timestamps. What if you have a subscription running and a single message is sent at say 10:15am. The subscription receives and processes this message. Then, a batch that was started at 10:00am and had messages sent at 10:00am and one say at 10:20am is sent at 10:30am. So both messages arrive at the server at that time, but if the server were to use the message's own timestamp, the first message in the batch would be older than what your subscriber has already received. 

The server uses a message sequence for ordering, and the sequencing is set by the server when the message is received. For file store, the message log is append only. Delivery is based on sequence, even when you select timestamp: what the server does is find the corresponding starting sequence for the given timestamp. Since timestamp are ordered (in current implementation), this is easy to find the corresponding sequence and have a sequential delivery of all messages past that timestamp/sequence.

We do offer a SQL store implementation now. But even then, the timestamp column is set by the server based on the time the message is received. This timestamp is used for message expiration (channels limits can be count, size or age). Changing this timestamp artificially to a custom value would break the server since there are current assumptions that timestamp of messages in a log are monotonically incrementing.

**Comment by vjpr** [comment]
Thanks for the reply. Much clearer now.

So seems like manually setting timestamps would be a special case for testing only - probably not that useful anyway.

And for any time-based processing, NATS should be used to write to a db, which can then be queried.

Good point about the data ordering. If there is always the potential for a batch to come in later, anything wanting to read time-ordered data must be aware of this and make a judgement call on what to do.
