### ISSUE TITLE
Huge performance difference between empty channel and channel with data

### ISSUE THREAD

**Issue by Kikimora** [nats-io/nats-streaming-server#455]
I use stan-bench.go from examples to send some messages to NATS streaming server and observe performance degradation as I push more and more messages.

I start with fresh channel and can push 130 000 messages per second.
```
go run stan-bench.go -np 1 -ns 1 -n 300000 -ms 60 -a TST.4
Starting benchmark [msgs=300000, msgsize=60, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 260,278 msgs/sec ~ 14.89 MB/sec
 Pub stats: 130,139 msgs/sec ~ 7.45 MB/sec
 Sub stats: 130,305 msgs/sec ~ 7.46 MB/sec
```

Next run demonstrates some performance degradation. This "second run" performance degradation seems to be consistent and does not depend on number of messages. I just run same benchmark two times and first time it is fast, then it became slower.
```
go run stan-bench.go -np 1 -ns 1 -n 300000 -ms 60 -a TST.4
Starting benchmark [msgs=300000, msgsize=60, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 58,714 msgs/sec ~ 3.36 MB/sec
 Pub stats: 52,023 msgs/sec ~ 2.98 MB/sec
 Sub stats: 29,357 msgs/sec ~ 1.68 MB/sec
```

If I change channel then I get good performance back again.
```
go run stan-bench.go -np 1 -ns 1 -n 300000 -ms 60 -a TST.5
Starting benchmark [msgs=300000, msgsize=60, pubs=1, subs=1]
NATS Streaming Pub/Sub stats: 287,041 msgs/sec ~ 16.42 MB/sec
 Pub stats: 143,520 msgs/sec ~ 8.21 MB/sec
 Sub stats: 143,692 msgs/sec ~ 8.22 MB/sec
```

At some point I get this warning ` [60568] 2018/01/11 19:06:08.115596 [INF] STREAM: WARNING: Reached limits for store "TST.4" (msgs=1000000/1000000 bytes=117.29 MB/976.56 MB), dropping old messages to make room for new ones` from NATS server and it looks to have some effect on performance. But I'm yet to conform this.

I wonder if there is a way to always get performance which I get on a first run?

Thanks

**Comment by kozlovic** [comment]
@Kikimora This is because the `stan-bench.go` tool creates the subscription with "DeliverAllAvailable()", which means that the server will deliver to the subscription old messages (the one at the beginning of the log). If you are using FileStore, it means reading back old messages from the log. When you have an empty channel, the recent messages are immediately sent and since we use some caching, we save reads.

So please try to add `-io` (for ignore old) in the command line and your subscription will start with new messages only and you should see a more constant performance.

But yes, when server start to drop messages from the log, it will have an impact in performance, merely by the added work of keeping track/updating the channel's state and sometimes resulting in dropping a file from the channel messages log and create a new one.

**Comment by Kikimora** [comment]
Thanks!
