### ISSUE TITLE
Q: Unlimited channels with no acknowledged messages

### ISSUE THREAD

**Issue by sega-yarkin** [nats-io/nats-streaming-server#514]
Hi! Is it possible to configure NATS Streaming to not storing messages which have been acknowledged by clients?

I have a Queue Group which stores tasks and several workers to handle these tasks. I don't want task to be removed from queue before it has been handled (e.g. when system is overloaded or workers are under maintenance). When I set unlimited numbers messages and unlimited storage space for channels the data directory is continue growing and never delete old slices even if workers have acknowledged all messages.
If there is only one queue group we can set channel limits according to a free disk space (but we cannot increase it on the fly if we add more disks, are we?). But if we have several queue groups, how can we allow one of them to consume 90% of free space for a short time and then allow to do so for another one without any restarts?

**Comment by kozlovic** [comment]
The answer is no. Streaming is not like a regular messaging queuing system where messages are removed once they have been consumed. Messages do stay in the channel regardless of consumer interest or acknowledgment. They are removed only based on limits set globally or at the channel level.

**Comment by sega-yarkin** [comment]
@kozlovic Ohh, thanks for the answer.

**Comment by sega-yarkin** [comment]
@kozlovic Hi! Sorry for a dummy question, but is there a way to know how many messages in channel still haven't consumed by clients? Thank you.

**Comment by kozlovic** [comment]
No, because as I explained, there is no requirement for messages to be consumed. That is, if a publisher publishes on channel `foo`, the server will store those messages even if there is no subscription interest (durable or not) at that time. 

Streaming is a message log, any published message is logged. Then, subscriptions can be started at any time and consume from somewhere in the stream (using starting positions). Messages are not removed when acknowledged by consumers. 

A consumer acknowledging a message simply indicate to the server that that message should not be resent to *this* consumer, but does not mean that it should be removed from the channel.

Now, if the question is: for a given consumer, how do I know if that consumer consumed all avail messages, then this is different. You can use monitoring for that, specifically get the subscription details of a channel and check the subscription's `last_sent` vs the `last_seq` numbers: https://github.com/nats-io/nats-streaming-server#channelsz

**Comment by sega-yarkin** [comment]
The last one is that I was talking about, thank you!
