### ISSUE TITLE
Low performance after raft snapshots

### ISSUE THREAD

**Issue by sega-yarkin** [nats-io/nats-streaming-server#520]
Hi! I'm doing some load testing of master branch and have very strange issue. I have 3-node cluster with limits by the age, which is running in docker containers on my local Linux machine with a lot of CPU cores, memory and fast ssd drive (it shouldn't be a resource issue). After several attempts (each starts from scratch and there was no data from previous one) it looks like issue happens after first raft snapshot. All publishers were working in synchronous mode and there were no errors in logs during the tests.

### Building base image
```sh
$ git clone https://github.com/nats-io/nats-streaming-server.git
$ cd nats-streaming-server
$ git rev-parse --short HEAD
4380598

$ docker container run -it --rm -v ${PWD}:/go/src/github.com/nats-io/nats-streaming-server \
  -e "CGO_ENABLED=0" -e "GOOS=linux" -e "GOARCH=amd64" \
  -w "/go/src/github.com/nats-io/nats-streaming-server" \
  golang:1.9.4 \
  go build -v -a -tags netgo -installsuffix netgo -ldflags "-s -w -X github.com/nats-io/nats-streaming-server/version.GITCOMMIT=`git rev-parse --short HEAD`" -o pkg/linux-amd64/nats-streaming-server
$ cp ./pkg/linux-amd64/nats-streaming-server ./nats-streaming-server
$ wget -q -ODockerfile2 https://raw.githubusercontent.com/nats-io/nats-streaming-docker/master/amd64/Dockerfile
$ docker build -t nats-streaming:beta -f Dockerfile2 .
```

### Data directories
```
$ mkdir srv1 srv2 srv3
```

### Configurations
```
$ cat srv1/nats.conf
port: 4231
http_port: 8231

store: "file"
dir: "/data"
limits {
  max_msgs: 0
  max_bytes: 0
  max_age: "10m"
}
file {
  slice_max_msgs: 0
  slice_max_bytes: 0
  slice_max_age: "1m"
}
cluster {
  host: '10.10.0.100'
  port: 5231
  raft_logging: true
  log_path: "/data"

  routes = [
    nats-route://10.10.0.100:5232
    nats-route://10.10.0.100:5233
  ]
}
```
**NOTE**: ports end with 1, 2 and 3 respectively to node. First node staring with `bootstrap` flag in first time in every attempt.

### Containers
```
$ docker run -it --name nats1 -v ${PWD}/srv1:/data --network=host nats-streaming:beta -c /data/nats.conf
$ docker run -it --name nats2 -v ${PWD}/srv2:/data --network=host nats-streaming:beta -c /data/nats.conf
$ docker run -it --name nats3 -v ${PWD}/srv3:/data --network=host nats-streaming:beta -c /data/nats.conf
```

### Listeners
```
$ for i in `seq 1 3`; do stan-sub -s nats://10.10.0.100:423${i} -id cl${i} --qgroup qgtest -last test & done
```

### First test
```
$ stan-bench -s nats://10.10.0.100:4231 -np 10 -ns 0 -n 100000 -ms 100 test
Pub stats: 5,738 msgs/sec ~ 560.39 KB/sec
$ stan-bench -s nats://10.10.0.100:4231 -np 10 -ns 0 -n 100000 -ms 1000 test
Pub stats: 4,706 msgs/sec ~ 4.49 MB/sec
```

### Second test
```
$ stan-bench -s nats://10.10.0.100:4231 -np 100 -ns 0 -n 1000000 -ms 1000 test
Pub stats: 20,623 msgs/sec ~ 19.67 MB/sec
$ stan-bench -s nats://10.10.0.100:4231 -np 100 -ns 0 -n 1000000 -ms 1000 test
Pub stats: 5,474 msgs/sec ~ 5.22 MB/sec
$ stan-bench -s nats://10.10.0.100:4231 -np 100 -ns 0 -n 1000000 -ms 1000 test
Pub stats: 11,968 msgs/sec ~ 11.41 MB/sec
$ stan-bench -s nats://10.10.0.100:4231 -np 100 -ns 0 -n 1000000 -ms 1000 test
Pub stats: 2,870 msgs/sec ~ 2.74 MB/sec
$ stan-bench -s nats://10.10.0.100:4231 -np 100 -ns 0 -n 1000000 -ms 1000 test
Publisher benchmark-pub-89 can't connect: stan: connect request timeout
```

When the test started there was traffic on local interface about 2Gb/s, but when raft started doing snapshots local traffic dropped to about 200-300Mb/s and very rare went back to the gigabits. After several tries the test couldn't even start. 

After some delay without any load and restarting all nodes, test could start again with 10 publisher, but:
```
$ stan-bench -s nats://10.10.0.100:4231 -np 10 -ns 0 -n 100000 -ms 100 test
Pub stats: 337 msgs/sec ~ 32.99 KB/sec
$ stan-bench -s nats://10.10.0.100:4231 -np 10 -ns 0 -n 100000 -ms 1000 test
Pub stats: 264 msgs/sec ~ 258.75 KB/sec

$ stan-bench -s nats://10.10.0.100:4231 -np 100 -ns 0 -n 1000000 -ms 1000 test
Publisher benchmark-pub-34 can't connect: stan: connect request timeout
```

What am I doing wrong? Thank you!

**Comment by kozlovic** [comment]
Sorry for the delay. I will get back to you as soon as I can. In the meantime, if you could confirm if you subscribing application are running all along or are they restarted between First test/Second test, etc..

Also, it looks like the way you build the image is ok, but have you tried with the 0.9.0 docker image that is now available? Master does not have things that would have an impact in the issue you are describing.

**Comment by kozlovic** [comment]
Just a note that I can reproduce the slow down after snapshot. From the look of it, it comes from the BoltDB store used for raft operations. I need to investigate more.

For the timeout issues: if the clients that create connection (the bench tool) is stopped before normal completion, the logical client connections are left opened in the server. When you restart the tool, since it uses the same client IDs, the server detects them as duplicate and tries to contact the known client HBInbox, to see if they respond. If not, the server replace them with the new client. However, this check used to be done in some go routines but is now done in place, and each test takes 1/2 second. So after processing only 4/5 clients, the remaining ones will start to report timeout and exit, which triggers the issue again. I will make a change to process those duplicate client ID connect request in go routines again to stop that from happening.

**Comment by sega-yarkin** [comment]
I've done the tests for the `latest` container and behavior looks the same as for the `master`.

```sh
$ docker pull nats-streaming
Using default tag: latest
latest: Pulling from library/nats-streaming
Digest: sha256:1ebbddf1a9f896731479e2ee4d47f93c804da1a2b6a6878961914f04dc59d54a
Status: Image is up to date for nats-streaming:latest
```

**Comment by kozlovic** [comment]
Yes, issue is present there too. I have fixed the issue with the timeout on (re)connect (#529). For the performance degradation, still looking into it. You may be able to minimize the effect by increasing the number of trailing logs (at the expense of the raft log getting bigger). The option would be `-cluster_trailing_logs 1000000`, to keep the last 1,000,000 entries.

**Comment by kozlovic** [comment]
@sega-yarkin Thank you for your patience. I have an attempt fix to improve performance after RAFT snapshots. The PR is #543. If you want to test, that would be great, but I understand if you can't or are no longer interested. If you try with the PR, please lower back (or don't explicitly set) the number of trailing logs as I had previously suggest to increase the value as a workaround. Thanks!

**Comment by sega-yarkin** [comment]
@kozlovic Thanks for the fix! I will test it in several days.

**Comment by kozlovic** [comment]
@sega-yarkin Thanks for confirming that performance is improved!

That behavior you describe is normal. Here is what is happening: the publisher sends a message and waits for an ACK from the server. The server (the leader) replicates the message and when it gets an OK from the quorum of servers in the cluster, respond back to the publisher. Since you stop the leader, that "in flight" message can't be ack'ed back to the publisher. The default publisher timeout is 30 seconds, so you would get that error back after that period of time. Let me know if this makes sense.

**Comment by sega-yarkin** [comment]
@kozlovic  But it was like a graceful stop, I didn't kill the process. Why the leader can't wait until new one will be promoted before stop serving clients? It should be seamless for clients, otherwise it will be hard to do things like a rolling upgrades.

**Comment by kozlovic** [comment]
A server can replicate only if it is leader. So it can't be servicing clients and not be leader. 

There is no way for a server to prevent a client from sending a message, or create a connection, subscription, etc... 

For existing connections, you could imagine the server sending to its clients a protocol to indicate that they should wait before attempting any type of send (message, ack, create sub, etc..), wait for all the clients to send another protocol to allow the server to know that it has processed everything that was coming from each of these connections, then close its raft group so another server is elected, then send a signal to the clients that they can now resume. (this would be required since there is no direct TCP connection between clients and server, the fact to actually exit would not trigger a reconnect if the clients were "attached" to the streaming server through a separate NATS server/cluster).

This would still not resolve issues with applications creating new connections when the process above is taking place. They would still experience timeout.

The above sequence seem straight forward, but in practice is not, and would require each client library to support this mode.
