### ISSUE TITLE
Feature request: Automatic ack deadline extend and nack

### ISSUE THREAD

**Issue by riaan53** [nats-io/nats-streaming-server#558]
Hi,

Currently im using google cloud pub/sub as a high available worker queue for long running tasks. They have a nice feature to automatically extend the ack deadline while you are still busy processing the request. This together with a Nack for the task queue will be a great addition to nats streaming. Nack is useful for quick task rescheduling if for example the process is busy terminating and should not attempt to take on any more work.

Regards,
Riaan

**Comment by kozlovic** [comment]
About extending the ack deadline, unfortunately, this is something that can't be done with current design. Streaming server and clients are not directly connected to each other with a TCP connection, so the only way for the server to know if a message is received is by the processing of its ACK.

When a server does not receive an ACK it does not know if the client is just holding onto the message, or if it never received at all, hence the redelivery. The danger is that a temporary connectivity could cause the client to never receive a message and the server would not know that the client did not get it, and the client would not know that the server sent one. In the case of MaxInflight of 1, that would be dramatic because the client would stop receiving any message since the server would have 1 outstanding ACK.

For NAck, what have you exactly in mind? If you imply that the server should redeliver the message right away (instead of waiting for the AckWait), this may not work for what you describe. The server may redeliver right away to that consumer (for sure for plain (durable) subscriptions, and possible for a queue subscription). For the case you describe, I would simply use `ManualAckMode()` instead and simply not ACK the message on exit. If the subscription is durable, that message will be resent on restart of the durable subscription.

**Comment by riaan53** [comment]
Hi @kozlovic ,

Thank you for the response, it makes sense. For this to work it will probably be necessary to have different sets of acks. One for message have been received (like it is now) and one for finished processing with the heartbeat (and early opt out wit a NAck) if still busy. But this will complicate things a bit like you mentioned - I will stick to google pubsub for long duration HA workload distribution and use nats-streaming for low latency reliable messaging. 

Thanks for the awesome open source project.

Regards,
Riaan
