### ISSUE TITLE
Would like to use streaming server as logging like Logstash

### ISSUE THREAD

**Issue by streetlist** [nats-io/nats-streaming-server#585]
Can nats.io streaming server be used like logstash keeping unlimited logs?

**Comment by kozlovic** [comment]
You can set no limit to all or individual channels, but do you have unlimited resources? Think about it, a message log store messages and those messages are not removed just because they are consumed. This is not a typical messaging's queue.

Have a look at [this](https://github.com/nats-io/nats-streaming-server#channels) and specifically the Message Log paragraph that expands on what I just wrote here.

**Comment by unisqu** [comment]
I saw this. Does it mean it's bad use case as a persistent log?
https://dev.to/byronruth/use-cases-for-persistent-logs-with-nats-streaming

**Comment by kozlovic** [comment]
Not at all, but you ask about unlimited limits. I am just stating that if you set to unlimited, messages will never be removed from the log, which means that the file(s) will grow for ever.

**Comment by unisqu** [comment]
Using as persistent logging, are the logs kept using LRU caching or certain mechanism for this?

I'm using it as a write only logging for database (mysql etc) message queue + backup log. I will not clear the log files of course in case my db gets corrupted, i can replay this log. What kind of "gotchas" I have to look out for? I don't want to be caught with surprises.

**Comment by aricart** [comment]
@unisqu the nats-streaming logs are limited by log size (all messages in the file(s)), message age or count - see https://github.com/nats-io/nats-streaming-server#store-limits. If you have it unlimited your machine could run out of resources. In your case, if your DB was down for a long period then the messages could be lost if some of these limits were less than your outage. Also, database systems have a lot of sidecars to implement replication, recovery, and snapshots. If you run snapshots every few hours, not sure why the setting would have to be unlimited, as you should always have a reasonable reset point.

**Comment by kozlovic** [comment]
@unisqu Again, not sure how to explain this differently, but NATS Streaming is not really a message queue broker. Messages are not removed from the log because they are consumed, they are removed IF you set channel limits (and there are by default: 1 million messages or ~1GB of data in a channel). When the channel has reached its limits, the old messages are dropped to leave room for the new messages.

**Comment by unisqu** [comment]
@kozlovic ok. i'm wondering if the messages are persisting to disk or partially stored in memory if i configure it as unlimited everything that's all. i expect the log to be >100GB eventually.

**Comment by kozlovic** [comment]
If you use SQL or FILE store, then yes, messages are persisted and very little is maintained in memory.
