### ISSUE TITLE
MySQL server configured to utf8mb4 fail to load provided sql

### ISSUE THREAD

**Issue by powerman** [nats-io/nats-streaming-server#596]
When MySQL is configured to have full Unicode support (`--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci`) it restriction "max key length is 767 bytes" result in lowering maximum length of index in chars from 767/3=255 to 767/4=191. Because of this it fail to load provided sql file:
```
mysql> CREATE TABLE IF NOT EXISTS Clients (id VARCHAR(1024), hbinbox TEXT, PRIMARY KEY (id(256)));
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```
The fix is to either change it to `…PRIMARY KEY (id(191))…` or add options to CREATE TABLE to explicitly set charset to utf8 instead of utf8mb4.

**Comment by kozlovic** [comment]
Not sure if this is a good idea since for instance for Clients, we only support alphanumeric and `_` or `-`. The other would be for channel name, which again, I would not recommend using anything but ASCII.

That being said, the provided sql file is just to help some users quickly setup the database, but it is possible (and probably recommended) that a DB admin tune that for better performance or adapt to fit the user's requirements.

(ps: I am not able to reproduce, in that if I create the database with this charset, then I have no problem creating the table with the existing command. Would you have step to reproduce?)

**Comment by powerman** [comment]
Sure, you need to ensure these settings will be used by default, e.g.:
```
$ docker run -d --restart=always --name mysql -p 53306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -v mysql56:/var/lib/mysql mysql:5.6 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
$ mysql -u root -h 127.0.0.1 -P 53306
mysql> create database nss_tmp;
Query OK, 1 row affected (0.00 sec)

mysql> use nss_tmp;
Database changed
mysql> CREATE TABLE IF NOT EXISTS Clients (id VARCHAR(1024), hbinbox TEXT, PRIMARY KEY (id(256)));
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

**Comment by kozlovic** [comment]
Repeat your steps with mysql:5.7 (which happens to be the one I have installed from homebrew) and you will see that the problem does not exist anymore.

So the fact that this issue does not occur with a more recent version of MySQL than the one you use and the fact that the provided SQL command file is for illustration only, I will not make the change at this time. Thank you.
