### ISSUE TITLE
How can I monitor the msgs are sent or not?

### ISSUE THREAD

**Issue by wjzhangcsu** [nats-io/nats-streaming-server#597]
Is there a way to see the messages is sent or not? How can I find the messages are lost or not?

**Comment by aricart** [comment]
@wjzhangcsu there's no notion of messages sent or not. However, if you publish a message you can find out if the message was received by the server. If received by the server then any subscriber that has expressed interest on that channel will get the message. The message will persist on the server until the expiration policy for the channel (server configuration).

For example the node-nats-streaming client gets called in the callback with nil, and a guid if the server accepted the message:
```
 stan.publish('foo', 'Hello node-nats-streaming!', function(err, guid){
    if(err) {
      console.log('publish failed: ' + err);
    } else {
      console.log('published message with guid: ' + guid);
    }
  });
```

If you want to know that a client specifically got a message or not, what you want to do is publish a 'request' message using regular NATS. The client would have to be coded to subscribe and respond to the reply subject as necessary.  Note that nats-streaming-server doesn't support request reply because the nats-streaming-server is simply recording messages to a log. The streaming client may be receiving the message now, or in a year depending on how long that message channel lives. So replying to that message would be missing the correct time context and/or the client that published the message could be long gone.

You could implement a similar strategy of having your streaming subscriber publish a message to a different channel where some other component then processes it. The observation here would be that if you are doing that, likely you don't need nats-streaming in the middle and can simply implement your application using NATS.

**Comment by kozlovic** [comment]
Could you clarify what you mean by "How can I find the messages are lost or not?" Are you referring to when messages are published or if messages are not consumed?
The publisher and subscriber are decoupled, that is, when the publisher receives a confirmation from the server, the confirmation is just to say that the message was persisted, not that it has been sent and/or processed by a consumer.
More over, due to channel limits (you could set to unlimited if you have unlimited resources), older messages may be dropped and in that case, it is possible that a message was successfully published, but end-up being dropped before it had a chance to be sent to a subscription.

I would recommend that you check this whole [chapter](https://github.com/nats-io/nats-streaming-server#channels) for more information. Thanks!
