### ISSUE TITLE
Is there a "persistent" or connection pooling thing for nats-streaming-server?

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#609]
I'm very used to connection pooling with redis etc e.g.
https://stackoverflow.com/questions/24387350/re-using-redigo-connection-instead-of-recreating-it-every-time

What's the equivalent? I'm having 1ms per connection using

            sc, err := stan.Connect( 

everytime i need to connect, which is not very efficient. I googled but couldnt really find anything useful. Appreciate any help or example code in repo. Thanks.

**Comment by ripienaar** [comment]
you can share a connection across go routines - but beware on connection error you have to recreate the connection and all subs yourself

**Comment by unisqu** [comment]
that's why i'm asking for an industrial standard production ready example code

**Comment by unisqu** [comment]
Someone with a connection pool specifically designed for nats.io can share the golang code? Thanks

**Comment by wallyqs** [comment]
you wouldn't need a connection pool since after connect there would be a single persistent connection. The client will automatically reconnect too if it gets disconnected so no need to call Connect again on the underlying NATS client.

**Comment by wallyqs** [comment]
Closing this one since related to the clients (https://github.com/nats-io/go-nats-streaming || https://github.com/nats-io/go-nats), btw @unisqu there is a Slack channel where can raise questions as well https://join.slack.com/t/natsio/shared_invite/enQtMzE2NDkxNDI2NTE1LTc5ZDEzYTkwYWZkYWQ5YjY1MzBjMWZmYzA5OGQxMzlkMGQzMjYxNGM3MWYxMjNiYmNjNzIwMTVjMWE2ZDgxZGM
