### ISSUE TITLE
Feature request - Publish time input

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#616]
e.g. Publish("Message", timestamp)

in the event that message can be slot in between messages too. This is highly useful in an ACK sequencing where some messages failed to deliver on time.

**Comment by kozlovic** [comment]
This is clearly not something we would do with NATS Streaming. Events are immutable (and so is their order in the message log). It would be impossible to insert a message in the log. Reordering them after recovery (if not ordered in message log) would also be problematic since "older" messages (in the log) may be dropped due to channel limits.
More over, timestamp is assigned by server. Having clients deciding on the timestamp would be problematic due to clock differences between clients and server.
