### ISSUE TITLE
Any alternatives for nats streaming server as a pub/sub log? Benchmark please?

### ISSUE THREAD

**Issue by streetlist** [nats-io/nats-streaming-server#633]
Any alternatives for nats streaming server as a pub/sub log? Benchmark please?

I like nats streaming server a lot. But it's rather slow (compared with persistent rabbitmq).

I'm looking for alternatives for nats streaming server as a pub/sub logging (persistence). Or benchmark for comparison. Basically I'm asking whether the developers of nats.io streaming server think that there's potential to make this logging / persistence faster in future so I can use other alternatives first and wait for the speed upgrades.

Great work. Please keep it up. Thanks.

**Comment by kozlovic** [comment]
Since you say that NATS Streaming is rather slow compared to RabbutMq, it means that you have been running some benchmarks, which is the right thing to do since you can tailor the tests to your environment and expected message flow.

Would you mind sharing the NATS Streaming server configuration you used for that and the client benchmark tool (if not using stan-bench, or if you are, what was the command line parameters used?).

Few things to note about the publish benchmarks
- Using `-a` in stan-bench which causes the tool to use asynchronous publish as opposed to synchronous publish will dramatically improve the performance.
- For the receiving side, and if you use a persistent store, keep in mind that if you keep sending more messages at every run but run the subscriber at the same time, if you have configure the subscriber to get "all" messages, the server will append new messages to the end of the log, but will have to read from the beginning to deliver to the subscribers. You can use `-io` for ignore old, or "new only" starting position). Alternatively, clean the store before the next run.
- Sending more than the channel limits allow will cause older messages to be discarded when new messages are accepted. This is putting more burden on the server.

**Comment by kozlovic** [comment]
Closing for now. Let me know if you have more info.
