### ISSUE TITLE
Clarification on durable queues destruction

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#659]
Hi there!
So I'm currently trying to work with durable queues, but I am having trouble understanding their destruction mechanism:
> Note: For a durable queue subscription, the last member to * unsubscribe * (not simply close) causes the group to be removed from the server.
Suppose that one day I have clients a, b, & c open w/ the same durable queue subscription to topic x. They are consuming just fine, and all of a sudden I close them all w/o unsubscribing. A day later, I publish a new message to topic x _and then_ open a new client, d, and subscribe to the same durable queue. Would the queue have survived? What if I then unsubscribe & close client d? And if clients a, b, & c where never, ever coming back to unsubscribe properly?

**Comment by kozlovic** [comment]
> A day later, I publish a new message to topic x and then open a new client, d, and subscribe to the same durable queue. Would the queue have survived? 

Yes, if you did not call Unsubscribe() when the last queue member exited, then the server would keep the durable queue subscription.

> What if I then unsubscribe & close client d? 

As described in the doc, since there is no specific API to create or destroy a queue group, the way it works is that the *last* member to leave the group will dictate if the group is maintained or removed. If the last member leaving calls Unsubscribe() then the group is removed. In other words, when the server receives an Unsubscribe request, if at that time there is no more member, then the group is removed. If it is a Close request and there is no more member, the group is maintained.

> And if clients a, b, & c where never, ever coming back to unsubscribe properly?

Again, the server needs 1 unsubscribe request to actually remove the group (if the server sees that there is currently only one active member that is sending the Unsubscribe request, then the group is removed).

Let me know if this is still not clear.

**Comment by juandiegopalomino** [comment]
@kozlovic ah, I see it's _if there are no other live connections_ -- that's what is meant by "last". If that's the case, then this makes sense, and thank you so much for the clarification!

**Comment by kozlovic** [comment]
Well, not connections really. Think of it this way. Suppose that you have 4 members (m1, m2, m3 and m4) of the same group, does not matter if they are from same or different connections. Here are possible sequences of them closing:
```
m2.Close() -> group still opened with m1, m3 and m4 members active
m1.Unsubscribe() -> this will be consider a simple close because there are still m3 and m4 members active
m4.Close() -> group still opened with m3 active.
```
Now the action of m3 in this situation will make the difference. If we have
```
m3.Close() -> group is maintained (if this is a durable group).
Group will be resumed next time that a subscription with same
channel name and queue name is started. Delivery will start at
the last sent + all unacknowledged messages.
```
If however you this happens
```
m3.Unsubscribe() -> group is removed (durable group or not,
this is the last of it). No state will be maintained. If a subscription
is created after that with same channel name and queue name,
a new group is created starting delivery at the given start position
when the new subscription is started.
