### ISSUE TITLE
How to handle slow consumers?

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#661]
Hi again!

My colleagues and I where reading about the slow consumer cautions for the NATS platform (https://nats.io/documentation/managing_the_server/slow_consumers/) and saw that the first solution listed is to use nats streaming. At first we thought that the persistent storage and sequencing solved the client message buffering issue, but apparently the go and python3 clients still have max pending messages per subscriber. This fields makes it look like slow consumers would still have messages dropped off or subscriptions terminated in nats streaming as well, which is a bit confusing.

This realization also led to worrying about the following scenario: suppose that topic x has 100K (far bigger than the pending limit described in https://github.com/nats-io/asyncio-nats-streaming/blob/73342063433a738226994ab5bd58b118def720e9/stan/aio/client.py#L41) tiny messages published to it. We now want to create a queue with a very simple subscriber to consume from topic x, but from the very beginning (e.g. all 100K messages). Would this consumer immediately fail because it has way more messages to handle than its pending limit.

Any clarification would be really appreciated!

**Comment by kozlovic** [comment]
I am of the opinion that the streaming client libraries that create internal subscriptions to receive streaming messages should be setting the limits to unlimited, but regardless, even if messages would be dropped from the subscription's internal queue, server will resend them.

If there is a channel with 100,000 messages and you create a subscription, the pending limit that you are talking about is for low level NATS Subscription. By default, the Streaming subscription will be created with a MaxInflight if 1024 messages, which means that the server will stop sending until it gets acknowledgment back so that its view of the number of outstanding message for this subscription is below the MaxInflight.

**Comment by juandiegopalomino** [comment]
@kozlovic cool, so because the MaxInflight number is lower than the pending limits of the nats platform, the nats platform will never think it is over its limits?

**Comment by kozlovic** [comment]
Yes, but the pending limit that you are talking about also does not mean that this is the max number of message that can be received, instead it means that it is the max number that the library will accumulate should the user callback not return fast enough compared to the rate of incoming messages.

**Comment by juandiegopalomino** [comment]
That makes sense, ty
