### ISSUE TITLE
Does not connect to the cluster.

### ISSUE THREAD

**Issue by dzen-it** [nats-io/nats-streaming-server#667]
I'm try to connect to cluster of streaming server with the configurations on the different hardware nodes:

Node-1:
```
port: 4222
net: '0.0.0.0'

cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://node2.example:6222"]
}

# NATS Streaming specific configuration
streaming {
  id: testcluster
  store: file
  dir: /opt/nats/testcluster/
  cluster {
    log_path: /opt/nats
    node_id: "a"
    peers: ["b"]
  }
}
```

Node-2:
```
port: 4222
net: '0.0.0.0'

cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://node1.example:6222"]
}

# NATS Streaming specific configuration
streaming {
  id: testcluster
  store: file
  dir: /opt/nats/testcluster/
  cluster {
    log_path: /opt/nats
    node_id: "b"
    peers: ["a"]
  }
}
```

Using the Go library I'm try connect by 4222 port with correctly cluster ID and always get the error "stan: connect request timeout". 
In single mode without a section "cluster" in the "streaming" all okay.
What am I doing wrong?

**Comment by kozlovic** [comment]
Please make sure that you see one of the two servers being elected. From above configuration I assume that the `/opt/nats` directories are local to each node. If they are shared then this is a misconfiguration since each process will try to write its own data in the same files. So again, if the location is shared, you should change above configuration to ensure that `dir` and `log_path` specify a unique location for node 1 and 2.
If everything is fine, then one of the two nodes should be elected leader and you should see something similar to:
```
[94260] 2018/10/08 10:00:53.190242 [INF] STREAM: server became leader, performing leader promotion actions
[94260] 2018/10/08 10:00:53.191382 [INF] STREAM: finished leader promotion actions
```
Once that is checked, please let us know what client library you are using and excerpt on how the connection is created and error you get. Thanks!

**Comment by dzen-it** [comment]
@kozlovic thank you very much for the example of a working cluster log it's very useful.

The problem turned out to be that I changed the `node_id` several times on one of the nodes.
After restarting the streaming server, the string of log `STREAM: Cluster Node ID:` did not change and the cluster did not work.

The solution was to clean the directory `dir` and restarting the streaming server.
