### ISSUE TITLE
Should we flush subscription stores are regular interval?

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-streaming-server#683]
Processing of ACKs does not result in flush of store (for performance reasons). Should we at least flush from time to time?

**Comment by nginxsantos** [comment]
Hi @kozlovic - Kindly advice what is the plan of implementing this enhancement. To me (also as per discussion the google group) it seems even after getting the ACK,  it stays until max age/max count or max size thresholds. 

Also, I have a question - when the max size thresholds is reached, does it first remove those entries for which the ACK was received ?

**Comment by funkyboy** [comment]
@kozlovic AFAIU there's no way to configure the server so that a message is removed after it has been consumed by one client.

Is there an API, even client-side, that allows implementing this?
"This" as in `I am a client, I just finished consuming this message, now I am gonna tell the server to delete it from the channel, so that the very same message is not consumed by another client`.

Context: I have a use case in mind and I am trying to understand if NATS streaming server offers a good solution for it.

**Comment by kozlovic** [comment]
@funkyboy See this [comment](https://github.com/nats-io/nats-streaming-server/issues/683#issuecomment-452032509). No you can't remove a message simply because it is consumed by one consumer. This is not a traditional message queue. The explanation is given in the referenced comment.

**Comment by funkyboy** [comment]
@kozlovic thanks. Was looking for some advice along the lines of "if you are looking for a queue system, NATS is not a good fit". Now I found them :)
I was a bit misled by the fact that NATS is listed here: http://queues.io/#nats

**Comment by kozlovic** [comment]
Note that JetStream will provide a workqueue semantic that will allow you to remove the message from the store when it is ack'ed. Closing this issue now.
