### ISSUE TITLE
[Question ] Clustering Vs Partitioning

### ISSUE THREAD

**Issue by maheshmahadevan** [nats-io/nats-streaming-server#684]
Hi, I have read the documentation on both Clustering and Partitioning using Nats Streaming , and it leaves me sort of confused as to when to use which configuration. I understand per documentation that Partitioning and Clustering cannot be used together , so If I start a cluster with 3 servers , with 1 being the leader , are all the subscriptions and channels routed only to the leader whereas the other 2 servers remain in standby ??
Requesting someone to clarify and if required update the documentation.

Thanks,

**Comment by kozlovic** [comment]
As described in the doc, the Partitioning feature is incompatible with Clustering.

In clustering mode, each server replicates the set of data, but there is only one leader as you say. Still, the others are not standby in that they actively replicate data. If the leader goes away, another in the cluster will take the role of leader (assuming there is quorum). Clustering requires that all channels are known by the cluster, which is opposite of Channel Partitioning.

Now you *could* have different clusters (different cluster IDs) that would handle different channels, but that would not be enforced as it is with Channel Partitioning. Applications pointing to a cluster would be expected to only deal with a subset of all your channels, etc..

If you want to use Channel Partitioning, but don't want the single point of failure, you can use Fault Tolerance (FT) and Partitioning, that is groups of FT servers, each having a set of channels that they handle. The FT setup, however, require that servers in the same group share the datastore, since in this case, only 1 server is active while the others are in standby, and access the datastore only on failure of the active server.

**Comment by maheshmahadevan** [comment]
@kozlovic Thanks for the reply. But i still have few questions , i am trying to clarify my thoughts here below.  Sorry for a long post.

Since I am comparing NATS streaming with Kafka architecture , I still have certain questions pertaining around optimum usage of resources in Clustering mode.
As you mentioned , In clustering , the non-leading servers actively replicate data , but do they also share the producer / subscriber load , I assume they do not , but I might be wrong as documentation is not clear on this part. If that is case , the non-leading clusters act no different than a standby server which can assume the role of the leader when leader goes down.

Whereas , when it comes to using partitioning along with Fault tolerance , I can  similar non-optimum usage of resources when it comes Standby servers , even though we can argue this is sort of similar to Mirroring concept in other frameworks. 

My confusion still remains , since from the documentation it is unclear how FT , Clustering and Partitioning these different concepts but not very clear how they come together ( or do not come together ) , for example , is it useful to have a FT with Clustering ? If yes , in what scenario.

Also, I was unable  to identify from documentation, the best way to bring up Nats Streaming cluster along with NATS server , is it recommended to also have a NATS cluster with NATS Streaming cluster on top of it , what are pros and cons of such an approach , does it increase the mem/cpu footprint ? I see there are examples but no details on what approach might be suitable for different scenarios.

**Comment by kozlovic** [comment]
> As you mentioned , In clustering , the non-leading servers actively replicate data , but do they also share the producer / subscriber load , I assume they do not , but I might be wrong as documentation is not clear on this part.

Correct. The followers replicate data but do not send data to consumers, the leader does.

> If that is case , the non-leading clusters act no different than a standby server which can assume the role of the leader when leader goes down.

The huge difference is that in FT the standby servers are completely passive and rely on a shared state, that is, you need to have a SAN or NFS so that the single store is available to all servers in the group. With clustering, they have their own storage. For some users, this is a requirement.

> From the documentation it is unclear how FT and Clustering come together ( or do not come together ) , for example , is it useful to have a FT with Clustering ? If yes , in what scenario.

They don't go together. It is either one or the other. That is, a group of FT servers, or a group of servers running in Clustering mode.

> Also, I was unable to identify from documentation, the best way to bring up Nats Streaming cluster along with NATS server , is it recommended to also have a NATS cluster with NATS Streaming cluster on top of it , what are pros and cons of such an approach , does it increase the mem/cpu footprint ? I see there are examples but no details on what approach might be suitable for different scenarios.

Depends the need of the user. If user has already in place a NATS cluster and want to make use of it for Streaming, then NATS Streaming could sit atop. If it is a brand new deployment and user does not have a need for core NATS, then it could be setup with NATS Streaming alone (keep in mind that Streaming embeds a NATS server, so really it is about the same).

You could even have a setup with simply 2 NATS servers for "fault tolerance" and then a cluster of say 3 or 5 NATS Streaming servers pointing to this cluster. That is, you don't need to have a NATS Server per streaming server.

**Comment by maheshmahadevan** [comment]
Thanks for the elaborate reply.  I believe this is my follow up and last question.
Can you suggest if there is really a time lag when switching from Active to Failover server during the FT mode and also do clients require to reconnect to Failover server or does this happen transparently ?

**Comment by maheshmahadevan** [comment]
@kozlovic Appreciate your time and replies.
