### ISSUE TITLE
[Question] Load distribution in cluster

### ISSUE THREAD

**Issue by Ketharan** [nats-io/nats-streaming-server#688]
While going through the issue #684 I have found that the subscriber/publisher load will not be shared between the cluster nodes; they only replicate the data and leader manages the load. If that so I can not understand how the clustering provides increased throughput or not at all. 
Does that mean compared to fault tolerance, we can say fault tolerance remove the single point of failure of nats streaming node and clustering remove the single point of failure of both nats streaming node and message store?
If that is the case, is the performance (throughput) of a 3 node cluster and 5 node cluster same?

Thanks.

**Comment by kozlovic** [comment]
Both FT and Clustering are for high availability, not scalability. In both FT and Clustering, only the leader sends messages to consumers.

The main difference between FT and Clustering is that FT requires a shared storage and assume that the shared file system honors distributed file locks. Clustering does storage in each node, so one does not have to setup a shared storage.

In theory, the performance of a 5 nodes cluster may be slower than the one of a 3 nodes cluster because data is replicated to 5 nodes instead of 3 and so there is a "longer" wait of acknowledgment of persistence from a bigger cluster.

**Comment by Ketharan** [comment]
Sorry for the late. Thanks for the clarification. But does that mean, currently nats-streaming does not has an in built method for scaling?

**Comment by kozlovic** [comment]
@Ketharan You can always have several clusters that handle different sets of channels, but otherwise as stated before, the clustering implementation as it stands right now is for HA really.
