### ISSUE TITLE
Long time to establish connection

### ISSUE THREAD

**Issue by ramasa** [nats-io/nats-streaming-server#698]
Using below fault tolerance setup in two different server, using version 0.11.2
```
nats 1 - nats-streaming-server -m 8222 -p 4222 --store file --dir /data -ft_group "ft" -cluster nats://ip1:5222 -cid c1 -routes nats://ip2:5222 --user nats --pass secret

nats 2 - nats-streaming-server -m 8222 -p 4222 --store file --dir /data -ft_group "ft" -cluster nats://ip2:5222 -cid c1 -routes nats://ip1:5222 --user nats --pass secret
```
And below java code to connect
```
        @Bean
        Connection cn() throws IOException, InterruptedException {
                log.info("Starting nats connection---------------");
                 String urls[] = env.getRequiredProperty("nats.url").split(",");
                io.nats.client.Options options = new io.nats.client.Options.Builder().maxReconnects(-1)
                                .reconnectWait(Duration.ofSeconds(2)).servers(urls).build();
                Connection cn = Nats.connect(options);
                log.info("nats connection done-------------------");
                return cn;
        }

        @Bean
        StreamingConnection sc(Connection cn) throws IOException, InterruptedException {
                log.info("Starting nats stream connection---------------");
                Options streamingOptions = new Options.Builder().natsConn(cn).build();
                StreamingConnection stream = NatsStreaming.connect(env.getRequiredProperty("nats.cluster"),
                                "Y_" + UUID.randomUUID().toString().replaceAll("-", "").trim(), streamingOptions);
                log.info("nats stream connection done-------------------");
                return stream;
        }

```
Below is our application log, **it takes around 2 minutes to establish connection**
```
2018-11-23 09:50:08.803 DEBUG 18980 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'cn'
2018-11-23 09:50:08.805  INFO 18980 --- [           main] com.example.NatsTest.AppConfig           : Starting nats connection---------------
2018-11-23 09:51:21.749  INFO 18980 --- [           main] com.example.NatsTest.AppConfig           : nats connection done-------------------
2018-11-23 09:51:21.752  INFO 18980 --- [           main] com.example.NatsTest.AppConfig           : Starting nats stream connection---------------
2018-11-23 09:52:03.377  INFO 18980 --- [           main] com.example.NatsTest.AppConfig           : nats stream connection done-------------------
2018-11-23 09:52:03.380 DEBUG 1898
```
Nothing on the nats-streaming-server log during connection

**Comment by kozlovic** [comment]
@ramasa This is really suspicious since even connection to bare NATS takes very long time. There may be some issue with your network here.

Can you print the URL you are actually using in your logs? Also, you could restart the streaming servers with the `-DV -SDV` to have full debug/trace logging for both NATS and NATS Streaming components.

I don't think this would be relevant to the long connection time, but in FT mode, the store needs to be shared, that means that `/data` here on each of your host need to point to the same shared directory.

Something you could try too, since NATS connection takes so long, is to do a telnet (using the same URL that your application is using - the one that you would print in your log) to one of the servers from the machine where your application is running.

**Comment by kozlovic** [comment]
@ramasa Since you saw that there is no network traffic, we need to figure out if this is the library not connecting (and doing what then?) or something else. I would first try to pass the IPs that you used for telnet to your app config (instead of a hostname if this is what you were doing). Could be a name resolution issue?
If that still fails (and there is verified no traffic for a minute or so before you start to see CONNECT, then try to get stack dump of your app to see what it is doing (that will include the nats library and may help pin point where in the code we are).
Make sure also there is no rules in your network that somehow would prevent proper flow of traffic between your app and the servers.

**Comment by spramothkumar** [comment]
Tried to debug this issue and found line number 140 in NatsConnection.class take to long while establishing the connection
    `this.nuid = new NUID();`

**Comment by ripienaar** [comment]
Do you mind sharing how you profiled the code to get to this? And how long it takes?

**Comment by spramothkumar** [comment]
Used [Remote debugging ](https://javapapers.com/core-java/java-remote-debug-with-eclipse/) to profile the code and its take 100 to 120 sec in this single line.

**Comment by ramasa** [comment]
More than 100 seconds for `new NUID()` in aws, but fast in laptop/local
```
    	        System.out.println(new Date());
		io.nats.client.NUID id= new io.nats.client.NUID();
		System.out.println(new Date()+" -"+ id.toString());
```

```
ubuntu@m1:~$ java -jar dis.jar
Thu Dec 06 07:38:39 UTC 2018
Thu Dec 06 07:40:19 UTC 2018 -io.nats.client.NUID@3a71f4dd
```

**Comment by ramasa** [comment]
Thanks @ColinSullivan1 , JVM arg fixed the issue.
