### ISSUE TITLE
Durable subscription application resiliency

### ISSUE THREAD

**Issue by vramanx** [nats-io/nats-streaming-server#705]
I need to enable resiliency for durable subscriptions from my application which runs on multiple nodes. If the application dies on one node, I want another node to resume processing messages automatically from that point. The documentation says that if one client crashes without closing and another one later connects with same client id, then it will work. But detection of crash and resuming on another node is left up to the application. 

Queue Groups enable a groups of consumers. But order is not guaranteed. Is it possible to have a consumer group where one consumer is picked by NATS and on close/failure of that consumer, another one is picked from the group?

**Comment by kozlovic** [comment]
For first part, yes, if you were to restart your durable with same clientID/durable after the first app crashed the server would try to get a response back from first app and since it would not get it, accept the new connection with same clientID/durable (replace old) and continue there. But yes, server won't start a new durable app on a different node for you ;-)

For second part, no, there is no such feature where by a queue group would use exclusively a single member until it fails before picking another.

**Comment by kozlovic** [comment]
Closing this and keeping #793 opened for tracking.
