### ISSUE TITLE
feature: support for multi clients subcribe topic by master/ backup mode ?

### ISSUE THREAD

**Issue by rfyiamcool** [nats-io/nats-streaming-server#710]
example: client1, client2 ,client3. I need the following effects.
When multiple clients subscribe a topic by queueScribe mode，Only client1 can receive msg, other clients are sleep, backup mode. When client1 is down, one of other clients can receive msg.

Nats have a plan to do this?  Or can you tell me what to do.

thank you ~~~

**Comment by kozlovic** [comment]
There is currently no support for that. I would argue why using queueSubscribe() if you want a single instance receiving messages? You could use a durable subscription (not a queue) that server guarantees that there is only one for the same client ID and durable name. 

You could use NATS to heartbeat between your clients and when detecting that currently active is not sending heartbeats, any of the other clients could try to create connection and durable. Only one will be accepted by the server. Note that I would not recommend blinding attempting to connect/resume durable too often since this would affect server, hence the idea to use some kind of HB to at least minimize the attempts.

**Comment by rfyiamcool** [comment]
@kozlovic   thank you

**Comment by carsonoid** [comment]
For what it's worth. NSQ supports this feature natively with it's [channels](https://nsq.io/overview/design.html#design). 

I'm not saying NATS needs this feature, but it's not without precedent.

**Comment by kozlovic** [comment]
@carsonoid Not saying that this is unprecedented. I have actually worked on a closed-source message broker that had this feature ;-)

However, I have read the link you posted and I can't find in there the feature the original poster asked about. NATS Streaming already has queue subscriptions (server sending "randomly" a message to one of the member of the group). What the poster wants is start a queue group but have the server pick exclusively a member to deliver all messages to, until that member fails (crashes, exit, etc..), in which case the server would pick another member from the group and start (re)delivering all messages to this member, etc..

**Comment by carsonoid** [comment]
Ah good point. 👍  I was thinking that the poster just wanted to send all messages to every member. I misread the original post. Sorry to resurrect a dead thread btw.

**Comment by kozlovic** [comment]
@carsonoid No worry!
