### ISSUE TITLE
Ability to manually parse message files

### ISSUE THREAD

**Issue by feribg** [nats-io/nats-streaming-server#719]
I was wondering if there's a straightforward way to manually parse message files, mainly for archival. For instance when rotating out old messages one might want to read them directly and export the data to another system, instead of having to subscribe to big chunks of data and putting load on the server. This is easily achieved with the SQL stores, but the file layout doesn't seem to be well documented. Any directions here?

**Comment by nginxsantos** [comment]
I am also looking for this information. Any help on this would be useful.

**Comment by kozlovic** [comment]
@feribg @nginxsantos As @ripienaar suggested, you could look at the tool. Otherwise, if you just want to decode the message data files, the format is pretty simple. The first 4 bytes of the file are used for the file version. You can disregard if you know that you are parsing a NATS Streaming file store data file.
A given record layout is as follows (see [here](https://github.com/nats-io/nats-streaming-server/blob/79944fa0744c3e3d9a2dfe8c9c0f316f96fc1abd/stores/filestore.go#L730)):
- 8 bytes for record header: (4 bytes for the size of the record, 4 bytes for crc32). Since this is a message, the 4 first bytes are really the size (for other type of records, the first byte indicates the type of record).
- Marshall'ed pb.MsgProto. This is a byte array which length is stored in the first 4 of the 8 previous bytes.
Once you read the bytes, to reconstruct the message:
```
msg = &pb.MsgProto{}
err = msg.Unmarshal(byteArray)
```
