### ISSUE TITLE
Ways to remove acked messages

### ISSUE THREAD

**Issue by vtolstov** [nats-io/nats-streaming-server#721]
Im newbie with nats streaming and i know that messages deleted only when number of it above limit.
If im use sql storage, can i safely remove acked messages after some time?

**Comment by kozlovic** [comment]
No you should not! A stream is supposed to have consecutive message sequence numbers. Only the older messages are removed due to limits. If you do remove random messages (in the sense of creating holes), message delivery may stall.

**Comment by vtolstov** [comment]
So how to do housekeeping in this case? 
I know that events is small, but have trillions of events not very good =) and if some service don't want to receive all events i think that it can panic =)

**Comment by kozlovic** [comment]
This is how streaming works. A stream is a message log of events that are appended, regardless of subscription interest. Consuming a message does not remove it since server needs the message for a future consumer that could start later and decide to replay those messages.
Limits can be set per channel (or globally) which removes old messages: https://github.com/nats-io/nats-streaming-server#store-limits

**Comment by vtolstov** [comment]
ok, older messages removed in sequence? How can i monitor fact that queue overflow and older messages removed?

**Comment by kozlovic** [comment]
Yes, older messages are removed in sequence until the state falls below the given limits. There is a message log when a channel first reaches the limit and server start to discard old messages, but the log statement is printed only once otherwise it would end-up flooding the log since when a limit is reached (if it is number of message specifically) it is likely that any new message will trigger the removal of an old message.

You could also use [monitoring](https://github.com/nats-io/nats-streaming-server#monitoring) to track usage of a channel and see if it has reached its limit.

**Comment by vtolstov** [comment]
do you have plans to add ability to purge old messages (acked and not acked) ?

**Comment by ripienaar** [comment]
As you saw above, you can set age, size and max messages limits today already
