### ISSUE TITLE
Durability: After connection of two subscribers with same queue group only one subscriber gets messages

### ISSUE THREAD

**Issue by vasicvuk** [nats-io/nats-streaming-server#725]
There is a sender A and two subscribers with same queue group.

Subscribers are getting messages in round-robin way.

Two subscribers disconnects. Sender sends 100 messages.

Two subscribers connect again but only one of the subscriber gets all 100 messages. After this 100 messages round-robin works again.

Is there a way to make queue group with durable messages?

**Comment by kozlovic** [comment]
This is expected. When you start a consumer, the server will deliver up to MaxInflight messages to that consumer.

**Comment by kozlovic** [comment]
They are delivered to any queue subscriber when they are running. When you restart the first member, the server will have a list of 1 and send available message to that single consumer. If you have a MaxInflight of 1 and sleep in the callback and quickly start the second subscriber, you will see that the server can then send to the second one.
(also make sure that consumers are ack'ing messages otherwise server will pick consumer with least outstanding acks).

**Comment by vasicvuk** [comment]
I am starting consumer in the same time. (Diffence maybe half a second). Also i have Thread.Sleep(50); in each consumer message listener but still only one is getting message. I will try to put larger Thread Sleep like 1 second or so. 

The thing i see as the problem is that if i have 4 replicas of my service only one will handle all of the load which is not case with RabbitMQ or ActiveMQ (they guarantee round robin delivery to subscribed consumers)

Also why messages are sent to only one consumer after the durable messages are received ?

This happens when MaxInflight is 1, but when there is no unsent messages to consumer round robin works fine? 

For example if i have one sender and the first time both are subscribed round robin works normal.

Only after durable messages are received its starting working like this. This seems so strange when there is no one way of working for both scenarios.

**Comment by kozlovic** [comment]
Can you provide a complete test case to reproduce this issue?
As I described before, the expected behavior is that messages are distributed to the consumer with the least number of outstanding acks. If you have 2 queue subs (on the same group) and they both acknowledge messages then you should see a normal distribution. If all members are stopped, then when you restart the first member, it may get all pending messages since server at that time will have a single consumer in its list. But as soon as the second member is registered, round-robin distribution will resume. With a sleep and MaxInflight of 1, you should have seen that. I have tested with the Go client and it works fine. Hence wanted to see your code and see what you are doing differently.

**Comment by vasicvuk** [comment]
I created a repository that uses C# nats streaming client to reproduce this issue:

https://github.com/vasicvuk/nats-streaming-durable-messages-reproduction

I wrote README with screenshots to show what i am doing to have this behavior. All of the code is in this class:

https://github.com/vasicvuk/nats-streaming-durable-messages-reproduction/blob/master/NATSDurableSubscriptionIssueReplication/Program.cs

**Comment by kozlovic** [comment]
@vasicvuk I understand what's going on. I will update this issue today with an explanation. Thank you for the report.

**Comment by kozlovic** [comment]
I noticed that you are not closing the subscriptions and/or connections when your application exits. Which means that the server does not know that the connections have been closed. Reasons for that is described [here](https://github.com/nats-io/nats-streaming-server#client-connections). On planned shutdown of a subscription, user should Close() subscription (closing connection will implicitly close the subscription).

When new messages are published, and again, since the server does not know that the queue members are down, it will attempt to deliver up to 1 message to each sub since you use MaxInflight of 1.

So suppose that you have qsub1 that received last message 19 and qsub2 that received last message 20. Messages 21, ,22, 23, 24 and 25 are then published. Server will assign 21 to qsub1 and 22 to qsub2. Since these messages are not ack'ed and MaxInflight is 1, they are both stalled.

When you restart a queue member, the server will detect that you are using the same client ID, will try to contact the old client (on a private inbox), won't get an answer so will replace the consumer. So say that qsub2 is replaced: the server will reassign qsub2 pending message (seq: 22) to other qsub (qsub1, which from server perspective is still running) and start deliver message 23 to it. If you restart qsub1 quickly, server again replaced old version and so move the 2 pending messages 21 and 22 to other qsub (qsub2). But since those messages have not yet expire their redelivery delay of 60 seconds (this is what you have set), these messages are not redelivered yet but the qsub has an number of outstanding messages > than MaxInflight which cause it to be marked as stalled. This is why you see it not receiving messages.... unless you wait for more than 60 seconds where you would see them being redelivered.

I will probably alter the code to force redelivery right away in that case (and not wait for AckWait interval). Note that still in that example when qsub2 is restarted, messages 21 and 22 have been assigned to qsub1 (which is not really running but server does not know), so new qsub2 will receive message 23, 24, etc.. until qsub1 is restarted and server replaces and start to reassign 21 and 22 right away to qsub2.

**Comment by vasicvuk** [comment]
I understand this. So changing --hb_timeout, --hb_interval and --hb_fail_count should make this work faster?

**Comment by vasicvuk** [comment]
Setting --hb_timeout=1s, --hb_interval=1s and --hb_fail_count=2 make this sample work. Thanks

**Comment by kozlovic** [comment]
Yes, but I still think that I can speed up the redelivery of those messages in this specific scenario. I am working on this.

**Comment by vasicvuk** [comment]
This will be better definitely :)

**Comment by kozlovic** [comment]
This has been merged to master and you could try to see if it helps for you. Again, in your case since you are re-using clientID it may help a lot. Some users, for queue members, use ephemeral clientIDs (generate some unique ID for the clientID), and in those cases, it won't help at all.
