### ISSUE TITLE
Nats streaming consumer ack question

### ISSUE THREAD

**Issue by zeusito** [nats-io/nats-streaming-server#732]
Hello, I´m using nats streaming and just want confirm a behavior I´ve been seen lately. Suppose my consumer gets 5 messages, sequence 1 to 5, and it starts acknowledging them out of order, say 2,5,3 and suddenly crashes. When the consumer reconnects again (assuming a durable subscription) will sequence 1 and 4 be redelivered and then message with sequence 6 will be delivered?. Are my observations correct?. Thanks and congratulation for this amazing project.

**Comment by kozlovic** [comment]
Yes, for a durable subscription, when it is resumed, the unacknowledged messages are redelivered first. So message 1 and 4 should be redelivered. By the way, there is a possibility up to current release that 4 be redelivered before 1 if both have the exact same timestamp (unlikely, but not impossible). This is fixed in https://github.com/nats-io/nats-streaming-server/pull/729 and in master, not in public release yet.

**Comment by vtolstov** [comment]
when you expect new nats streaming server release?
