### ISSUE TITLE
Reliable messaging without persistence

### ISSUE THREAD

**Issue by AnatolyKap** [nats-io/nats-streaming-server#764]
Hi

1) Is it possible to build a NATS cluster where messages are not stored on disk? I would prefer to use memory store. 
(I'm dealing with sensitive data; encryption-at-rest is not an option)
PS. RALF store can be file-based

2) Messages within NATS cluster are replicated to all nodes. How exactly the replication works: is it synchronous or asynchronous? Is there a chance to loose not-yet-replicated messages at node failure? 

3) What happens at graceful shutdown of cluster leader in terms of replication: will the leader finish replication before going down?

Thanks.

**Comment by kozlovic** [comment]
> Is it possible to build a NATS cluster where messages are not stored on disk? I would prefer to use memory store.
(I'm dealing with sensitive data; encryption-at-rest is not an option)
PS. RAFT store can be file-based

Actually, data is also stored (because replicated) in the RAFT stores. Note that we have introduce support for encryption at rest in the server itself (see https://github.com/nats-io/nats-streaming-server#store-encryption)
Memory store is not supported for clustering. That being said, we have users using /var/tmp as the location of the store and as you know, in some systems, this is mapped to a ramdisk. So there is no recovery.

> Messages within NATS cluster are replicated to all nodes. How exactly the replication works: is it synchronous or asynchronous? Is there a chance to loose not-yet-replicated messages at node failure?

When the leader replicates a message, it waits for a quorum to acknowledge persistence of that message. Only when that happens an OK is sent back to the publisher API. So if your publish calls gets an OK that means that the message was replicated.

> What happens at graceful shutdown of cluster leader in terms of replication: will the leader finish replication before going down?

The RAFT node is shutdown, but there is no guarantee that inflight replication is completed. If you have high message rate and shutdown the leader, you may see failures saying that the node lost leadership while committing to the log. Again, your publishers should then get an error and you can resend those messages to be handled by the new leader.

**Comment by AnatolyKap** [comment]
Thanks for prompt response

I don't think current implementation of the encryption at rest is sufficient for sensitive data:
1) There should be a way to change encryption key without stopping the service
2) Encryption key must be stored in hardware security module

**Comment by kozlovic** [comment]
Understood. Even if we were to allow memory store (which could be a problem in that subscription IDs may not be recovered after a restart and cause a collision), as I mentioned, messages are also persisted in RAFT logs (due to data replication), so I assume that this would not be possible based on your requirements.

**Comment by AnatolyKap** [comment]
Hi 
One more question please
I have standalone NATS server (not a cluster). I would like to be able to shutdown the server "gracefully":
1. I sent signal "Start graceful shutdown" to NATS server 
2. NATS server stops listening for new connections from producers
3. NATS server closes all existing connections with producers (gracefully - after sending ACK/NAC) 
4. NATS server continues delivering messages to consumers
5. NATS server stops after all messages delivered to consumers

**Comment by kozlovic** [comment]
Sorry for the delay. This is not possible at the moment. Out of curiosity, what would be the behavior if there are messages that need redelivery (not ack'ed by consumers)?

**Comment by AnatolyKap** [comment]
If server can't deliver all messages it should wait at step 4.
User can wait for some time and kill the server (loosing data)

**Comment by kozlovic** [comment]
Doing a bit of housekeeping. We have no plan to implement the feature you had requested. So I am closing this issue now. Sorry for the long wait before getting back to you.
