### ISSUE TITLE
Obtaining Queue Sizes

### ISSUE THREAD

**Issue by Agronis** [nats-io/nats-streaming-server#768]
```// Pending returns the number of queued messages and queued bytes in the client for this subscription.```

I very well am likely misinterpreting the expected output of this function, so correct me if I am wrong, but it reads to me that this will return the current number of messages in the queue for this subscription, and the cumulative size of said messages.

1) Is my interpretation correct?
 - A) If so.. why do I only ever receive `0, 0` as my return values?
      - I have a microservice arch. consisting of 8 services in this stream, with thousands of messages being passed from start to finish - all pods, across all services, show `0, 0` msgs/bytes

Example usage:
```
func MonitorQueue(sub stan.Subscription, gauge prometheus.Gauge) {
    go func() {
        for range time.NewTicker(time.Second * 5).C {
            msgs, bytes, _ := sub.Pending()
            gauge.Set(float64(msgs))
            glog.V(2).Infof("Pending messages for this pod sit at %d msgs / %dmb", msgs, bytes*1048576)
        }
    }()
}
```

2) Is this exclusive to unacked messages, or all? (presuming my first question is true)

Apologies if this isn't the appropriate venue to ask this question..

**Comment by Agronis** [comment]
However, I literally just realized each msg has a Subscription associated to it
`msg.Sub.Pending()`

Hopefully I can report back shortly to say I have had my lightbulb moment.

**Comment by kozlovic** [comment]
@Agronis Maybe you should have posted to the go-nats-streaming repo, but that's ok.

There is no API to get the number of messages in a given channel. What you are using here is the pending size of that low level NATS subscription. This was requested by an early adopter of Streaming, so we added those APIs but these can be misleading (https://github.com/nats-io/go-nats-streaming/pull/116). I wish I had pushed back on that. I could have exposed (returned) the nats.Subscription, but then it would have been worse because user could then really disrupt the internal of the streaming library (by auto unsubscribing for instance, etc..).

Anyway, to get back to your question: in NATS Streaming messages are appended to the channel's message log regardless of subscription interest. When you create a subscription, you provide a starting point into that channel message's log based on a sequence number (if you provide a time, the server will match the corresponding sequence number). The most that the server can send to the subscription without receiving acks is defined by the subscription's option MaxInflight. The default is 1024. Again, there is no API that would tell you how many messages there are from the last sequence the server has sent to the subscription compared to the last sequence in the channel's message log.
The server can be started with monitoring port enabled (https://github.com/nats-io/nats-streaming-server#monitoring) and you can query the details about a channel. From there, you could get the information you want (I think?) but agreed this is not the easiest way.

What information exactly are you trying to get?

**Comment by Agronis** [comment]
You're right, definitely should have been over in go - apologies, but thank you all the same for your detail.

At a high level, being able to know how many messages on a specific channel are pending ack would be extremely useful for this architecture.  This appears to be available via the monitoring API, I just wish it was accessible within the implementation.. because I'm lazy and don't want to write handlers to capture all of this information ;)

Anyhow, thank you very much for your prompt response!
