### ISSUE TITLE
Nats streaming cluster does not survive restarts without message loss

### ISSUE THREAD

**Issue by mareksoluch** [nats-io/nats-streaming-server#771]
Hello,

I'm trying to evaluate NATS Streaming for our project and I've created a simple application to reflect use case we intend to use NATS Streaming for. Unfortunately it seems like my test fails - after several restarts of different nodes application stops getting response messages.

Application I've created, NATS Streaming cluster setup and test scenario is all described in this repo:
https://github.com/mareksoluch/nats-restarts-issue

Could you please advice what am I doing wrong here?

Additionally I faced some issues with Java Nats streaming client that I tried to patch on my side - could you comment on those as well? (all described in README)

Best regards
Marek Soluch

**Comment by kozlovic** [comment]
@mareksoluch I have spent quite a bit of time looking at the repo to reproduce the issue and I have some comments:
- I had to add the NATS dependency otherwise `gradle assemble` would fail ;-)
- I don't know how your volume tester works. It does not seem to keep sending, I have to trigger it every time (I also changed the POST to a GET and pass the test config locally based on what would have been in the POST).
- Not sure what issue you had with synchronous publish(), but your implementation using async publish is wrong and causes NPE too. For instance, if there is an ACK timeout, then callback is invoked with an exception, and if that is the case, you do not set anything in the requestId map, but after the latch, you check "requestId.get().equals..." which will produce a NPE.
- It seems that in some cases you create new clients (without the older being closed). This is the reason for the redeliveries. The Streaming server knows that a client is gone if the client closes the streaming connection. Otherwise, it relies on heartbeats (that are configurable) to cleanup the client connection (and stop redeliveries). Check https://github.com/nats-io/nats-streaming-server#client-connections for a bit of background.
- Not sure why you flush the low level NATS connection

The key point here is that when you publish a message, if you get an ACK timeout (because there is a new leader election - for any reason, node crashes, etc..) then your application has to take a decision: should you resend (with the risk that the message was actually accepted by the cluster but the ACK did not make it to the client) or not. There is no easy solution to that. NATS Streaming does not offer de-dup at this time. You can try to create a subscription on ACK timeout to "see" if you find the message you have published toward the end of the channel - not very reliable, or make sure that applications consuming messages from the log are tolerant of duplicates (either because they can detect them, or messages are idempotent).

**Comment by mareksoluch** [comment]
Hello @kozlovic sorry for late response (I was out of office)

As for your points 
 - as for missing dependency I don't get any failures - just checked it out on 'fresh' machine built and started with docker compose and it all just works so I'm not sure what issue you had
- as for how this volume tester works it is described in `README.md` - in order to start it you should POST test setup to `http://localhost:48081/startVolumeTest` or you can do empty post to `http://localhost:48081/startVolumeTestDefault` in order to start it with default config. I'm not sure what and why you had to change POST to GET. I assumed that POSTing config in order to start test is a better idea as it has side effects.
- as for my ugly fix with synching publish it was fixing following issue:
when I configured volume tester to use only one queue (sender sends to a queue and receiver receives and mars as delivered) it seemed like publish method that was supposed to block until ACK is received did not block and considered message send even if it was not acked - as a result during NATS restarts I was loosing messages - I will create separate branch with such setup
As for NPE you are right - will fix it - but this exception will be caught and RuntimeException will be thrown so it should not influence the volume tester as it will consider this message as not sent
- as for multiple clients created - how can I check how many clients are currently active? I tried monitoring it via rest endpoints but didn't spot duplicates. Another question is how should I handle that issues then? Should I use the same client id? What if client is still active after restart? Should I implement active reconnect retries?
- flush is probably not needed - I was just playing with different potions trying to figure out what might fix issues I experienced.

Maybe I will do a step back and create a branch with simples test and no hacks that I made and you could help me figure out why it does not survive broker restarts.

**Comment by mareksoluch** [comment]
Referring to NATS not supporting deduplication I'm totally OK with that - my app supports at least one delivery so no issue with that.

**Comment by mareksoluch** [comment]
I've simplified test, removed countdown latch all in:
https://github.com/mareksoluch/nats-restarts-issue/tree/simplify

**Comment by kozlovic** [comment]
Sorry for the delay. As I described earlier, if your client creates a new connection and uses this to send new messages but the old connection is not closed, the server will attempt to redeliver messages to that old connection until it detects it as lost. 
As described also, there is always a risk when publishing a message that the message is actually persisted in the cluster but the ACK gets lost (say the leader crashes right before sending back the publish ACK). The only guarantee is that if the publisher gets an OK, then the message has been persisted.
We have fixed also many issues related to clustering since then, so if you are interested, you could revisit your tests and try with the latest release https://github.com/nats-io/nats-streaming-server/releases/tag/v0.14.1.
