### ISSUE TITLE
Getting Status of Message

### ISSUE THREAD

**Issue by ekoeryanto** [nats-io/nats-streaming-server#787]
Halo, I am new to `nats`, is there a way/feature to get status of  published messages?

_Sorry for this kind of issue._

Thanks.

**Comment by kozlovic** [comment]
> Halo, I am new to nats, is there a way/feature to get status of published messages?

I am not sure what you are asking here. When your application publishes a message, it will either report OK, which means that the message has been persisted in the server (or cluster), or return an error. If there is an error, it is likely that the message was not persisted. If the error is indicative of an ACK timeout, then there is an uncertainty as to know if the message was persisted or not, since the server could have persisted the message and sent an ACK back to the publisher but the client may have missed or simply timed-out just before receiving the ACK.

If the message is persisted, it is appended to the message log, regardless of subscription interest. You can create a subscription to any sequence in the message log and consume those messages.

I would recommend that you browse the README where we cover some of the concepts (https://github.com/nats-io/nats-streaming-server#message-log).

If you still have questions or can clarify your original question, please don't hesitate.

**Comment by ekoeryanto** [comment]
Hi, @kozlovic, thanks for the great support.

I think, I am in the wrong repository, it should be in [/nats-io/node-nats-streaming](/nats-io/node-nats-streaming)
