### ISSUE TITLE
Default configuration values not documented

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-streaming-server#796]
https://github.com/nats-io/nats-streaming-server#configuration-file lists a bunch of parameters, but most of them don't have default value documented. Would be very nice to know what they default to.

**Comment by jextrevor** [comment]
Bump. This is something that would be very useful to know, and shouldn't be very hard to add.

**Comment by kozlovic** [comment]
@jextrevor Agreed, should not be very hard to add. By the way, the doc has moved to https://docs.nats.io/nats-streaming-server/configuring/cfgfile. Would you like to contribute? That would be greatly appreciated! If not, that's ok, thank you for bumping this out, I will get to this when I find the time :-(

**Comment by kozlovic** [comment]
@jextrevor Actually, let me know if you want/can to work on that. If not, I will set aside an hour or two to do it early next week. There is no reason to leave that issue opened for so long. Thanks again.

**Comment by jextrevor** [comment]
I see two useful places where defaults could be added - on https://docs.nats.io/nats-streaming-server/configuring/cmdline and the actual usage string that `nats-streaming-server` outputs, and on the page you linked. I'd be happy to contribute but it might be a few days before I have time.

**Comment by kozlovic** [comment]
I think the command line page could simply have a statement that those command line parameters are used to override configuration file settings, which themselves can override defaults. What I mean by that is that the config file is a more exhaustive set of things that can be configured, and command line params just a subset of what can be configured. So a statement in that page that would link to the configuration file for the user to check defaults may be enough.

> I'd be happy to contribute but it might be a few days before I have time.

Who am I to complain since this issue has been opened for more than a year :-). Again, I want to give you the opportunity to contribute if you wish. But if you prefer me to tackle it, just let me know. I will book some time early next week.

**Comment by jextrevor** [comment]
Had some extra time just now to go through and look @kozlovic 
https://github.com/nats-io/nats.docs/pull/125

**Comment by kozlovic** [comment]
This is excellent! Thank you for the contribution.

**Comment by kozlovic** [comment]
Closing since it was addressed with doc change.
