### ISSUE TITLE
Configuration sections could be documented better

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-streaming-server#797]
For example, https://github.com/nats-io/nats-streaming-server#configuration-file has a section called "Cluster Configuration:" however there is nowhere stated that the configuration file section is `cluster { }`. Some of the configuration file sections exists in example configuration files, but not all.

**Comment by JensRantil** [comment]
...to clarify what I'd expect of a fix from this issue: Either have a single full full verbose configuration file containing all sections, or mention the exact section name in each README subsection.

**Comment by JensRantil** [comment]
https://github.com/nats-io/nats-streaming-server/blob/2b200fa8f1daa1f54edb507b4567315ad91c5d25/test/configs/test_parse.conf might help here.

**Comment by kozlovic** [comment]
@JensRantil No question that we could do better. That being said, the main streaming section describes the properties that you can configure. When those properties are themselves not just a simple value, the description of that sub-section is detailed below.
For instance, for cluster in the main section you can see:
```
cluster | Cluster Configuration | Map: cluster: { ... } | See details below
```
then, you get the description of the cluster configuration section:
```
Cluster Configuration:

Parameter | Meaning | Possible values | Usage example
...
```

We had discussed internally the idea of having a configuration file with all properties present but commented out. I am ok with that I guess. It is a bit tricky since some settings are either mutually exclusive (for instance partitioning and clustering), etc..

Some background about the way the configuration is documented in the repo, I originally had a configuration file with lots of the settings and notice that some people had taken that and use it as-is, which was obviously not the intent. But it is true that having the properties prefixed with `#` to make them just comments would solve that issue I guess.

**Comment by JensRantil** [comment]
👍  I actually had totally missed that the sections were listed there.
