### ISSUE TITLE
Received invalid client publish message

### ISSUE THREAD

**Issue by naveedh27** [nats-io/nats-streaming-server#808]
Hi,
I get a error  **"Received invalid client publish message"** . When subscriber disconnects to NATS server and reconnects. Publisher is not able to push any message. On NATS console we get **[ERR] STREAM: Received invalid client publish message clientID** . The error is not observed at publisher end.

Please provide a solution.

Thanks.

**Comment by kozlovic** [comment]
@naveedh27 The error is from a "publisher" that is, server receives a published message from a connection with a client ID that is no longer valid. The connection is no longer valid if you have restarted a server without persistent store (when you start the server, if you don't provide a type of store, it uses MEMORY store as the default) since it can't recover any state, or if there was a network separation between the server and its clients long enough that the server dropped the client ID due to lack of response to heartbeat.

Here are some links about connections concept in the server:
https://github.com/nats-io/nats-streaming-server#relation-to-nats
https://github.com/nats-io/nats-streaming-server#client-connections

Not sure which client library you are using, but here is a link that can also help you understand better:
https://github.com/nats-io/go-nats-streaming#connection-status

**Comment by naveedh27** [comment]
Thanks for the quick reply. We have changed the store to file store. Its working as expected.
Much appreciated.

**Comment by raphaelLacerda** [comment]
i've got this error too. The scenario is simple as this: Nats-stan needs nats server. If nats server is down, all clients are listening and get the feedback that the connection is not valid anymore.

As soon as nats-servers comes back, all clients get the feedback that the connection is ok again.


However, IF nats-stan is down, the clients connection stays the same. So, when the nats-stan comes back, he tries to restore the previous state. If you didn't save the previous state on a persistent volume, he creates a news state.


However, the clients are connected using the previous state, so we'll get the follow errors

On nats stan: **[ERR] STREAM: Received invalid client publish message clientID:**

On nats clients: **java.io.IOException: stan: invalid publish request**


So, the solution is when you are working with nats persistence storage, like a file system, on a cloud, you can't use the container's volume to save the content, you have to map a PVC (persistence volume claim), so when a container is destroyed and a new one is created, he is able to restore the previous state.
