### ISSUE TITLE
pass *tls.Config to options and not files

### ISSUE THREAD

**Issue by vtolstov** [nats-io/nats-streaming-server#817]
I'm using mTLS in my services with own CA, and run embed nats streaming server. Using files in options not useful for me. Does it possible to add ability to pass *tls.Config struct to server options?
Also i see in https://godoc.org/github.com/nats-io/go-nats#Secure that passing *tls.Config not recommended for production using, why?

**Comment by kozlovic** [comment]
You should be able to do so since we merged https://github.com/nats-io/nats-streaming-server/pull/767. Let me know if that works for you.

The comment was that if you provide Secure(nil) then the library used to create a default TLS config that would skip server name verification, which we changed recently. So I guess that doc need to be changed.

**Comment by vtolstov** [comment]
thanks! so i need to pass *tls.Config to go-nats-streaming and to nats-streaming-server(via nats.Option)
Does this block ability to connect to nats and nats streaming via non tls clients?

**Comment by kozlovic** [comment]
In the go streaming client, you can configure TLS only if you pass the NATS connection. So configure the NATS connection for TLS, then pass that connection to the stan.Connect() call.
The streaming server needs to be configured as a client since what is really accepting connection is the NATS Server. If you embed NATS Server in the Streaming server, you need to configure both: https://github.com/nats-io/nats-streaming-server#tls

**Comment by vtolstov** [comment]
yes, thanks!
