### ISSUE TITLE
maximum payload exceeded even when it isn't 

### ISSUE THREAD

**Issue by mmanna-sapfgl** [nats-io/nats-streaming-server#830]
[streamer_conf.txt](https://github.com/nats-io/nats-streaming-server/files/3167184/streamer_conf.txt)

Attached is my config file for streaming server and the following command is what I have used to do a bench test

`.\stan-bench.exe -c streamer1 -id foofighter1 -qgroup foo.eater -np 1 -ns 1 -ms 5000000 -n 1 -csv 5Mx1x1px1s.csv -s nats://192.168.99.100:4223`

It's outputting:

`Starting benchmark [msgs=1, msgsize=5000000, pubs=1, subs=1]
nats: maximum payload exceeded`

As per documentation, it's the size of each payload. And I can confirm that the payload limit is shown as 5M upon startup. Is there any specific calculcation for payload limit (if so, could this be documented slightly better in FAQ or README sections) ?

Thanks

**Comment by kozlovic** [comment]
A streaming message uses protobuf so there will be overhead. When you pass `ms 5000000` you are really setting the protobuf Msg.Data to an array of 5000000, so after serialization of that message, the actual size will be just enough bigger to cause the failure. Reduce the size of `ms` or increase the size of `max_payload`

**Comment by mmanna-sapfgl** [comment]
> 
> 
> A streaming message uses protobuf so there will be overhead. When you pass `ms 5000000` you are really setting the protobuf Msg.Data to an array of 5000000, so after serialization of that message, the actual size will be just enough bigger to cause the failure. Reduce the size of `ms` or increase the size of `max_payload`

No trying to reject your answer here. But I believe this is not very well documented. I can see a section for protocols on nats.io. From a user's viewpoint, what you explained above isn't obvious. I would expect this to be in some form of bold character under 

https://nats.io/documentation/additional_documentation/nats-benchmarking/

Would you not agree ?

**Comment by kozlovic** [comment]
Sorry about that. I answered your question more on the perspective of why it failed, not the documentation part.
We are completely reworking the documentation at the moment and so yes, this is something that we should include somewhere. The link you point to is for core NATS though, which then does not apply since the actual message payload limit is really max_payload. The problem with streaming is that a NATS message payload contains the streaming protobuf serialized contain (which itself contains your application specific payaload). Keep this one close but will open one specifically for documenting the max_payload impact in streaming clients.
