### ISSUE TITLE
I embed NATS Streaming, how to send messages to the embedded nats straming in the process.

### ISSUE THREAD

**Issue by lovelly** [nats-io/nats-streaming-server#860]
I see an example :  

```  
s, err := stand.RunServerWithOpts(opts, snopts)  
nc, _ := nats.Connect("nats://localhost:4223")   
sc, err := stan.Connect("test-cluster", "client_id", stan.NatsConn(nc))   
sc.Publish("subject", []byte(data))
```

I need:  
No need to connect nats.
Send a message directly to nats in the process.
E.g  
```  
s, err := stand.RunServerWithOpts(opts, snopts)  
s.Publish("subject", []byte(data))  
```

**Comment by aricart** [comment]
Not sure if I understood your message correctly, but it seems that you want to send messages to the NATS server embedded in the nats streaming server. If that is is the case:

```
s, err := stand.RunServerWithOpts(opts, snopts)  
// 'nc' is a nats connection, which you are passing to the stan client:
nc, _ := nats.Connect("nats://localhost:4223")   
sc, err := stan.Connect("test-cluster", "client_id", stan.NatsConn(nc))   
sc.Publish("subject", []byte(data))

// so to send a nats message that won't go through stan you can:
nc.publish("subject", []byte(data))
```

**Comment by lovelly** [comment]
I want to bypass the socket connection, which should be applied and nats in one process. I want to send a message to nats directly through a function call, not a socket connection.

**Comment by gedw99** [comment]
Interesting question. Whats the Use case ?

You could maybe do it using a serial connection to the NATS STreaming Server ( that embeds the NATS Server). SO you need durable messaging ?

**Comment by kozlovic** [comment]
@lovelly Nowadays, TCP through loopback is really optimized and I bet that it would not make much of a difference (except for reduce number of API calls in the example you posted). Question is do you plan to have other subscriptions or publishers actually receiving/sending outside of the process? If not, I would argue that using streaming is an overkill?

**Comment by kozlovic** [comment]
@lovelly I am closing this for now, unless you have additional questions/comments.

**Comment by pturanyi** [comment]
Please can you proviede more detailed information about nats connection
```
package main
 
func main() {
        s, err := stand.RunServerWithOpts(opts, snopts)  
        nc, _ := nats.Connect("nats://nats.argo-events.svc:4222")   
        sc, err := stan.Connect("PASS-DEV-AKS-Cluster", "client_id", stan.NatsConn(nc))   
        sc.Publish("subject", []byte(data))
}
```
output
```
C:\>go run nats.go
# command-line-arguments
.\nats.go:5:19: undefined: stand
.\nats.go:5:43: undefined: opts
.\nats.go:5:49: undefined: snopts
.\nats.go:6:18: undefined: nats
.\nats.go:7:20: undefined: stan
.\nats.go:8:38: undefined: data
```

**Comment by kozlovic** [comment]
@pturanyi You did not import the appropriate packages and use `data` that is not defined anywhere. I don't mean to offend, but it looks like you are not familiar with the Go programming language and therefore should start learning with the standard library before jumping into projects. Once you are familiar with Go, here are some resources to help you with:

NATS: 
https://github.com/nats-io/nats.go#basic-usage
https://docs.nats.io/developing-with-nats/developer

STAN:
https://github.com/nats-io/stan.go#basic-usage
https://docs.nats.io/developing-with-nats-streaming/streaming (and all chapters that follow, showing how to connect, publish, subscribe, etc..).

If you plan to embed the streaming server in your application:
https://docs.nats.io/nats-streaming-server/embedding

But since you are starting with STAN, please be aware that NATS Streaming (STAN) is in maintenance mode and instead you should be looking at JetStream: https://docs.nats.io/jetstream/jetstream
