### ISSUE TITLE
Durable subscriptions but possibility of message loss due to limits?

### ISSUE THREAD

**Issue by Manuri** [nats-io/nats-streaming-server#864]
I'm trying to understand NATS concepts since I'm working on writing a NATS client for Ballerina language.

According to the documentation, in NATS streaming server, durable subscriptions are supported. But as I understand, if the message log limit has passed when a client disconnects and connects back, it will lose a set of messages. How the at-least once promise is fulfilled with this?
What are the intended use cases that tolerate this behavior?

**Comment by ripienaar** [comment]
Yes messages will be lost in that case. If you configure explicit limits for count size or age then that’s pretty much the only thing they make sense.

Obviously it can’t guarantee delivery of things that you also tell it to delete. Deletes will win. So careful consideration should be made for your limits. 

For example i put server metrics through streaming and old metrics in the stream is useless so I set short discards - 5 minutes - and should some receiver be down for ages when he returns he get data that’s relevant to its uses - recent data only. The durable feature then is to help with restarts and short reboots as a short buffer. In that scenario short limits are fine. 

Other data that I put over streaming gets replaced by new data every 10 minutes. So I set it to discard after 30 minutes which is the right thing again for that case. Neither of these I would want infinite delivery of data and both have different limits. 

So for each scenario you have to balance it out against your needs and data types.

**Comment by kozlovic** [comment]
The question about "how can this be at least once" if due to limit a message is removed before a consumer had a chance to get it is legitimate. But you have to understand that streaming is not a message queue (as you may know from JMS or the like) in that a message is not removed because it is acknowledged by a consumer. A message is persisted regardless of consumer interest and consumers can be started at any time to point to any place in the stream. (https://nats-io.github.io/docs/nats_streaming/channels/message-log.html)

With that in mind, the only way for the system to remove a message is to define some limits. You *can* make the channel unbounded, but you need to realize that it means that you would need unlimited resources, which is not realistic.
