### ISSUE TITLE
Received invalid client publish message with persistent store

### ISSUE THREAD

**Issue by MateuszPluciennik** [nats-io/nats-streaming-server#873]
Hi, 
I am using NATS Streaming server **v0.11.2** in cluster mode (three nodes).
Java client version: **2.1.2**

I have problem with publisher, at some point there is (probably) problem with network for one of the clients. After such incident the client is stil publishing messages, without any errors but there are errors in nats-streaming-server itself. I get same error as described in (https://github.com/nats-io/nats-streaming-server/issues/808): **'Received invalid client publish message'**. 

The main difference is that I use persistent store (SQL) with Postgres database. 
Currently I have connected more than 8 clients. Problem occured only for some of them. I checked nats database and I found that clients table is empty. 

Shouldn't be in database informations about currently connected clients?

Thank you!

**Comment by kozlovic** [comment]
The Java client does not have yet the ability to detect that the logical connection to the streaming server is no longer valid (some background with the Go client can be found [here](https://github.com/nats-io/stan.go#connection-status)). So if there was a network issue to the point where the server has dropped the client connection due to timeout, then the client would possibly not know and continue to publish which would result in the error you have observed.

In clustered mode, the client connection information is not stored in the streaming stores/DBs, but is in the RAFT logs, so this explains why you don't see anything there.

**Comment by MateuszPluciennik** [comment]
What is your suggestion? How we can handle such situation? 
Right now we are loosing messages.  
We also noticed that (probably) in the same situation our subscribers stop receiving messages.

**Comment by kozlovic** [comment]
@MateuszPluciennik First, please make sure that you use the latest NATS Streaming server release. There were "serious" issues with cluster mode and SQL. Note however that 0.15.1 cannot be clustered with older releases, unless you use a separate NATS cluster. Check release notes for details.
Also, make sure that each of your node in the cluster has its own SQL database. In clustered mode, the storage (being file or SQL) needs to be per node, not shared.

Then back to your issue:
- Have you changed the server configuration regarding client health heartbeat frequency? If not, then I am a bit surprised that you get this error because it means that the network outage would have been more than 7 minutes, which then you should look at that first.
- Are you providing your own NATS connection to the Streaming connection? 
- Do you know if the NATS connection was disconnected or reconnected ok?
- Are you doing async or sync publish calls?

Regardless of how you do publish message, you SHOULD receive an error when the publish is invalid. The error you see being reported in the server is sent back to the publish call. When that happens, then your application should consider the connection lost and re-create it along with the streaming subscriptions (if applicable).
This is really what the Go's ConnectionLostHandler would do: report that the connection is lost, but as of now, no streaming library will reconnect/recreate subscriptions for the user.

**Comment by MateuszPluciennik** [comment]
As I mentioned in first message the issue was spotted on configuration: 
NATS Streaming server **v0.11.2**
Java client version: **v2.1.2**
All nodes have their own SQL database.

Answers to your questions: 
>Have you changed the server configuration regarding client health heartbeat frequency? If not, then I am a bit surprised that you get this error because it means that the network outage would have been more than 7 minutes, which then you should look at that first.

Client healt heartbeat frequensy was not changed. I use default configuration for this.

>Are you providing your own NATS connection to the Streaming connection?

I'm not sure if I got your question. Snippet contains simplified connection initialization that I use in my application.

```java
import io.nats.client.Connection;
import io.nats.client.ConnectionListener;
import io.nats.client.Consumer;
import io.nats.client.ErrorListener;
import io.nats.client.Nats;
import io.nats.client.Options;
import io.nats.streaming.StreamingConnection;
import io.nats.streaming.StreamingConnectionFactory;


class ConnectionExample {

private StreamingConnection streamingConnection;
private Conncetion connection;
private String[] urls = new String[]{"nats://localhost:4222"};


public void initNatsConnection() throws IOException, InterruptedException { 
	Options o = new Options.Builder()
			.servers(urls)
			.userInfo(username, password)
			.connectionListener(new CustomConnectionListener())
			.errorListener(new CustomErrorListener())
			.maxReconnects(-1).build();

	connection = Nats.connect(o);

	StreamingConnectionFactory cf = new StreamingConnectionFactory(clusterId, clientId);
	cf.setNatsConnection(connection);

	streamingConnection = cf.createConnection();
}
```
>Do you know if the NATS connection was disconnected or reconnected ok?

Yes, based on logs from ConnectionListener, connection was disconnected and reconnected. My implemetation of ConnectionListener. 

``` java
class CustomConnectionListener implements ConnectionListener {
	private final List<Events> connectEvents = asList(CONNECTED, RECONNECTED, DISCOVERED_SERVERS);

	@Override
	public void connectionEvent(Connection conn, Events event) {
		log.info(String.format("Connection status changed to %s. ", event.name()));

		if (connectEvents.contains(event)) {
			log.info(String.format("%s. Connection event occurred for host %s", event.toString(), conn.getConnectedUrl()));
		}
	}
}
```

>Are you doing async or sync publish calls?

I use both publish methods.

>Regardless of how you do publish message, you SHOULD receive an error when the publish is invalid. The error you see being reported in the server is sent back to the publish call.

I checked it again. For sync calls error is not sent to client or client is not able to get it. 

For testing I used newer version of nats server and the newest java client:
- nats streaming server (v0.14.3 in docker) with sql storage (postgres)
- java aplication able to make asynch and sync calls (java client v.2.5.2)
- nats connection created with option `maxReconnects(-1)` (first snippet)

Steps to recreate issue:
- connect to nats server and create streaming connection (first snippet),
- connect to database and remove client from database,
- restart nats server,
- when connection status change to `RECONNECTED` try to publish message with sync call

Method does not throw any exception. There is also no client logs.
Nats server log:
```
[ERR] STREAM: Received invalid client publish message clientID:"clientId" guid:"66q9SDClGzUBAvX0ix47XC" subject:"test" data:"message"
```


For asynch method exception is thrown. Example method implementation:

```java
public void publishAsync() {
	try {
		streamingConnection.publish(message.getSubject(), message.getMessage().getBytes(), (nuid, ex) -> {
			if (ex == null) {
				log.info("PUBLISHED message '{}' to subject '{}'", message.getMessage(), message.getSubject());
			} else {
				log.error("AckHandler: Cannot publish message.", ex);
				log.info("Nats connection status " + connection.getStatus());
			}
		});
	} catch (IOException | InterruptedException | TimeoutException e) {
		log.info("Nats connection status " + connection.getStatus());
		log.error("Cannot publish message.", e);
	}
}
```

```
java.io.IOException: stan: invalid publish request
	at io.nats.streaming.StreamingConnectionImpl.processAck(StreamingConnectionImpl.java:560) [java-nats-streaming-2.1.6.jar:2.1.6]
	at io.nats.streaming.StreamingConnectionImpl.lambda$connect$0(StreamingConnectionImpl.java:127) [java-nats-streaming-2.1.6.jar:2.1.6]
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:80) ~[jnats-2.5.2.jar:2.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]`
```

`log.info("Nats connection status " + connection.getStatus());`
This line prints: `Nats connection status  CONNECTED`. `connection` is connection to nats server (not streaming connection).
Application is connected to nats server but not to nats streaming (probably).

Should I re-create streaming connection every time when i get IOException in AckHandler implementation?
What if my application use only subscriptions or subscribptions with synch calls? Then application never get this exception.

**Comment by kozlovic** [comment]
> As I mentioned in first message the issue was spotted on configuration:
NATS Streaming server v0.11.2

What I mentioned is that there is known (severe) issue with clustered mode and SQL store, whereby followers are not persisting any message when they should, only flushing a possibly huge transaction when becoming active.

> Client health heartbeat frequency was not changed. I use default configuration for this.

That's where I am a bit concerned because for the invalid client publish to happen, it means that the server dropped the connection due to timeout, and that is more than 7 minutes of no response with default values. The manipulation that you are doing: removing client record from DB is fine for the purpose of demonstrating the issue, but that should not happen in production.

> I checked it again. For sync calls error is not sent to client or client is not able to get it.

It should, if not, there may be a bug in the library. I have cc'ed @sasbury since he is the one maintaining it.

> Should I re-create streaming connection every time when i get IOException in AckHandler implementation?

Until the "client ping" feature is added to the Java streaming library, you could indeed check the error and for that specific case, yes, the streaming connection is considered lost from a server perspective.

> What if my application use only subscriptions or subscriptions with sync calls? Then application never get this exception.

The sync publish call should return an exception, this should be addressed. As for "only sub" apps, yes, that is a problem and reason why client-to-server pings were introduced.

I think it would still be worthwhile figuring out why the server dropped the client connection, which will happen if there was no communication from server to client (server sends pings to client that it echos) for more than 7 minutes. With the client-to-server ping feature missing from the Java library, the outcome would be the same: connection will be reported as permanently lost.

**Comment by MateuszPluciennik** [comment]
I updgraded streaming server to **0.14.3**, java-nats-streaming to **2.1.6** and jnats **2.5.2**.

I tried to reproduce issue without removing client id from database. I could not do it in that way.

However the situation described in issue has happened again. 
We have clustered nats and several applications connected to this cluster. We lost connection to one application (app is in separate cloud). Lets call it just "client". 
Connection was lost, but the client was still running. Due to configuration, the client was trying to connect to nats server endlessly. In the same time the nats server was still sending pings to client. After 7 minutes the server probably dropped client id (default heartbeat confguration). Connection was recovered after about 30 minutes. Then the client succesfully recovered connection to nats server but was unable to send messages due to: 'Received invalid client publish message' issue. 

I'm not 100% sure about this scenario but it looks probably. Do you think that's the case?

I think that by following your instructions I am able to handle such situations by re-creating streaming connection on every exception from client. 

Problem is with "sub obnly" clients and sync call. I will create a separate issue in java client github.

**Comment by kozlovic** [comment]
Yes, the way you describe the steps would cause the invalid client publish. As I was hinting to, though, is that having your clients separated from the servers for more than 7 min should be a concern to you.

Yes, create an issue to the java repo for tracking purposes. Thanks!.

**Comment by dagenius007** [comment]
I still get this error I am using node-nats-streaming

**Comment by kozlovic** [comment]
@dagenius007 Please stop commenting on all issues related to that. Wait for a comment on the issue you filed today on the stan.js repo. Thanks!

**Comment by dagenius007** [comment]
Alright

**Comment by raphaelLacerda** [comment]
i've got this error too. The scenario is simple as this: Nats-stan needs nats server. If nats server is down, all clients are listening and get the feedback that the connection is not valid anymore.

As soon as nats-servers comes back, all clients get the feedback that the connection is ok again.


However, IF nats-stan is down, the clients connection stays the same. So, when the nats-stan comes back, he tries to restore the previous state. If you didn't save the previous state on a persistent volume, he creates a news state.


However, the clients are connected using the previous state, so we'll get the follow errors

On nats stan: **[ERR] STREAM: Received invalid client publish message clientID:**

On nats clients: **java.io.IOException: stan: invalid publish request**


So, the solution is when you are working with nats persistence storage, like a file system, on a cloud, you can't use the container's volume to save the content, you have to map a PVC (persistence volume claim), so when a container is destroyed and a new one is created, he is able to restore the previous state.
