### ISSUE TITLE
how to remove warn?

### ISSUE THREAD

**Issue by peng-w** [nats-io/nats-streaming-server#877]
This is my configuration.
![image](https://user-images.githubusercontent.com/6479081/60860480-51c9c200-a249-11e9-95de-37370c525be0.png)

Is my operation correct? how to remove warn? 
![image](https://user-images.githubusercontent.com/6479081/60860467-4080b580-a249-11e9-94c1-02234369a95c.png)

**Comment by kozlovic** [comment]
@peng-w The short answer is you can't, but there is more to it. Let me try to explain.

First let's understand how things work with NATS Server (not streaming), then we will look at streaming.

In NATS Server, when a configuration file is provided with an authorization block that contains only 1 user, then the command line parameter `-user ..` overrides whatever is in the configuration. (Note that the simple authorization stance - with single user - is different than having the multi-user stance, even if there is only one user defined there)
However, due to Unix and the special characters that compose the bcrypt password, you would not configure the server with the expected user/password. You could try and if you were to try to connect a NATS client with the expected user/password it would fail. You would need to surround the bcrypt password on the *command line* with `'` characters.
But in NATS server, you are simply configuring the users (and their passwords) that are allowed to connect.

In NATS Streaming, if you want to embed the NATS Server, you have to configure both the valid list of users but then need to configure which credentials the Streaming server (which is actually a client to NATS) need to use.

Also, you should know that when a client connects to the NATS Server, it provides the username and password in plaintext, even if the server has the user's password configured using bcrypt. That is, the client sends in the CONNECT protocol the password in plaintext. When server receives it and if the matching configured user has a bcrypt password, the server will apply bcrypt algo to the received plaintext password and compare the result to see if the user is authorized or not.

With that in mind, you would not be able in NATS Streaming to configure both the user's password and the credentials to use from the command line using bcrypt because the streaming server would then try to pass the password to the connection to NATS Server as provided in the command line, which then would not match the bcrypt of the configured password.

So if you need only one user, then in NATS Streaming you will need to have `-user <user> -pass <pass in plaintext>` only. If you want to specify multiple user, then you will need the config file and still the command line to select which user to use for the streaming server.
For instance, here is what a streaming auth configuration may look like:
```
authorization {
  users [
     {user: server, password: $2a$05$aA0QpGeDJfIDdZBsL35Px.ObKkdc3dmS9XVwSM5nvkfWgN6YPyUZe}
     {user: user, password: $2a$05$LHj2tDdH4gCKAwRQZa1eduZ65L0WuUMHRQIJv5vBI3Thym0w3JW0u}
  ]
}
```
The bcrypt password for each user is the name of the user. That is, password for `server` is `server` and password for `user` is `user`.
When starting the server you would then need something like this:
```
nats-streaming-server -c c.conf -user server -pass $SRV_PASS
```
where `$SRV_PASS` would contain the actual password in plaintext, that is `server`. You can obviously pass it directly:
```
nats-streaming-server -c c.conf -user server -pass server
```

At this point, due to the reuse of NATS server code in NATS Streaming, you would not be able to avoid the warning message. 
You would have to run a separate NATS server, but still, you would need to pass the streaming credentials in plain text as described above, with the addition of `-ns <nats server url>`.
