### ISSUE TITLE
question: start position for new durablename to same queue

### ISSUE THREAD

**Issue by blinkinglight** [nats-io/nats-streaming-server#896]
i hit strange situation. i dont know if DurableName is new or not new. i expected that with new DurableName and stan.StartWithLastReceived() start position will be 0. so my question is - is that bug or i am missing feature like "if name not exists start at 0 else start from name.last_received". Or how i can check if DurableName exists.

**Comment by kozlovic** [comment]
I think I understand why you are confused. The `stan.StartWithLastReceived()` option means last message received by the server and appended to the end of the channel. In other words, it means start with the last message on the channel.

Otherwise, when you create a durable for the first time, if you wish to receive all messages in the channel, you would start with `stan.DeliverAllAvailable()`. The default is NewOnly which means any message that will be published after the subscription is registered. Again, the StartWithLastReceived means the current last message in the channel when the subscription is registered.

Once a durable exists, the start position is ignored since the server maintains the current position of the subscription in the channel.

More information here: 
https://nats-io.github.io/docs/nats_streaming/channels/subscriptions/subscriptions.html#subscriptions
https://nats-io.github.io/docs/nats_streaming/channels/subscriptions/durable.html

**Comment by blinkinglight** [comment]
thank you!
