### ISSUE TITLE
Are all received messages immediately saved to a configured persistance storage (eq postgreSQL)?

### ISSUE THREAD

**Issue by CarloWakefield** [nats-io/nats-streaming-server#898]
According to the `README.md` the NATS Streaming Server can store some of it's state on a persistent storage (like e.g. a postgreSQL database):

> By default, the NATS Streaming Server stores its state in memory, which means that if the streaming server is stopped, all state is lost. Still, this level of persistence allows applications to stop and later resume the stream of messages, and protect against applications disconnect (network or applications crash).

What exactly is persisted? Are all messages that are published to a subject immediately persisted? Or is there some interval (time, memory, …) which has to be passed before they are saved? Or is only the state of the subscriptions persisted?

**Comment by kozlovic** [comment]
This says that if you run with no persistent store (file or SQL), everything is just in memory. If the *server* were to crash, then all state is lost. But, if applications crashes or simply gets temporarily disconnected, then this still offers the at-least-once guarantee.

So in most cases users will use persistence (filestore or SQL) so that the state is persisted also after a server restart (due to crash or maintenance).

Messages are persisted when they are received and only after that the ACK is sent back to the publisher. The filestore and SQL implementation do use some buffer to optimize a bit the processing of parallel incoming messages for the same channel from different connections, still, the messages are persisted and store is flushed, so messages should be in persistent storage before the ACK is sent back.
