### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by edufschmidt** [nats-io/nats-streaming-server#904]
Hi, do you plan to add support for other persistence backends in the near future? More specifically, I would be interested in having MongoDB as an option. Thank you in advance for any information you can provide.

**Comment by kozlovic** [comment]
No plan at the moment. Someone asked if there was interest in Badger (https://github.com/nats-io/nats-streaming-server/issues/887) but propose to contribute if interest is there. Would be the same for MongoDB or any other backend.

**Comment by edufschmidt** [comment]
Cool, thanks for the quick answer!

**Comment by SherinSony** [comment]
We also need support for mongodb !

**Comment by mnrendra** [comment]
There is MongoDB connector or adapter or converter to NATS server?
I want to make some communication between all MongoDB servers (replica set) to all my NodeJs nodes via pubsub.

**Comment by kozlovic** [comment]
Sorry for leaving this ticket opened for so long. We have not plan to add new store implementations. Note that this project is in maintenance mode (see deprecation notice [here](https://github.com/nats-io/nats-streaming-server#warning--deprecation-notice-warning)).

I am closing this issue so that it does not give a false hope that this would happen in the future. Thank you.
