### ISSUE TITLE
Implementation of a queue with the ability to change the status of messages

### ISSUE THREAD

**Issue by karpotkin** [nats-io/nats-streaming-server#911]
Is it possible with nats server to implement the following: 

suppose I have a queue of messages that the subscriber received, every 10 seconds the subscriber saves all messages and sends a message to the nats server. After this, messages are deleted from nats. If the subscriber did not do this (for example, something went wrong and everything broke), a new subscriber is created, to which nats should send all messages, including those that have already been sent to the previous subscriber.

**Comment by kozlovic** [comment]
No this is not possible with NATS Streaming. Messages are appended to a log and only old messages are removed based on limits set on the channel (or globally): https://nats-io.github.io/docs/nats_streaming/channels/message-log.html

But since messages are not removed simply because they are consumed, your application could consume and ack, but if something goes wrong, you can always recreate a subscription to any sequence/timestamp for messages in that log (again, assuming older have not been removed due to limits).
