### ISSUE TITLE
Force memstore/expireMsgs after  [INF] STREAM: done restoring from snapshot

### ISSUE THREAD

**Issue by bfoxstudio** [nats-io/nats-streaming-server#915]
We use in-memory streaming with 3 nodes cluster.
Each node use 5gb RAM.  max_age: "6h"
```
streaming: {
    store_limits: {
			max_channels: 1000
			max_msgs: 0
			max_bytes: 16GB
			max_age: "6h"
			max_inactivity: "48h"
```
`[1] 2019/08/16 07:57:48.729472 [INF] STREAM: done restoring from snapshot,`

If restart 1 node and "done restoring from snapshot" we have 5GB ram, but first expireMsgs start after 6h.
It turns out that we use 10 gigabytes after 5:59 hours and after 6 hours 5 gigabytes are released immediately

```
		ms.ageTimer = time.AfterFunc(ms.limits.MaxAge, ms.expireMsgs)
```

On other types of storages, the problem is the same but less critical

total bytes:
blue line -> 2 restarts
![image](https://user-images.githubusercontent.com/11800002/63155613-94867300-c01b-11e9-8213-13086e8781ea.png)

**Comment by kozlovic** [comment]
So far MEMORY store is not supported with clustering, so it means that you have removed the check in RunServerWithOpts(). The memory store implementation did not expect that a message timestamp would be in the past (since on restart there is no possible recovery of older messages). But since you by-passed the memory type check, then those messages are recovered from the RAFT store (or from the leader if you also removed that node's raft log), there is then a call to the memory store's Store() function with a message which timestamp is well in the past.

The file store implementation behaves correctly, however, the SQL does not (behaves similar to the memory store in that the age timer is fired based on current time + max_age). So this definitively needs fixing.

I will probably fix the memory store too, although again it is not a supported configuration. Keep in mind that messages are stored in both the RAFT log and streaming stores but the messages are looked-up (to be delivered to subs) from the streaming store. RAFT log can be compacted, that is older entries are removed when a snapshot is done, which means that with the memstore you could have a situation where messages are no longer available from streaming store (due to use of memstore and a restart) while they are still referenced (first/last seq for a channel) in a RAFT snapshot, which may cause issues...
