### ISSUE TITLE
checked in docker image instead of file

### ISSUE THREAD

**Issue by satishb557** [nats-io/nats-streaming-server#946]
Hi Friends,

Appreciate your help and time.
I have few questions on my existing NAT streaming in our project.

1)
Earlier who worked in the role had been checked in the docker image instead of file.

FROM docker.apple.com/abc/nats-streaming:latest\

Now I want to check through the docker file . can you help me.

2)
Also, NATs stream deployed as cluster with the one leader and 2 follower nodes. what is use of the follower nodes. Can leader exist without followers. where is sample code for the leader with the followers code.

3) In the test environment, I found one leader and many followers. how to check which are follower are associated with the leader . so that, I can clean the unused followers with out any impact

Regards,
Satish

**Comment by kozlovic** [comment]
@satishb557 Sorry, I don't understand the first question. The official image can be pulled from here: https://hub.docker.com/_/nats-streaming : `docker pull nats-streaming`.

> Also, NATs stream deployed as cluster with the one leader and 2 follower nodes. what is use of the follower nodes. 

In cluster mode, the state is replicated in all followers. This allows high availability in that if a node were to disappear, then the state exists in enough other nodes so that the system can continue to run. See https://nats-io.github.io/docs/nats_streaming/clustering/clustering.html for more information.

> Can leader exist without followers. where is sample code for the leader with the followers code.

No, unless you want to run it in standalone mode. (that is, no clustering, no RAFT group, single server): https://nats-io.github.io/docs/nats_streaming/intro.html

> In the test environment, I found one leader and many followers. how to check which are follower are associated with the leader . so that, I can clean the unused followers with out any impact

Again, in cluster mode, a leader cannot work without follower. For instance, for a cluster of size 3, the system can work with 1 failure, if a second node fails, the system blocks because there is no quorum.
Quorum=cluster size / 2 + 1 
Failures = cluster size - quorum
Cluster sizes should be odd numbers.
For size 3: qorum=3/2+1=2, so failures allowed=3-2=1
For size 5: qorum=5/2+1=3, so failures allowed=5-3=2
etc..

**Comment by satishb557** [comment]
Thanks Ivan for your elaborated reply.
I am pretty new to this NATs streaming. sorry for dumb questions.

On the first point, Please confirm my understanding.  if we lost/accidentally deleted  the existing used image , latest image can be pulled using below command.

docker pull nats-streaming

Also I heard that, instead of pull the image , we need to build the image.is that the standard way of doing? Please clarify

On the last question, I am assuming some unused followers pods are running in the test environment . How can I find the followers with no leader.

Thanks ,
Satish

**Comment by kozlovic** [comment]
> On the first point, Please confirm my understanding. if we lost/accidentally deleted the existing used image , latest image can be pulled using below command.
docker pull nats-streaming

Yes.

> Also I heard that, instead of pull the image , we need to build the image.is that the standard way of doing? Please clarify

It depends if you want to use the docker image or not. You can manually build from the repo (say if there are some fixes that are not yet released but you need/want to try), or also download/use the pre-built binaries: https://github.com/nats-io/nats-streaming-server/releases (look at the assets list with all executables that we provide).

> On the last question, I am assuming some unused followers pods are running in the test environment . How can I find the followers with no leader.

Again, not sure what "unused" mean since a follower is a normal state. If this is test and you don't know who is using what, maybe you can shutdown/clean everything and restart with a fresh setup.
The logfile should show the name of the cluster and somewhere in the log is printed when a node becomes leader or when it loses leadership. If you had enabled monitoring, and depending the version you use, the `/streaming/serverz` monitoring endpoint will display which clustering role the node is in (https://nats-io.github.io/docs/nats_streaming/monitoring/endpoints.html#serverz)

**Comment by kozlovic** [comment]
Closing due to age. Will re-open if required.
