### ISSUE TITLE
publish ack timeout

### ISSUE THREAD

**Issue by zhhnzw** [nats-io/nats-streaming-server#958]
I received some log such as 

> Warning: error publishing msg id nnOjUDCSXSbRUCA7ZfZtkg: stan: publish ack timeout

Those log seems to be intermittent and random.I can't find the reason.Maybe I use nats-streaming-server a inappropriate way. Any special config suggestions?
I run NATS-Streaming server cluster and use go-nats-streaming client connect it. I used it in the special way, NATS-Streaming server cluster is exposed to the public network, and client connect server through the wide area network. Does this usage cause this problem?

**Comment by kozlovic** [comment]
Those warnings are on your application logs, right?
This error means that a streaming client is publishing a message and it did not get the ack back from the server. It could be because:
- the message was lost in transit
- the ack was lost in transit
- the server was not able to respond within the publisher's ack wait
- in clustering mode, there was no leader at the time of the publish
- if you use low level NATS permissions, the publisher sent to a subject for which it does not have permission

Hope the above list helps.
