### ISSUE TITLE
question about restoreMsgsFromSnapshot function

### ISSUE THREAD

**Issue by cjg1990** [nats-io/nats-streaming-server#960]
![image](https://user-images.githubusercontent.com/14998346/67732039-0a329600-f9f2-11e9-9b8f-d2e7fe487e48.png)
I'm reading the source code of nats streaming and I have got a confused question here as the above screenshot。Why the function restoreMsgsFromSnapshot should be called even on startup？

**Comment by kozlovic** [comment]
I will try not to paraphrase the comments you have highlighted, but this is the actual reason :-)

RAFT stores all messages and meta data (information about connections, subscriptions, etc..) in its own log. Messages are also stored in the streaming message stores. This is needed because when the server needs to lookup a message the message is per channel and at a given sequence number that would not match what is in the RAFT log. Also, from time to time, RAFT will perform snapshots that will remove entries from its own log.

When RAFT produces a snapshot, we save in the snapshot the first/last sequence of a given channel. This allows RAFT to reclaim space in its log, otherwise it would grow unbounded.

When a node starts, we need to make sure that the streaming message store is in agreement with what the RAFT log says this store should contain (we do this for each channel). If that's not the case, this node must not be elected leader and needs to get the missing messages from the current leader. Hence the repeated attempts at restoring and if it can't, the server exit without ever completing the RAFT startup phase (again, this is on purpose since this node is not to in sync between its RAFT log and the message stores).

**Comment by cjg1990** [comment]
Thanks for your answer! But I am really confused with that  in which situation message  in the message store is not in sync with RAFT log?can you show me an example?

**Comment by wallyqs** [comment]
That is because the according to Raft spec whenever Raft log is compacted, then to be in sync it has to do it from an snapshot if the member was really gehind

**Comment by cjg1990** [comment]
> That is because according to the Raft spec whenever Raft log is compacted, then to be in sync it has to do it from an snapshot if the member was really gehind

Thanks for answering this question! And I know there are two cases in which Follower needs to restore messages from Leader，one is that RAFT log on Follower is far behind Leader, and Leader sends the latest RAFT snapshot to Follower for getting missing messages. The other one is when a published message has been commited, Follower must make sure that there is no gap between the last message stored locally and the commited message, so Follower should restore message from Leader. But I am really confused in which situation message in the message store is not in sync with RAFT log **when the server starts up**?And I think that restoring messages on server's startup is unnecessary, **can you show me an example of the necessity of restoring messages from Leader when the follower starts up?**

**Comment by kozlovic** [comment]
Because RAFT replicates data and then invoke the FSM (finite state machine) about committed log. This is when the server has a chance to store in its own store. This is asynchronous and also NATS Streaming may store data on its file using buffers (for performance) and so there is always a risk that some data is missing. On startup when the RAFT log is replayed, the streaming server needs to ensure that its message store is in sync with the RAFT log.

**Comment by kozlovic** [comment]
Closing this for now.
