### ISSUE TITLE
[API] field total_msgs (streaming/serverz) is directly affected by the deletion.

### ISSUE THREAD

**Issue by renanberto** [nats-io/nats-streaming-server#974]
Hello guys

We use [nats-exporter](https://github.com/nats-io/prometheus-nats-exporter) to get nats metrics and set up charts, alerts, and everything.

We note that after the timeout to begin deleting messages, the`streaming/serverz` -> `total_msgs` field follows this deletion and matched its value relative to what is in storage. This is not good for taking real-time metrics of the amount of messages we receive in the streaming input.

The metrics are confusing as it takes into account what is being deleted as well:
`round(sum(rate(nss_chan_msgs_total{server_id="$server"}[5m])) by (instance))`
![Screenshot_20191118_160830](https://user-images.githubusercontent.com/9089146/69077852-58e1b780-0a15-11ea-8aea-4bca27bc552c.png)
(I'm not send this amount of messages)

Is there a possibility that we have a field for streaming like nats-server already has? `/ varz` ->` in_msgs`

Thank you!

**Comment by kozlovic** [comment]
`total_msgs` represents the number of messages reported by the store (for all channels). If messages are removed from the store due to limits, this number could go down. We could add an in_msgs/in_bytes and out_msgs/out_bytes to the monitor endpoint (I think that nats-exporter would then need to be updated). But in cluster mode, a non insignificant part of the traffic can also be attributed by the RAFT protocol. That will not be seen there, but would be part of the NATS varz in/out since we use NATS as a transport.

**Comment by kozlovic** [comment]
Here is what it would like from a streaming monitoring perspective:
```
{
  "cluster_id": "test-cluster",
  "server_id": "Pp3Rr3T71AMSMPJF2kESls",
  "version": "0.16.2",
  "go": "go1.12.13",
  "state": "STANDALONE",
  "now": "2019-11-19T16:30:55.038751-07:00",
  "start_time": "2019-11-19T16:30:16.556499-07:00",
  "uptime": "38s",
  "clients": 0,
  "subscriptions": 0,
  "channels": 1,
  "total_msgs": 1000000,
  "total_bytes": 152000000,
  "in_msgs": 2000000,
  "in_bytes": 406000000,
  "out_msgs": 20000000,
  "out_bytes": 3039834900
}
```
My channel limit is 1,000,000 messages, and I have sent 2 million messages, so you see the total_msgs capped at 1,000,000 (which is the store). There were 10 subscriptions, so the total of outbound is 20,000,000 messages.

Is that what you had in mind?

**Comment by kozlovic** [comment]
Note that the inbound bytes and outbound bytes don't match because the inbound bytes is measure as the raw bytes of the PubMsg (sent by clients), but the outbound bytes is the serialization of a MsgProto (sent to clients) and they don't have the same size.

**Comment by renanberto** [comment]
Thank you Ivan

> Is that what you had in mind?

It's similar to that.

Today api shows `/ streaming / serverz`

```
{
  "cluster_id": "involves-nats",
  "server_id": "pFJmaaSPMmi1eVOHCOcyj8",
  "version": "0.16.2",
  "go": "go1.11.13",
  "state": "CLUSTERED",
  "roll": "Follower",
  "now": "2019-11-20T14: 25: 06.00719826Z",
  "start_time": "2019-11-13T17: 52: 15.897380927Z",
  uptime: 6d20h32m50s,
  clients: 525,
  subscriptions: 25624,
  "channels": 20579,
  "total_msgs": 45435614,
  "total_bytes": 38118787666,
  "open_fds": 499,
  "max_fds": 1048576
}
```

`total_msgs` I believe is the amount of message the client is sending regardless of channels.
My suggestion is to put `in_msgs` not considering distribution to channels and not including deletion, so we know how many messages clients are sending.

However, if you have some way to put another field informing the distribution to the channels without considering the exclusion would be good too!

**Comment by kozlovic** [comment]
> `total_msgs` I believe is the amount of message the client is sending regardless of channels.

It is the total number of messages reported by the Store implementation, that is, all messages currently that could be looked-up, for all channels. Which means that say you have persistent store and stop/start the server, it will immediately report that number. You understand that if you use that as a way to know how many msgs/sec are being sent by clients, this won't work.

> My suggestion is to put `in_msgs` not considering distribution to channels and not including deletion, so we know how many messages clients are sending.

This would be similar to NATS core, that is, I would increment this number in the place where I process client inbound messages. This value will be the total of all messages being received by the server while the server is running. That value is ephemeral and will be lost after a restart. Also, since it represents the number of received messages, it can be higher than total_msgs (which is capped by the limits imposed on the channels).

> However, if you have some way to put another field informing the distribution to the channels without considering the exclusion would be good too!

Not really, but the `out_msgs` field would be updated when the server sends a message to a client, again, similar to NATS core. So after a fresh server start, if a client publishes 1 message and there are 10 consumers running, it would be in_msgs == 1 and out_msgs == 10. Note that out_msgs would then increase when there is redeliveries since messages are resent.

**Comment by renanberto** [comment]
Cool Ivan, this already works well for those who store the data (such as Prometheus). The information being ephemeral has no problem for this type of metric (at least msgs/s).

Thank you!
