### ISSUE TITLE
Failed to acknowledge a message from another connection(client)

### ISSUE THREAD

**Issue by gsngsngsn** [nats-io/nats-streaming-server#985]
Let`s say we have 3 servers A && B && C that connected to NATS. 
When server A gets a message **M** from NATS, it triggered some stuff and don't want to care of it anymore. 

Once any of the servers get a signal saying this message **M** can be ack, I would like to ack it right away, so that the server A which actually receives it doesn't have to record such message. 

In order to do so, I thought I could pass on all the information that builds up the msg.Ack() and whoever finishes processing can go Ack it. 

So in server A that received the message, I pass on the sub.ackInbox and pb.Ack  info

```
ackSubject := sub.ackInbox
ack := &pb.Ack{Subject: msg.Subject, Sequence: msg.Sequence}
b, _ := ack.Marshal()

xxx.passOn(ackSubject , b)
```

When server B get the signal where this message has been fully processed, I would like to ack the message from server B

```
subj = "_INBOX.0pyy4EZZyYC2fVXmRagWFe" //subj from server A
aaa := &pb.Ack{Subject: "test", Sequence: uint64(205)} //subject and sequence from server A
mmg, _ := aaa.Marshal()
sc.NatsConn().Publish(subj, mmg)
```

By printing those clauses in Publish method, they look identical from server A and B but of course, it doesn't work.

I am assuming I have done sth wrong here. Any ideas would be greatly appreciated!
(after taking a close look at the sdk, could be the clientId in grpc request that stops me for acking the message?)

**Comment by kozlovic** [comment]
This is really confusing.. Are servers A, B and C clustered or separate servers? If clustered, the notion of a message being acknowledged is already replicated, so you don't have to do it manually.

But most importantly, in NATS Streaming, messages are never removed from the message log simply because they are acknowledged. They are removed only due to limits on the channel.
See below links for more information.
https://docs.nats.io/nats-streaming-concepts/channels
https://docs.nats.io/nats-streaming-concepts/channels/message-log

The upcoming JetStream product will have the notion of work queue where when a message is consumed/acknowledged it is never redelivered.

**Comment by gsngsngsn** [comment]
@kozlovic thanks for the info. 

The problem for is: server A, B, C can be seen as 3 different clients to NATS. They might subscribe to same topic. 

It`s like:
1. 
NATS ----(mes#1)-----> A  ---(mes#1)----> (some unknown processes)

2.        B   <------(mes#1 processed)----- (unknown)

So, I would like B to tell NATS not to keep redelivering mes#1 to A (so, yeah, ack only, I have no intention of deleting the message at the moment.)
