### ISSUE TITLE
Uncontrolled redelivering on manual ack mode

### ISSUE THREAD

**Issue by vm-affekt** [nats-io/nats-streaming-server#991]
Hello!
We have a NATS queue handler, which performs a long operation (HTTP request to other service). Once we've noticed that NATS Streaming redelivers some messages, though they are processed successfully.
We read the [issue](https://github.com/nats-io/nats-streaming-server/issues/728) and realized that we should use ManualAck mode in our case. But this problem hasn't gone. Some messages are still being redelivered.

This is an example of a queue handler, that has Ack() and Sleep() function calls:
```golang
func main() {
  clusterID := "test-cluster"
  clientID := pyraconv.ToString(time.Now().Unix())
  sc, err := stan.Connect(clusterID, clientID)
  if err != nil {
    log.Println(err)
  }
_, err = sc.QueueSubscribe("foo", "group", func(m *stan.Msg) {
    errors := m.Ack()
    if errors != nil {
      log.Println(errors)
    }
    time.Sleep(30 * time.Second)

    fmt.Printf("id:%s | redelivered:%v | seq:%v\n", string(m.Data), m.Redelivered, m.Sequence)

  }, stan.SetManualAckMode())
  if err != nil {
    log.Println(err)
  }
  runtime.Goexit()
}
```

Despite that we acknowledge a message before long Sleep, NATS redelivers our messages:
```
id:2 | redelivered:false | seq:34
id:4 | redelivered:false | seq:36
id:6 | redelivered:false | seq:38
id:8 | redelivered:false | seq:40
id:4 | redelivered:true | seq:36
id:6 | redelivered:true | seq:38
id:8 | redelivered:true | seq:40
id:1 | redelivered:true | seq:33
id:3 | redelivered:true | seq:35
id:5 | redelivered:true | seq:37
id:7 | redelivered:true | seq:39
```
Why the manual acknowledge mode doesn't help to resolve uncontrolled redelivering problem?

Thanks!

**Comment by kozlovic** [comment]
This is because although you ack a message right away, your callback then sleep for a long time. Since you have more than one message inflight (MaxInflight is not set, so default to 1024), the server may have sent several messages at once. They are waiting to be dispatched to your callback, but from the server perspective, the timer has started when it sent those messages, so it keeps redelivering them while your callback is "stuck" processing older ones.
Even with MaxInflight(1), you would still have the problem (especially if you ack at the beginning) because then as soon as server receives the ack, it will send the next message. So go back to auto-ack or ack at the end, but still, what will happen is that if your callback takes more than the AckWait() (default 30 seconds), then that message will be redelivered.

**Comment by EliteX23** [comment]
Hi, I have same problem with redelivering. 
So if I decrease MaxInflight, will it reduce the percentage of redelivered messages?

**Comment by kozlovic** [comment]
Yes, the minimum you can set it to is 1. Then make sure your AckWait() covers most of your callback processing time. Ack the message after or use auto-ack.

**Comment by kozlovic** [comment]
what do you mean a queue overflow? In streaming, messages are not removed from channel just because they are aked (https://docs.nats.io/nats-streaming-concepts/channels/message-log).
But the danger of setting AckWait() to high is that it will take that long to get a redelivery should you want one.

**Comment by EliteX23** [comment]
now I understand. thanks

**Comment by vm-affekt** [comment]
Thank you for answers! I close the issue
