### ISSUE TITLE
Is NATS streaming server horizontally scalable?

### ISSUE THREAD

**Issue by himanshusahu06** [nats-io/nats-streaming-server#999]
We've the requirement to scale the cluster upto upto 7-11 node (but currently 3). I've benchmarked performance of the NATS streaming server for 1 node and 3 nodes and it seems 1 node nats streaming server outperforms 3 node cluster.
Is the NATS streaming server not horizontally scalable?

**Comment by wallyqs** [comment]
That's right, when in clustered mode it is not horizontally scalable... What type of storage are you using? To get more performance you could look into using the fault tolerance based active/standby setup and use partitions in order to have multiple active servers serving different channels for the same NATS Streaming cluster.

**Comment by himanshusahu06** [comment]
@wallyqs I'm using file store. Also as per https://github.com/nats-io/nats-streaming-server/issues/712 fault tolerance mode requires **shared storage (like NFS)**. Is this correct?
Also is there any read performance improvement in clustered mode?

**Comment by wallyqs** [comment]
@himanshusahu06 yes a shared storage would be required could be a db like postgres/mysql or a shared file system like EFS in AWS.  There wouldn't be read performance improvements when in clustered mode since all reads also go through the leader.

**Comment by Telavian** [comment]
This is news to me and I don't think it is documented anywhere.
How scalable is cluster mode in reality?

**Comment by kozlovic** [comment]
@Telavian We mention in the documentation (https://docs.nats.io/nats-streaming-concepts/clustering) that "NATS Streaming Server supports clustering and data replication, implemented with the Raft consensus algorithm, for the purposes of high availability."
Would adding the note in that page help?

**Comment by Telavian** [comment]
Yes it would. However being "not horizontally scalable" means what?

Assuming regular default hardware.
3 nodes max?
300 nodes max?

**Comment by kozlovic** [comment]
Clustering in NATS Streaming is for high availability, which means that it provides protection for some nodes failing. In this implementation, the leader is the one handling publish calls and sending to subscriptions, so that's why we say it is not horizontally scalable. 
A cluster of 3 or 5 nodes should really be the maximum.

**Comment by Telavian** [comment]
Ok thanks.
That is really good information.

**Comment by kozlovic** [comment]
I will had that to the documentation page..

**Comment by kozlovic** [comment]
@Telavian You can check the PR for the doc: https://github.com/nats-io/nats.docs/pull/63. Feedback is welcomed.

**Comment by kozlovic** [comment]
We have added a note in the documentation. Closing this issue now.

PS: JetStream (currently in development) is supposed to address this issue, that is, is expected to be horizontally scalable.

**Comment by Telavian** [comment]
Thanks. I am very excited for JetStream.
